In [32]:
import textwrap
import sys 
sys.path.append('../..')
import utils.utils as utils


with open('../../data/arxiv/cleaned_DPO.txt', 'r') as f:
    paper = f.read()


def print_wrapped(text, width=100):
    """
    Prints the given text wrapped to a specified width for better readability in notebooks.
    This function preserves paragraph breaks.
    """
    paragraphs = text.split('\n\n')
    for para in paragraphs:
        print(textwrap.fill(para, width=width))
        print()
        
print_wrapped(paper)

\title{Direct Preference Optimization: Your Language Model is Secretly a Reward Model}

\begin{abstract} While large-scale unsupervised language models (LMs) learn broad world knowledge
and some reasoning skills, achieving precise control of their behavior is difficult due to the
completely unsupervised nature of their training. Existing methods for gaining such steerability
collect human labels of the relative quality of model generations and fine-tune the unsupervised LM
to align with these preferences, often with reinforcement learning from human feedback (RLHF).
However, RLHF is a complex and often unstable procedure, first fitting a reward model that reflects
the human preferences, and then fine-tuning the large unsupervised LM using reinforcement learning
to maximize this estimated reward without drifting too far from the original model. In this paper we
introduce a new parameterization of the reward model in RLHF that enables extraction of the
corresponding optimal policy in closed form, allowing us to solve the standard RLHF problem with
only a simple classification loss. The resulting algorithm, which we call \textit{Direct Preference
Optimization} (DPO), is stable, performant, and computationally lightweight, eliminating the need
for sampling from the LM during fine-tuning or performing significant hyperparameter tuning. Our
experiments show that DPO can fine-tune LMs to align with human preferences as well as or better
than existing methods. Notably, fine-tuning with DPO exceeds PPO-based RLHF in ability to control
sentiment of generations, and matches or improves response quality in summarization and single-turn
dialogue while being substantially simpler to implement and train. \end{abstract}

\section{Introduction} Large unsupervised language models (LMs) trained on very large datasets
acquire surprising capabilities~\citep{chowdhery2022palm, brown2020language,
touvron2023llama,bubeck2023sparks}. However, these models are trained on data generated by humans
with a wide variety of goals, priorities, and skillsets. Some of these goals and skillsets may not
be desirable to imitate; for example, while we may want our AI coding assistant to
\textit{understand} common programming mistakes in order to correct them, nevertheless, when
generating code, we would like to bias our model toward the (potentially rare) high-quality coding
ability present in its training data. Similarly, we might want our language model to be
\textit{aware} of a common misconception believed by 50\% of people, but we certainly do not want
the model to claim this misconception to be true in 50\% of queries about it! In other words,
selecting the model's \emph{desired responses and behavior} from its very wide \textit{knowledge and
abilities} is crucial to building AI systems that are safe, performant, and controllable
\citep{ouyang2022training}. While existing methods typically steer LMs to match human preferences
using reinforcement learning (RL), we will show that the RL-based objective used by existing methods
can be optimized exactly with a simple binary cross-entropy objective, greatly simplifying the
preference learning pipeline.

\begin{figure}     \centering
\includegraphics[width=0.999\textwidth]{figures/diagrams/teaser.png}     \caption{\textbf{DPO
optimizes for human preferences while avoiding reinforcement learning.} Existing methods for fine-
tuning language models with human feedback first fit a reward model to a dataset of prompts and
human preferences over pairs of responses, and then use RL to find a policy that maximizes the
learned reward. In contrast, DPO directly optimizes for the policy best satisfying the preferences
with a simple classification objective, fitting an \textit{implicit} reward model whose
corresponding optimal policy can be extracted in closed form.}     \vspace{-2mm}
\label{fig:teaser} \end{figure}

At a high level, existing methods instill the desired behaviors into a language model using curated
sets of human preferences representing the types of behaviors that humans find safe and helpful.
This preference learning stage occurs after an initial stage of large-scale unsupervised pre-
training on a large text dataset. While the most straightforward approach to preference learning is
supervised fine-tuning on human demonstrations of high quality responses, the most successful class
of methods is reinforcement learning from human (or AI) feedback (RLHF/RLAIF;
\citep{christiano2017deep,bai2022constitutional}). RLHF methods fit a reward model to a dataset of
human preferences and then use RL to optimize a language model policy to produce responses assigned
high reward without drifting excessively far from the original model. While RLHF produces models
with impressive conversational and coding abilities, the RLHF pipeline is considerably more complex
than supervised learning, involving training multiple LMs and sampling from the LM policy in the
loop of training, incurring significant computational costs.

In this paper, we show how to directly optimize a language model to adhere to human preferences,
without explicit reward modeling or reinforcement learning. We propose Direct Preference
Optimization (DPO), an algorithm that implicitly optimizes the same objective as existing RLHF
algorithms (reward maximization with a KL-divergence constraint) but is simple to implement and
straightforward to train. Intuitively, the DPO update increases the relative log probability of
preferred to dispreferred responses, but it incorporates a dynamic, per-example importance weight
that prevents the model degeneration that we find occurs with a naive probability ratio objective.
Like existing algorithms, DPO relies on a theoretical preference model (such as the Bradley-Terry
model; \cite{bradley1952rankanalysis}) that measures how well a given reward function aligns with
empirical preference data. However, while existing methods use the preference model to define a
preference loss to train a reward model and then train a policy that optimizes the learned reward
model, DPO uses a change of variables to define the preference loss as a function of the policy
directly. Given a dataset of human preferences over model responses, DPO can therefore optimize a
policy using a simple binary cross entropy objective, producing the optimal policy to an implicit
reward function fit to the preference data.

Our main contribution is Direct Preference Optimization (DPO), a simple RL-free algorithm for
training language models from preferences. Our experiments show that DPO is at least as effective as
existing methods, including PPO-based RLHF, for learning from preferences in tasks such as sentiment
modulation, summarization, and dialogue, using language models with up to 6B parameters.

\section{Related Work}

Self-supervised language models of increasing scale learn to complete some tasks zero-shot
\citep{radford2019language} or with few-shot prompts \citep{gpt3,megatron,chowdhery2022palm}.
However, their performance on downstream tasks and alignment with user intent can be significantly
improved by fine-tuning on datasets of instructions and human-written completions \citep{mishra-
etal-2022-cross,sanh2022multitask,chung2022scaling,thoppilan2022lamda}. This `instruction-tuning'
procedure enables LLMs to generalize to instructions outside of the instruction-tuning set and
generally increase their usability \citep{chung2022scaling}. Despite the success of instruction
tuning, \textit{relative} human judgments of response quality are often easier to collect than
expert demonstrations, and thus subsequent works have fine-tuned LLMs with datasets of human
preferences, improving proficiency in translation \citep{kreutzer-etal-2018-reliability},
summarization \citep{stiennon2022learning,ziegler2020finetuning}, story-telling
\citep{ziegler2020finetuning}, and instruction-following
\citep{ouyang2022training,ramamurthy2023is}. These methods first optimize a neural network reward
function for compatibility with the dataset of preferences under a preference model such as the
Bradley-Terry model \citep{bradley1952rankanalysis}, then fine-tune a language model to maximize the
given reward using reinforcement learning algorithms, commonly REINFORCE
\citep{williams1992reinforce}, proximal policy optimization (PPO; \cite{schulman2017proximal}), or
variants \citep{ramamurthy2023is}. A closely-related line of work leverages LLMs fine-tuned for
instruction following with human feedback to generate additional synthetic preference data for
targeted attributes such as safety or harmlessness \citep{bai2022constitutional}, using only weak
supervision from humans in the form of a text rubric for the LLM's annotations. These methods
represent a convergence of two bodies of work: one body of work on training language models with
reinforcement learning for a variety of
objectives~\citep{Ranzato2015SequenceLT,paulus2018a,wu2018learning} and another body of work on
general methods for learning from human preferences \citep{christiano2017deep,kupcsik2018learning}.
Despite the appeal of using relative human preferences, fine-tuning large language models with
reinforcement learning remains a major practical challenge; this work provides a theoretically-
justified approach to optimizing relative preferences without RL.

Outside of the context of language, learning policies from preferences has been studied in both
bandit and reinforcement learning settings, and several approaches have been proposed. Contextual
bandit learning using preferences or rankings of actions, rather than rewards, is known as a
contextual dueling bandit (CDB; \cite{yue2012karmed,dudik2015contextual}). In the absence of
absolute rewards, theoretical analysis of CDBs substitutes the notion of an optimal policy with a
\textit{von Neumann winner}, a policy whose expected win rate against \textit{any} other policy is
at least 50\% \citep{dudik2015contextual}. However, in the CDB setting, preference labels are given
online, while in learning from human preferences, we typically learn from a fixed batch of offline
preference-annotated action pairs \citep{yan2022human}. Similarly, \textit{preference-based RL}
(PbRL) learns from binary preferences generated by an \textit{unknown} `scoring' function rather
than rewards \citep{BusaFekete2014,ruiz2023dueling}. Various algorithms for PbRL exist, including
methods that can reuse off-policy preference data, but generally involve first explicitly estimating
the latent scoring function (i.e. the reward model) and subsequently optimizing it
\citep{jain2013learning,BusaFekete2014,christiano2017deep,sadigh2017active,kupcsik2018learning}. We
instead present a single stage policy learning approach that directly optimizes a policy to satisfy
preferences.

\section{Preliminaries}\label{section:prelims}

We review the RLHF pipeline in \citeauthor{ziegler2020finetuning} (and later
\citep{stiennon2022learning, bai2022training, ouyang2022training}). It usually includes three
phases: 1) supervised fine-tuning (SFT); 2) preference sampling and reward learning and 3) RL
optimization.

\textbf{SFT}: RLHF typically begins by fine-tuning a pre-trained LM with supervised learning on
high-quality data for the downstream task(s) of interest (dialogue, summarization, etc.), to obtain
a model $\pisft$.

\textbf{Reward Modelling Phase}: In the second phase the SFT model is prompted with prompts $x$ to
produce pairs of answers $(y_1, y_2)\sim \pisft(y \mid x)$. These are then presented to human
labelers who express preferences for one answer, denoted as $y_w\succ y_l \mid x$ where $y_w$ and
$y_l$ denotes the preferred and dispreferred completion amongst $(y_1, y_2)$ respectively. The
preferences are assumed to be generated by some latent reward model $r^*(y, x)$, which we do not
have access to. There are a number of approaches used to model preferences, the Bradley-Terry (BT)
\cite{bradley1952rankanalysis} model being a popular choice (although more general Plackett-Luce
ranking models \citep{plackett1975analysis, luce2012individual} are also compatible with the
framework if we have access to several ranked answers). The BT model stipulates that the human
preference distribution $p^*$ can be written as: \begin{equation}\label{eq:bradley-terry}
p^*(y_1\succ y_2 \mid x)=\frac{\exp\left(r^*(x, y_1)\right)}{\exp\left(r^*(x, y_1)\right) +
\exp\left(r^*(x, y_2)\right)}. \end{equation} Assuming access to a static dataset of comparisons
$\mathcal{D}=\bigl\{x^{(i)}, y_w^{(i)}, y_l^{(i)}\bigr\}_{i=1}^N$ sampled from $p^*$, we can
parametrize a reward model $r_{\phi}(x, y)$ and estimate the parameters via maximum likelihood.
Framing the problem as a binary classification we have the negative log-likelihood loss:
\begin{equation}\label{eq:reward_model}     \mathcal{L}_R(r_{\phi}, \mathcal{D}) = -\mathbb{E}_{(x,
y_w, y_l)\sim \mathcal{D}}\bigl[\log \sigma(r_{\phi}(x, y_w)- r_{\phi}(x, y_l))\bigr] \end{equation}
where $\sigma$ is the logistic function. In the context of LMs, the network $r_{\phi}(x, y)$ is
often initialized from the SFT model $\pisft(y \mid x)$ with the addition of a linear layer on top
of the final transformer layer that produces a single scalar prediction for the reward value
\cite{ziegler2020finetuning}. To ensure a reward function with lower variance, prior works normalize
the rewards, such that  $\mathbb{E}_{x,y\sim \mathcal{D}}\left[r_\phi(x, y)\right] = 0$ for all $x$.

\textbf{RL Fine-Tuning Phase}: During the RL phase, the learned reward function is used to provide
feedback to the language model. Following prior works~\citep{jaques2017sequence, jaques2020human},
the optimization is formulated as \begin{equation}\label{eq:RL} \max_{\pi_{\theta}}
\mathbb{E}_{x\sim \mathcal{D}, y\sim \pi_{\theta}(y \mid x)}\bigl[r_{\phi}(x, y)\bigr] -
\beta\mathbb{D}_{\textrm{KL}}\bigl[\pi_{\theta}(y\mid x)\mid \mid \piref(y\mid x)\bigr],
\end{equation} where $\beta$ is a parameter controlling the deviation from the base reference policy
$\piref$, namely the initial SFT model $\pisft$.  In practice, the language model policy
$\pi_\theta$ is also initialized to $\pisft$. The added constraint is important, as it prevents the
model from deviating too far from the distribution on which the reward model is accurate, as well as
maintaining the generation diversity and preventing mode-collapse to single high-reward answers. Due
to the discrete nature of language generation, this objective is not differentiable and is typically
optimized with reinforcement learning. The standard approach \citep{ziegler2020finetuning,
stiennon2022learning, bai2022training, ouyang2022training} has been to construct the reward function
${r(x, y) = r_{\phi}(x, y) -\beta (\log \pi_{\theta}(y\mid x) - \log \piref(y\mid x))}$, and
maximize using PPO \cite{schulman2017proximal}.

\section{Direct Preference Optimization}\label{sec:DPO}

Motivated by the challenges of applying reinforcement learning algorithms on large-scale problems
such as fine-tuning language models, our goal is to derive a simple approach for policy optimization
using preferences directly. Unlike prior RLHF methods, which learn a reward and then optimize it via
RL, our approach leverages a particular choice of reward model parameterization that enables
extraction of its optimal policy in closed form, without an RL training loop.  As we will describe
next in detail, our key insight is to leverage an analytical mapping from reward functions to
optimal policies, which enables us to transform a loss function over reward functions into a loss
function over policies. This change-of-variables approach avoids fitting an explicit, standalone
reward model, while still optimizing under existing models of human preferences, such as the
Bradley-Terry model. In essence, the policy network represents both the language model and the
(implicit) reward.

\textbf{Deriving the DPO objective.} We start with the same RL objective as prior work,
Eq.~\ref{eq:RL}, under a general reward function $r$. Following prior
work~\citep{peters2007reinforcement, peng2019advantage, korbak2022reinforcement, go2023aligning}, it
is straightforward to show that the optimal solution to the KL-constrained reward maximization
objective in Eq.~\ref{eq:RL} takes the form: \begin{equation}\label{eq:op_policy}     \pi_r(y\mid x)
= \frac{1}{Z(x)}\piref(y\mid x)\exp\left(\frac{1}{\beta}r(x, y)\right), \end{equation}% where $Z(x)
=\sum_{y}\piref(y\mid x)\exp\left(\frac{1}{\beta}r(x, y)\right)$ is the partition function. See
Appendix \ref{app:derivation1} for a complete derivation. Even if we use the MLE estimate $r_{\phi}$
of the ground-truth reward function $r^*$, it is still expensive to estimate the partition function
$Z(x)$ \citep{korbak2022reinforcement, go2023aligning}, which makes this representation hard to
utilize in practice. However, we can rearrange Eq.~\ref{eq:op_policy} to express the reward function
in terms of its corresponding optimal policy $\pi_r$, the reference policy $\piref$, and the unknown
partition function $Z(\cdot)$. Specifically, we first take the logarithm of both sides of
Eq.~\ref{eq:op_policy} and then with some algebra we obtain: \begin{equation}\label{eq:main_eq}
r(x,y) =\beta \log \frac{\pi_r(y\mid x)}{\piref(y\mid x)} + \beta \log Z(x). \end{equation} We can
apply this reparameterization to the ground-truth reward $r^*$ and corresponding optimal model
$\pi^*$. Fortunately, the Bradley-Terry model depends only on the difference of rewards between two
completions, i.e., ${p^*(y_1 \succ y_2 \mid x) = \sigma(r^*(x, y_1) - r^*(x, y_2))}$. Substituting
the reparameterization in Eq.~\ref{eq:main_eq} for $r^*(x,y)$ into the preference model
Eq.~\ref{eq:bradley-terry}, the partition function cancels, and we can express the human preference
probability in terms of only the optimal policy $\pi^*$ and reference policy $\piref$. Thus, the
optimal RLHF policy $\pi^*$ under the Bradley-Terry model satisfies the preference model:
\begin{equation}\label{eq:objective}     p^*(y_1\succ y_2 \mid x)=\frac{1}{1 + \exp\left(\beta \log
\frac{\pi^*(y_2\mid x)}{\piref(y_2\mid x)} - \beta \log \frac{\pi^*(y_1\mid x)}{\piref(y_1\mid
x)}\right)} \end{equation} The derivation is in Appendix~\ref{app:derivation2}. While
Eq.~\ref{eq:objective} uses the Bradley-Terry model, we can similarly derive expressions under the
more general Plackett-Luce models~\citep{plackett1975analysis, luce2012individual}, shown in
Appendix~\ref{app:plackett_luce_models}.

Now that we have the probability of human preference data in terms of the optimal policy rather than
the reward model, we can formulate a maximum likelihood objective for a parametrized policy
$\pi_\theta$. Analogous to the reward modeling approach (i.e. Eq.~\ref{eq:reward_model}), our policy
objective becomes: \begin{equation}\label{eq:optimum_model}     \mathcal{L}_\text{DPO}(\pi_{\theta};
\piref) = -\mathbb{E}_{(x, y_w, y_l)\sim \mathcal{D}}\left[\log \sigma \left(\beta \log
\frac{\pi_{\theta}(y_w\mid x)}{\piref(y_w\mid x)} - \beta \log \frac{\pi_{\theta}(y_l\mid
x)}{\piref(y_l\mid x)}\right)\right]. \end{equation} This way, we fit an implicit reward using an
alternative parameterization, whose optimal policy is simply $\pi_\theta$. Moreover, since our
procedure is equivalent to fitting a reparametrized Bradley-Terry model, it enjoys certain
theoretical properties, such as consistencies under suitable assumption of the preference data
distribution \cite{bong2022generalized}. In Section~\ref{sec:theory}, we further discuss theoretical
properties of DPO in relation to other works.

\textbf{What does the DPO update do?} For a mechanistic understanding of DPO, it is useful to
analyze the gradient of the loss function $\mathcal{L}_\text{DPO}$. The gradient with respect to the
parameters $\theta$ can be written as: \begin{multline*}\label{eq:gradient}     \nabla_\theta

### [Old Prompts] Generate Factual Recall Knowledge Probe

In [6]:
prompt = {}
# prompt['system'] = """Your task is to extract the key knowledge facts in a paper. 

# ##
# These claims should be stand alone claims that have meaning on their own without context, offer generalizable knowledge, and are descriptive rather than prescriptive or evaluative e.g. . For instance, the claim shouldn't be specific to a particular experiment of the paper, but a general insight that follows. List them word for word how it appears in the paper."""
# prompt['system'] = """Your task is to act as a knowledge extraction engine. From the provided text, extract standalone, factual claims that represent generalizable knowledge. The claims should be objective, descriptive, and self-contained.
# # Key Criteria For Extracting Claims

# 1.  **Objective and Factual:** Extract statements presented as facts or claims, not opinions, subjective evaluations, or superlative statements.
#     *   GOOD: "Direct Preference Optimization (DPO) is an algorithm for aligning language models with human preferences."
#     *   BAD: "We believe DPO is the most promising approach for alignment." (Subjective belief)
#     *   BAD: "DPO is the best method." (Superlative statement)

# 2.  **Self-Contained:** The claim must be fully understandable on its own, without requiring context from surrounding sentences. It should not include any pronouns or references that aren't included inthe claim.
#     *   GOOD: "The DPO loss function is derived from a mapping between policy probabilities and an implicit reward."
#     *   BAD: "This loss function is more stable." (Requires external context for "This")

# 3.  **Generalizable Knowledge, not Paper-Specific Results:** Focus on definitions, mechanisms, and core concepts. Do not extract claims about the paper's specific findings, experimental setup, or citations.
#     *   GOOD: "Reinforcement Learning from Human Feedback (RLHF) typically involves training a separate reward model on preference data."
#     *   BAD: "Our experiments show a 5% improvement on the benchmark." (Specific result)
#     *   BAD: "As shown by Smith et al. (2023), the method is effective." (Relies on a citation)
prompt['system'] = """Carefully read the provided text. Your job is to extract knowledge from the provided paper.

# Detailed Instructions
 - Specifically, I want you to identify the "pieces of knowledge" from the following text.
    - We define a piece of knowledge as an informative statement that makes sense on its own without further context. 
    - The piece of knowledge can be a single sentence, or a paragraph, or even a section of the paper. Whatever the case, it should be fully self-contained and coherent. 
    - Demarcate the piece of knowledge by marking the beginning and end of the "knowledge" in the paper with <knowledge> and </knowledge> tags.
    - Again, place the tags around the entire piece of knowledge so that it's self-contained. For instance, if there is a reference to a "reward function", the earlier formal mention of the reward function should be included in the span of the piee of knowledge.
 - Do this for all pieces of knowledge from the following text.
 - Return the entire text with this annotation."""

# 2.  **Descriptive, not Prescriptive:** The claim should describe what something *is* or *does*, not give advice or instructions.
#     *   GOOD: "DPO directly optimizes the language model policy using preference data."
#     *   BAD: "To align your model, you should use the DPO method." (Prescriptive advice)

prompt['user'] = f"""Paper: {paper}"""
extracted_claims = []
import concurrent.futures

def query_single():
    return utils.query_llm(prompt, model='gpt-4.1', temperature=0.1, max_tokens=32768)

with concurrent.futures.ThreadPoolExecutor() as executor:
    futures = [executor.submit(query_single) for _ in range(1)]
    extracted_claims = [future.result() for future in futures]
print(extracted_claims[0])

Paper: \title{Direct Preference Optimization: Your Language Model is Secretly a Reward Model}

\begin{abstract}
<knowledge>
While large-scale unsupervised language models (LMs) learn broad world knowledge and some reasoning skills, achieving precise control of their behavior is difficult due to the completely unsupervised nature of their training.
Existing methods for gaining such steerability collect human labels of the relative quality of model generations and fine-tune the unsupervised LM to align with these preferences, often with reinforcement learning from human feedback (RLHF).
However, RLHF is a complex and often unstable procedure, first fitting a reward model that reflects the human preferences, and then fine-tuning the large unsupervised LM using reinforcement learning to maximize this estimated reward without drifting too far from the original model.
In this paper we introduce a new parameterization of the reward model in RLHF that enables extraction of the corresponding optimal policy in closed form, allowing us to solve the standard RLHF problem with only a simple classification loss.
The resulting algorithm, which we call \textit{Direct Preference Optimization} (DPO), is stable, performant, and computationally lightweight, eliminating the need for sampling from the LM during fine-tuning or performing significant hyperparameter tuning.
Our experiments show that DPO can fine-tune LMs to align with human preferences as well as or better than existing methods. Notably, fine-tuning with DPO exceeds PPO-based RLHF in ability to control sentiment of generations, and matches or improves response quality in summarization and single-turn dialogue while being substantially simpler to implement and train.
</knowledge>
\end{abstract}

\section{Introduction}
<knowledge>
Large unsupervised language models (LMs) trained on very large datasets acquire surprising capabilities~\citep{chowdhery2022palm, brown2020language, touvron2023llama,bubeck2023sparks}. However, these models are trained on data generated by humans with a wide variety of goals, priorities, and skillsets. Some of these goals and skillsets may not be desirable to imitate; for example, while we may want our AI coding assistant to \textit{understand} common programming mistakes in order to correct them, nevertheless, when generating code, we would like to bias our model toward the (potentially rare) high-quality coding ability present in its training data. Similarly, we might want our language model to be \textit{aware} of a common misconception believed by 50\% of people, but we certainly do not want the model to claim this misconception to be true in 50\% of queries about it! In other words, selecting the model's \emph{desired responses and behavior} from its very wide \textit{knowledge and abilities} is crucial to building AI systems that are safe, performant, and controllable \citep{ouyang2022training}. While existing methods typically steer LMs to match human preferences using reinforcement learning (RL), we will show that the RL-based objective used by existing methods can be optimized exactly with a simple binary cross-entropy objective, greatly simplifying the preference learning pipeline.
</knowledge>

\begin{figure}
    \centering
    \includegraphics[width=0.999\textwidth]{figures/diagrams/teaser.png}
    \caption{\textbf{DPO optimizes for human preferences while avoiding reinforcement learning.} Existing methods for fine-tuning language models with human feedback first fit a reward model to a dataset of prompts and human preferences over pairs of responses, and then use RL to find a policy that maximizes the learned reward. In contrast, DPO directly optimizes for the policy best satisfying the preferences with a simple classification objective, fitting an \textit{implicit} reward model whose corresponding optimal policy can be extracted in closed form.}
    \vspace{-2mm}
    \label{fig:teaser}
\end{figure}

<knowledge>
At a high level, existing methods instill the desired behaviors into a language model using curated sets of human preferences representing the types of behaviors that humans find safe and helpful. This preference learning stage occurs after an initial stage of large-scale unsupervised pre-training on a large text dataset. While the most straightforward approach to preference learning is supervised fine-tuning on human demonstrations of high quality responses, the most successful class of methods is reinforcement learning from human (or AI) feedback (RLHF/RLAIF; \citep{christiano2017deep,bai2022constitutional}). RLHF methods fit a reward model to a dataset of human preferences and then use RL to optimize a language model policy to produce responses assigned high reward without drifting excessively far from the original model. While RLHF produces models with impressive conversational and coding abilities, the RLHF pipeline is considerably more complex than supervised learning, involving training multiple LMs and sampling from the LM policy in the loop of training, incurring significant computational costs.
</knowledge>

<knowledge>
In this paper, we show how to directly optimize a language model to adhere to human preferences, without explicit reward modeling or reinforcement learning. We propose Direct Preference Optimization (DPO), an algorithm that implicitly optimizes the same objective as existing RLHF algorithms (reward maximization with a KL-divergence constraint) but is simple to implement and straightforward to train. Intuitively, the DPO update increases the relative log probability of preferred to dispreferred responses, but it incorporates a dynamic, per-example importance weight that prevents the model degeneration that we find occurs with a naive probability ratio objective. Like existing algorithms, DPO relies on a theoretical preference model (such as the Bradley-Terry model; \cite{bradley1952rankanalysis}) that measures how well a given reward function aligns with empirical preference data. However, while existing methods use the preference model to define a preference loss to train a reward model and then train a policy that optimizes the learned reward model, DPO uses a change of variables to define the preference loss as a function of the policy directly. Given a dataset of human preferences over model responses, DPO can therefore optimize a policy using a simple binary cross entropy objective, producing the optimal policy to an implicit reward function fit to the preference data}.
</knowledge>

<knowledge>
Our main contribution is Direct Preference Optimization (DPO), a simple RL-free algorithm for training language models from preferences. Our experiments show that DPO is at least as effective as existing methods, including PPO-based RLHF, for learning from preferences in tasks such as sentiment modulation, summarization, and dialogue, using language models with up to 6B parameters.
</knowledge>

\section{Related Work}

<knowledge>
Self-supervised language models of increasing scale learn to complete some tasks zero-shot \citep{radford2019language} or with few-shot prompts \citep{gpt3,megatron,chowdhery2022palm}. However, their performance on downstream tasks and alignment with user intent can be significantly improved by fine-tuning on datasets of instructions and human-written completions \citep{mishra-etal-2022-cross,sanh2022multitask,chung2022scaling,thoppilan2022lamda}. This `instruction-tuning' procedure
enables LLMs to generalize to instructions outside of the instruction-tuning set and generally increase their usability \citep{chung2022scaling}. Despite the success of instruction tuning, \textit{relative} human judgments of response quality are often easier to collect than expert demonstrations, and thus subsequent works have fine-tuned LLMs with datasets of human preferences, improving proficiency in translation \citep{kreutzer-etal-2018-reliability}, summarization \citep{stiennon2022learning,ziegler2020finetuning}, story-telling \citep{ziegler2020finetuning}, and instruction-following \citep{ouyang2022training,ramamurthy2023is}. These methods first optimize a neural network reward function for compatibility with the dataset of preferences under a preference model such as the Bradley-Terry model \citep{bradley1952rankanalysis}, then fine-tune a language model to maximize the given reward using reinforcement learning algorithms, commonly REINFORCE \citep{williams1992reinforce}, proximal policy optimization (PPO; \cite{schulman2017proximal}), or variants \citep{ramamurthy2023is}. A closely-related line of work leverages LLMs fine-tuned for instruction following with human feedback to generate additional synthetic preference data for targeted attributes such as safety or harmlessness \citep{bai2022constitutional}, using only weak supervision from humans in the form of a text rubric for the LLM's annotations. These methods represent a convergence of two bodies of work: one body of work on training language models with reinforcement learning for a variety of objectives~\citep{Ranzato2015SequenceLT,paulus2018a,wu2018learning} and another body of work on general methods for learning from human preferences \citep{christiano2017deep,kupcsik2018learning}.
Despite the appeal of using relative human preferences, fine-tuning large language models with reinforcement learning remains a major practical challenge; this work provides a theoretically-justified approach to optimizing relative preferences without RL.
</knowledge>

<knowledge>
Outside of the context of language, learning policies from preferences has been studied in both bandit and reinforcement learning settings, and several approaches have been proposed. Contextual bandit learning using preferences or rankings of actions, rather than rewards, is known as a contextual dueling bandit (CDB; \cite{yue2012karmed,dudik2015contextual}). In the absence of absolute rewards, theoretical analysis of CDBs substitutes the notion of an optimal policy with a \textit{von Neumann winner}, a policy whose expected win rate against \textit{any} other policy is at least 50\% \citep{dudik2015contextual}. However, in the CDB setting, preference labels are given online, while in learning from human preferences, we typically learn from a fixed batch of offline preference-annotated action pairs \citep{yan2022human}. Similarly, \textit{preference-based RL} (PbRL) learns from binary preferences generated by an \textit{unknown} `scoring' function rather than rewards \citep{BusaFekete2014,ruiz2023dueling}. Various algorithms for PbRL exist, including methods that can reuse off-policy preference data, but generally involve first explicitly estimating the latent scoring function (i.e. the reward model) and subsequently optimizing it \citep{jain2013learning,BusaFekete2014,christiano2017deep,sadigh2017active,kupcsik2018learning}. We instead present a single stage policy learning approach that directly optimizes a policy to satisfy preferences.
</knowledge>

\section{Preliminaries}\label{section:prelims}

<knowledge>
We review the RLHF pipeline in \citeauthor{ziegler2020finetuning} (and later \citep{stiennon2022learning, bai2022training, ouyang2022training}). It usually includes three phases: 1) supervised fine-tuning (SFT); 2) preference sampling and reward learning and 3) RL optimization.

\textbf{SFT}: RLHF typically begins by fine-tuning a pre-trained LM with supervised learning on high-quality data for the downstream task(s) of interest (dialogue, summarization, etc.), to obtain a model $\pisft$.

\textbf{Reward Modelling Phase}: In the second phase the SFT model is prompted with prompts $x$ to produce pairs of answers $(y_1, y_2)\sim \pisft(y \mid x)$. These are then presented to human labelers who express preferences for one answer, denoted as $y_w\succ y_l \mid x$ where $y_w$ and $y_l$ denotes the preferred and dispreferred completion amongst $(y_1, y_2)$ respectively. The preferences are assumed to be generated by some latent reward model $r^*(y, x)$, which we do not have access to. There are a number of approaches used to model preferences, the Bradley-Terry (BT) \cite{bradley1952rankanalysis} model being a popular choice (although more general Plackett-Luce ranking models \citep{plackett1975analysis, luce2012individual} are also compatible with the framework if we have access to several ranked answers). The BT model stipulates that the human preference distribution $p^*$ can be written as:
\begin{equation}\label{eq:bradley-terry}
    p^*(y_1\succ y_2 \mid x)=\frac{\exp\left(r^*(x, y_1)\right)}{\exp\left(r^*(x, y_1)\right) + \exp\left(r^*(x, y_2)\right)}.
\end{equation}
Assuming access to a static dataset of comparisons $\mathcal{D}=\bigl\{x^{(i)}, y_w^{(i)}, y_l^{(i)}\bigr\}_{i=1}^N$ sampled from $p^*$, we can parametrize a reward model $r_{\phi}(x, y)$ and estimate the parameters via maximum likelihood. Framing the problem as a binary classification we have the negative log-likelihood loss:
\begin{equation}\label{eq:reward_model}
    \mathcal{L}_R(r_{\phi}, \mathcal{D}) = -\mathbb{E}_{(x, y_w, y_l)\sim \mathcal{D}}\bigl[\log \sigma(r_{\phi}(x, y_w)- r_{\phi}(x, y_l))\bigr]
\end{equation}
where $\sigma$ is the logistic function. In the context of LMs, the network $r_{\phi}(x, y)$ is often initialized from the SFT model $\pisft(y \mid x)$ with the addition of a linear layer on top of the final transformer layer that produces a single scalar prediction for the reward value \cite{ziegler2020finetuning}. To ensure a reward function with lower variance, prior works normalize the rewards, such that  $\mathbb{E}_{x,y\sim \mathcal{D}}\left[r_\phi(x, y)\right] = 0$ for all $x$.

\textbf{RL Fine-Tuning Phase}: During the RL phase, the learned reward function is used to provide feedback to the language model. Following prior works~\citep{jaques2017sequence, jaques2020human}, the optimization is formulated as
\begin{equation}\label{eq:RL}
\max_{\pi_{\theta}}  \mathbb{E}_{x\sim \mathcal{D}, y\sim \pi_{\theta}(y \mid x)}\bigl[r_{\phi}(x, y)\bigr] - \beta\mathbb{D}_{\textrm{KL}}\bigl[\pi_{\theta}(y\mid x)\mid \mid \piref(y\mid x)\bigr],
\end{equation}
where $\beta$ is a parameter controlling the deviation from the base reference policy $\piref$, namely the initial SFT model $\pisft$.
In practice, the language model policy $\pi_\theta$ is also initialized to $\pisft$. The added constraint is important, as it prevents the model from deviating too far from the distribution on which the reward model is accurate, as well as maintaining the generation diversity and preventing mode-collapse to single high-reward answers. Due to the discrete nature of language generation, this objective is not differentiable and is typically optimized with reinforcement learning. The standard approach \citep{ziegler2020finetuning, stiennon2022learning, bai2022training, ouyang2022training} has been to construct the reward function ${r(x, y) = r_{\phi}(x, y) -\beta (\log \pi_{\theta}(y\mid x) - \log \piref(y\mid x))}$, and maximize using PPO \cite{schulman2017proximal}.
</knowledge>

\section{Direct Preference Optimization}\label{sec:DPO}

<knowledge>
Motivated by the challenges of applying reinforcement learning algorithms on large-scale problems such as fine-tuning language models, our goal is to derive a simple approach for policy optimization using preferences directly. Unlike prior RLHF methods, which learn a reward and then optimize it via RL, our approach leverages a particular choice of reward model parameterization that enables extraction of its optimal policy in closed form, without an RL training loop.
As we will describe next in detail, our key insight is to leverage an analytical mapping from reward functions to optimal policies, which enables us to transform a loss function over reward functions into a loss function over policies.
This change-of-variables approach avoids fitting an explicit, standalone reward model, while still optimizing under existing models of human preferences, such as the Bradley-Terry model. In essence, the policy network represents both the language model and the (implicit) reward.
</knowledge>

<knowledge>
\textbf{Deriving the DPO objective.} We start with the same RL objective as prior work, Eq.~\ref{eq:RL}, under a general reward function $r$. Following prior work~\citep{peters2007reinforcement, peng2019advantage, korbak2022reinforcement, go2023aligning}, it is straightforward to show that the optimal solution to the KL-constrained reward maximization objective in Eq.~\ref{eq:RL} takes the form:
\begin{equation}\label{eq:op_policy}
    \pi_r(y\mid x) = \frac{1}{Z(x)}\piref(y\mid x)\exp\left(\frac{1}{\beta}r(x, y)\right),
\end{equation}%
where $Z(x) =\sum_{y}\piref(y\mid x)\exp\left(\frac{1}{\beta}r(x, y)\right)$ is the partition function. See Appendix \ref{app:derivation1} for a complete derivation. Even if we use the MLE estimate $r_{\phi}$ of the ground-truth reward function $r^*$, it is still expensive to estimate the partition function $Z(x)$ \citep{korbak2022reinforcement, go2023aligning}, which makes this representation hard to utilize in practice. However, we can rearrange Eq.~\ref{eq:op_policy} to express the reward function in terms of its corresponding optimal policy $\pi_r$, the reference policy $\piref$, and the unknown partition function $Z(\cdot)$. Specifically, we first take the logarithm of both sides of Eq.~\ref{eq:op_policy} and then with some algebra we obtain:
\begin{equation}\label{eq:main_eq}
    r(x,y) =\beta \log \frac{\pi_r(y\mid x)}{\piref(y\mid x)} + \beta \log Z(x).
\end{equation}
We can apply this reparameterization to the ground-truth reward $r^*$ and corresponding optimal model $\pi^*$. Fortunately, the Bradley-Terry model depends only on the difference of rewards between two completions, i.e., ${p^*(y_1 \succ y_2 \mid x) = \sigma(r^*(x, y_1) - r^*(x, y_2))}$. Substituting the reparameterization in Eq.~\ref{eq:main_eq} for $r^*(x,y)$ into the preference model Eq.~\ref{eq:bradley-terry}, the partition function cancels, and we can express the human preference probability in terms of only the optimal policy $\pi^*$ and reference policy $\piref$. Thus, the optimal RLHF policy $\pi^*$ under the Bradley-Terry model satisfies the preference model:
\begin{equation}\label{eq:objective}
    p^*(y_1\succ y_2 \mid x)=\frac{1}{1 + \exp\left(\beta \log \frac{\pi^*(y_2\mid x)}{\piref(y_2\mid x)} - \beta \log \frac{\pi^*(y_1\mid x)}{\piref(y_1\mid x)}\right)}
\end{equation}
The derivation is in Appendix~\ref{app:derivation2}. While Eq.~\ref{eq:objective} uses the Bradley-Terry model, we can similarly derive expressions under the more general Plackett-Luce models~\citep{plackett1975analysis, luce2012individual}, shown in Appendix~\ref{app:plackett_luce_models}.

Now that we have the probability of human preference data in terms of the optimal policy rather than the reward model, we can formulate a maximum likelihood objective for a parametrized policy $\pi_\theta$. Analogous to the reward modeling approach (i.e. Eq.~\ref{eq:reward_model}), our policy objective becomes:
\begin{equation}\label{eq:optimum_model}
    \mathcal{L}_\text{DPO}(\pi_{\theta}; \piref) = -\mathbb{E}_{(x, y_w, y_l)\sim \mathcal{D}}\left[\log \sigma \left(\beta \log \frac{\pi_{\theta}(y_w\mid x)}{\piref(y_w\mid x)} - \beta \log \frac{\pi_{\theta}(y_l\mid x)}{\piref(y_l\mid x)}\right)\right].
\end{equation}
This way, we fit an implicit reward using an alternative parameterization, whose optimal policy is simply $\pi_\theta$. Moreover, since our procedure is equivalent to fitting a reparametrized Bradley-Terry model, it enjoys certain theoretical properties, such as consistencies under suitable assumption of the preference data distribution \cite{bong2022generalized}. In Section~\ref{sec:theory}, we further discuss theoretical properties of DPO in relation to other works.
</knowledge>

<knowledge>

In [20]:
extraction_prompt = """Your task is to act as a text segmenter. Carefully read the provided text from a research paper and identify all "pieces of knowledge."

# Definition of a "Piece of Knowledge"
A piece of knowledge is an informative statement that is:
1.  **Self-Contained:** It must be fully understandable on its own without needing sentences before or after it. If it uses a specific term (e.g., "the reward function"), the definition or first mention of that term should be included in the segment.
2.  **Coherent:** The extracted text should form a logical, complete thought. This can range from a single, dense sentence to a full paragraph that explains a concept.

# What to Exclude (Do NOT tag these):
- **Paper Structure & Meta-Commentary:** Sentences about the paper itself (e.g., "In this section, we describe...", "Figure 3 shows...", "Our contributions are threefold..."). 
- **Citations:** Sentences that primarily exist to cite other work (e.g., "This was previously shown by Smith et al. (2023).").
- **Transitional Sentences:** Text that only serves to connect ideas without adding new information (e.g., "Furthermore...", "Now we turn to...", "In addition to the above...").
- **Author Speculation or Rhetorical Questions:** Subjective statements or questions posed to the reader (e.g., "This result is quite surprising.", "But what if the model could...?").

# Instructions
1.  Read the entire text carefully.
2.  Identify all segments that fit the definition of a "piece of knowledge" and do not fall into the exclusion categories.
3.  Demarcate each piece of knowledge by wrapping it in `<knowledge>` and `</knowledge>` tags.
4.  Return the entire original text with these annotations. Do not modify or summarize the text itself.
"""
prompt['user'] = f"""Paper: {paper}"""
extracted_claims = []
import concurrent.futures

def query_single():
    return utils.query_llm(prompt, model='gpt-4.1', temperature=0.1, max_tokens=32768)

with concurrent.futures.ThreadPoolExecutor() as executor:
    futures = [executor.submit(query_single) for _ in range(1)]
    extracted_claims = [future.result() for future in futures]
print_wrapped(extracted_claims[0])

Paper: \title{Direct Preference Optimization: Your Language Model is Secretly a Reward Model}

\begin{abstract} <knowledge> While large-scale unsupervised language models (LMs) learn broad world
knowledge and some reasoning skills, achieving precise control of their behavior is difficult due to
the completely unsupervised nature of their training. Existing methods for gaining such steerability
collect human labels of the relative quality of model generations and fine-tune the unsupervised LM
to align with these preferences, often with reinforcement learning from human feedback (RLHF).
However, RLHF is a complex and often unstable procedure, first fitting a reward model that reflects
the human preferences, and then fine-tuning the large unsupervised LM using reinforcement learning
to maximize this estimated reward without drifting too far from the original model. In this paper we
introduce a new parameterization of the reward model in RLHF that enables extraction of the
corresponding optimal policy in closed form, allowing us to solve the standard RLHF problem with
only a simple classification loss. The resulting algorithm, which we call \textit{Direct Preference
Optimization} (DPO), is stable, performant, and computationally lightweight, eliminating the need
for sampling from the LM during fine-tuning or performing significant hyperparameter tuning. Our
experiments show that DPO can fine-tune LMs to align with human preferences as well as or better
than existing methods. Notably, fine-tuning with DPO exceeds PPO-based RLHF in ability to control
sentiment of generations, and matches or improves response quality in summarization and single-turn
dialogue while being substantially simpler to implement and train. </knowledge> \end{abstract}

\section{Introduction} <knowledge> Large unsupervised language models (LMs) trained on very large
datasets acquire surprising capabilities~\citep{chowdhery2022palm, brown2020language,
touvron2023llama,bubeck2023sparks}. However, these models are trained on data generated by humans
with a wide variety of goals, priorities, and skillsets. Some of these goals and skillsets may not
be desirable to imitate; for example, while we may want our AI coding assistant to
\textit{understand} common programming mistakes in order to correct them, nevertheless, when
generating code, we would like to bias our model toward the (potentially rare) high-quality coding
ability present in its training data. Similarly, we might want our language model to be
\textit{aware} of a common misconception believed by 50\% of people, but we certainly do not want
the model to claim this misconception to be true in 50\% of queries about it! In other words,
selecting the model's \emph{desired responses and behavior} from its very wide \textit{knowledge and
abilities} is crucial to building AI systems that are safe, performant, and controllable
\citep{ouyang2022training}. While existing methods typically steer LMs to match human preferences
using reinforcement learning (RL), we will show that the RL-based objective used by existing methods
can be optimized exactly with a simple binary cross-entropy objective, greatly simplifying the
preference learning pipeline. </knowledge>

\begin{figure}     \centering
\includegraphics[width=0.999\textwidth]{figures/diagrams/teaser.png}     \caption{\textbf{DPO
optimizes for human preferences while avoiding reinforcement learning.} Existing methods for fine-
tuning language models with human feedback first fit a reward model to a dataset of prompts and
human preferences over pairs of responses, and then use RL to find a policy that maximizes the
learned reward. In contrast, DPO directly optimizes for the policy best satisfying the preferences
with a simple classification objective, fitting an \textit{implicit} reward model whose
corresponding optimal policy can be extracted in closed form.}     \vspace{-2mm}
\label{fig:teaser} \end{figure>

<knowledge> At a high level, existing methods instill the desired behaviors into a language model
using curated sets of human preferences representing the types of behaviors that humans find safe
and helpful. This preference learning stage occurs after an initial stage of large-scale
unsupervised pre-training on a large text dataset. While the most straightforward approach to
preference learning is supervised fine-tuning on human demonstrations of high quality responses, the
most successful class of methods is reinforcement learning from human (or AI) feedback (RLHF/RLAIF;
\citep{christiano2017deep,bai2022constitutional}). RLHF methods fit a reward model to a dataset of
human preferences and then use RL to optimize a language model policy to produce responses assigned
high reward without drifting excessively far from the original model. While RLHF produces models
with impressive conversational and coding abilities, the RLHF pipeline is considerably more complex
than supervised learning, involving training multiple LMs and sampling from the LM policy in the
loop of training, incurring significant computational costs. </knowledge>

<knowledge> In this paper, we show how to directly optimize a language model to adhere to human
preferences, without explicit reward modeling or reinforcement learning. We propose Direct
Preference Optimization (DPO), an algorithm that implicitly optimizes the same objective as existing
RLHF algorithms (reward maximization with a KL-divergence constraint) but is simple to implement and
straightforward to train. Intuitively, the DPO update increases the relative log probability of
preferred to dispreferred responses, but it incorporates a dynamic, per-example importance weight
that prevents the model degeneration that we find occurs with a naive probability ratio objective.
Like existing algorithms, DPO relies on a theoretical preference model (such as the Bradley-Terry
model; \cite{bradley1952rankanalysis}) that measures how well a given reward function aligns with
empirical preference data. However, while existing methods use the preference model to define a
preference loss to train a reward model and then train a policy that optimizes the learned reward
model, DPO uses a change of variables to define the preference loss as a function of the policy
directly. Given a dataset of human preferences over model responses, DPO can therefore optimize a
policy using a simple binary cross entropy objective, producing the optimal policy to an implicit
reward function fit to the preference data}. </knowledge>

<knowledge> Our main contribution is Direct Preference Optimization (DPO), a simple RL-free
algorithm for training language models from preferences. Our experiments show that DPO is at least
as effective as existing methods, including PPO-based RLHF, for learning from preferences in tasks
such as sentiment modulation, summarization, and dialogue, using language models with up to 6B
parameters. </knowledge>

\section{Related Work} <knowledge> Self-supervised language models of increasing scale learn to
complete some tasks zero-shot \citep{radford2019language} or with few-shot prompts
\citep{gpt3,megatron,chowdhery2022palm}. However, their performance on downstream tasks and
alignment with user intent can be significantly improved by fine-tuning on datasets of instructions
and human-written completions \citep{mishra-
etal-2022-cross,sanh2022multitask,chung2022scaling,thoppilan2022lamda}. This `instruction-tuning'
procedure enables LLMs to generalize to instructions outside of the instruction-tuning set and
generally increase their usability \citep{chung2022scaling}. Despite the success of instruction
tuning, \textit{relative} human judgments of response quality are often easier to collect than
expert demonstrations, and thus subsequent works have fine-tuned LLMs with datasets of human
preferences, improving proficiency in translation \citep{kreutzer-etal-2018-reliability},
summarization \citep{stiennon2022learning,ziegler2020finetuning}, story-telling
\citep{ziegler2020finetuning}, and instruction-following
\citep{ouyang2022training,ramamurthy2023is}. These methods first optimize a neural network reward
function for compatibility with the dataset of preferences under a preference model such as the
Bradley-Terry model \citep{bradley1952rankanalysis}, then fine-tune a language model to maximize the
given reward using reinforcement learning algorithms, commonly REINFORCE
\citep{williams1992reinforce}, proximal policy optimization (PPO; \cite{schulman2017proximal}), or
variants \citep{ramamurthy2023is}. A closely-related line of work leverages LLMs fine-tuned for
instruction following with human feedback to generate additional synthetic preference data for
targeted attributes such as safety or harmlessness \citep{bai2022constitutional}, using only weak
supervision from humans in the form of a text rubric for the LLM's annotations. These methods
represent a convergence of two bodies of work: one body of work on training language models with
reinforcement learning for a variety of
objectives~\citep{Ranzato2015SequenceLT,paulus2018a,wu2018learning} and another body of work on
general methods for learning from human preferences \citep{christiano2017deep,kupcsik2018learning}.
Despite the appeal of using relative human preferences, fine-tuning large language models with
reinforcement learning remains a major practical challenge; this work provides a theoretically-
justified approach to optimizing relative preferences without RL. </knowledge>

<knowledge> Outside of the context of language, learning policies from preferences has been studied
in both bandit and reinforcement learning settings, and several approaches have been proposed.
Contextual bandit learning using preferences or rankings of actions, rather than rewards, is known
as a contextual dueling bandit (CDB; \cite{yue2012karmed,dudik2015contextual}). In the absence of
absolute rewards, theoretical analysis of CDBs substitutes the notion of an optimal policy with a
\textit{von Neumann winner}, a policy whose expected win rate against \textit{any} other policy is
at least 50\% \citep{dudik2015contextual}. However, in the CDB setting, preference labels are given
online, while in learning from human preferences, we typically learn from a fixed batch of offline
preference-annotated action pairs \citep{yan2022human}. Similarly, \textit{preference-based RL}
(PbRL) learns from binary preferences generated by an \textit{unknown} `scoring' function rather
than rewards \citep{BusaFekete2014,ruiz2023dueling}. Various algorithms for PbRL exist, including
methods that can reuse off-policy preference data, but generally involve first explicitly estimating
the latent scoring function (i.e. the reward model) and subsequently optimizing it
\citep{jain2013learning,BusaFekete2014,christiano2017deep,sadigh2017active,kupcsik2018learning}. We
instead present a single stage policy learning approach that directly optimizes a policy to satisfy
preferences. </knowledge>

\section{Preliminaries}\label{section:prelims}

<knowledge> We review the RLHF pipeline in \citeauthor{ziegler2020finetuning} (and later
\citep{stiennon2022learning, bai2022training, ouyang2022training}). It usually includes three
phases: 1) supervised fine-tuning (SFT); 2) preference sampling and reward learning and 3) RL
optimization.

\textbf{SFT}: RLHF typically begins by fine-tuning a pre-trained LM with supervised learning on
high-quality data for the downstream task(s) of interest (dialogue, summarization, etc.), to obtain
a model $\pisft$.

\textbf{Reward Modelling Phase}: In the second phase the SFT model is prompted with prompts $x$ to
produce pairs of answers $(y_1, y_2)\sim \pisft(y \mid x)$. These are then presented to human
labelers who express preferences for one answer, denoted as $y_w\succ y_l \mid x$ where $y_w$ and
$y_l$ denotes the preferred and dispreferred completion amongst $(y_1, y_2)$ respectively. The
preferences are assumed to be generated by some latent reward model $r^*(y, x)$, which we do not
have access to. There are a number of approaches used to model preferences, the Bradley-Terry (BT)
\cite{bradley1952rankanalysis} model being a popular choice (although more general Plackett-Luce
ranking models \citep{plackett1975analysis, luce2012individual} are also compatible with the
framework if we have access to several ranked answers). The BT model stipulates that the human
preference distribution $p^*$ can be written as: \begin{equation}\label{eq:bradley-terry}
p^*(y_1\succ y_2 \mid x)=\frac{\exp\left(r^*(x, y_1)\right)}{\exp\left(r^*(x, y_1)\right) +
\exp\left(r^*(x, y_2)\right)}. \end{equation} Assuming access to a static dataset of comparisons
$\mathcal{D}=\bigl\{x^{(i)}, y_w^{(i)}, y_l^{(i)}\bigr\}_{i=1}^N$ sampled from $p^*$, we can
parametrize a reward model $r_{\phi}(x, y)$ and estimate the parameters via maximum likelihood.
Framing the problem as a binary classification we have the negative log-likelihood loss:
\begin{equation}\label{eq:reward_model}     \mathcal{L}_R(r_{\phi}, \mathcal{D}) = -\mathbb{E}_{(x,
y_w, y_l)\sim \mathcal{D}}\bigl[\log \sigma(r_{\phi}(x, y_w)- r_{\phi}(x, y_l))\bigr] \end{equation}
where $\sigma$ is the logistic function. In the context of LMs, the network $r_{\phi}(x, y)$ is
often initialized from the SFT model $\pisft(y \mid x)$ with the addition of a linear layer on top
of the final transformer layer that produces a single scalar prediction for the reward value
\cite{ziegler2020finetuning}. To ensure a reward function with lower variance, prior works normalize
the rewards, such that  $\mathbb{E}_{x,y\sim \mathcal{D}}\left[r_\phi(x, y)\right] = 0$ for all $x$.

\textbf{RL Fine-Tuning Phase}: During the RL phase, the learned reward function is used to provide
feedback to the language model. Following prior works~\citep{jaques2017sequence, jaques2020human},
the optimization is formulated as \begin{equation}\label{eq:RL} \max_{\pi_{\theta}}
\mathbb{E}_{x\sim \mathcal{D}, y\sim \pi_{\theta}(y \mid x)}\bigl[r_{\phi}(x, y)\bigr] -
\beta\mathbb{D}_{\textrm{KL}}\bigl[\pi_{\theta}(y\mid x)\mid \mid \piref(y\mid x)\bigr],
\end{equation} where $\beta$ is a parameter controlling the deviation from the base reference policy
$\piref$, namely the initial SFT model $\pisft$.  In practice, the language model policy
$\pi_\theta$ is also initialized to $\pisft$. The added constraint is important, as it prevents the
model from deviating too far from the distribution on which the reward model is accurate, as well as
maintaining the generation diversity and preventing mode-collapse to single high-reward answers. Due
to the discrete nature of language generation, this objective is not differentiable and is typically
optimized with reinforcement learning. The standard approach \citep{ziegler2020finetuning,
stiennon2022learning, bai2022training, ouyang2022training} has been to construct the reward function
${r(x, y) = r_{\phi}(x, y) -\beta (\log \pi_{\theta}(y\mid x) - \log \piref(y\mid x))}$, and
maximize using PPO \cite{schulman2017proximal}.  </knowledge>

\section{Direct Preference Optimization}\label{sec:DPO}

<knowledge> Motivated by the challenges of applying reinforcement learning algorithms on large-scale
problems such as fine-tuning language models, our goal is to derive a simple approach for policy
optimization using preferences directly. Unlike prior RLHF methods, which learn a reward and then
optimize it via RL, our approach leverages a particular choice of reward model parameterization that
enables extraction of its optimal policy in closed form, without an RL training loop.  As we will
describe next in detail, our key insight is to leverage an analytical mapping from reward functions
to optimal policies, which enables us to transform a loss function over reward functions into a loss
function over policies. This change-of-variables approach avoids fitting an explicit, standalone
reward model, while still optimizing under existing models of human preferences, such as the
Bradley-Terry model. In essence, the policy network represents both the language model and the
(implicit) reward. </knowledge>

<knowledge> \textbf{Deriving the DPO objective.} We start with the same RL objective as prior work,
Eq.~\ref{eq:RL}, under a general reward function $r$. Following prior
work~\citep{peters2007reinforcement, peng2019advantage, korbak2022reinforcement, go2023aligning}, it
is straightforward to show that the optimal solution to the KL-constrained reward maximization
objective in Eq.~\ref{eq:RL} takes the form: \begin{equation}\label{eq:op_policy}     \pi_r(y\mid x)
= \frac{1}{Z(x)}\piref(y\mid x)\exp\left(\frac{1}{\beta}r(x, y)\right), \end{equation}% where $Z(x)
=\sum_{y}\piref(y\mid x)\exp\left(\frac{1}{\beta}r(x, y)\right)$ is the partition function. See
Appendix \ref{app:derivation1} for a complete derivation. Even if we use the MLE estimate $r_{\phi}$
of the ground-truth reward function $r^*$, it is still expensive to estimate the partition function
$Z(x)$ \citep{korbak2022reinforcement, go2023aligning}, which makes this representation hard to
utilize in practice. However, we can rearrange Eq.~\ref{eq:op_policy} to express the reward function
in terms of its corresponding optimal policy $\pi_r$, the reference policy $\piref$, and the unknown
partition function $Z(\cdot)$. Specifically, we first take the logarithm of both sides of
Eq.~\ref{eq:op_policy} and then with some algebra we obtain: \begin{equation}\label{eq:main_eq}
r(x,y) =\beta \log \frac{\pi_r(y\mid x)}{\piref(y\mid x)} + \beta \log Z(x). \end{equation} We can
apply this reparameterization to the ground-truth reward $r^*$ and corresponding optimal model
$\pi^*$. Fortunately, the Bradley-Terry model depends only on the difference of rewards between two
completions, i.e., ${p^*(y_1 \succ y_2 \mid x) = \sigma(r^*(x, y_1) - r^*(x, y_2))}$. Substituting
the reparameterization in Eq.~\ref{eq:main_eq} for $r^*(x,y)$ into the preference model
Eq.~\ref{eq:bradley-terry}, the partition function cancels, and we can express the human preference
probability in terms of only the optimal policy $\pi^*$ and reference policy $\piref$. Thus, the
optimal RLHF policy $\pi^*$ under the Bradley-Terry model satisfies the preference model:
\begin{equation}\label{eq:objective}     p^*(y_1\succ y_2 \mid x)=\frac{1}{1 + \exp\left(\beta \log
\frac{\pi^*(y_2\mid x)}{\piref(y_2\mid x)} - \beta \log \frac{\pi^*(y_1\mid x)}{\piref(y_1\mid
x)}\right)} \end{equation} The derivation is in Appendix~\ref{app:derivation2}. While
Eq.~\ref{eq:objective} uses the Bradley-Terry model, we can similarly derive expressions under the
more general Plackett-Luce models~\citep{plackett1975analysis, luce2012individual}, shown in
Appendix~\ref{app:plackett_luce_models}.

Now that we have the probability of human preference data in terms of the optimal policy rather than
the reward model, we can formulate a maximum likelihood objective for a parametrized policy
$\pi_\theta$. Analogous to the reward modeling approach (i.e. Eq.~\ref{eq:reward_model}), our policy
objective becomes: \begin{equation}\label{eq:optimum_model}     \mathcal{L}_\text{DPO}(\pi_{\theta};
\piref) = -\mathbb{E}_{(x, y_w, y_l)\sim \mathcal{D}}\left[\log \sigma \left(\beta \log
\frac{\pi_{\theta}(y_w\mid x)}{\piref(y_w\mid x)} - \beta \log \frac{\pi_{\theta}(y_l\mid
x)}{\piref(y_l\mid x)}\right)\right]. \end{equation} This way, we fit an implicit reward using an
alternative parameterization, whose optimal policy is simply $\pi_\theta$. Moreover, since our
procedure is equivalent to fitting a reparametrized Bradley-Terry model, it enjoys certain
theoretical properties, such as consistencies under suitable assumption of the preference data
distribution \cite{bong2022generalized}. In Section~\ref{sec:theory}, we further discuss theoretical
properties of DPO in relation to other works. </knowledge>

<knowledge> \textbf{What does the DPO update do?} For a mechanistic understanding of DPO, it is

In [21]:
extraction_prompt = """Your task is to act as a text segmenter. Carefully read the provided text from a paper and identify all "pieces of knowledge."

# Definition of a "Piece of Knowledge"
A piece of knowledge is an informative statement that is:
1.  Self-Contained: It must be fully understandable on its own without needing sentences before or after it. 
    - If it's referring to a term in a previous sentence (e.g., "the reward function"), they should be together as one unit of knowledge.
    - If the sentence is directly building on a previous sentence, either by a pronoun or a reference, they should be together as one unit of knowledge.
2.  Atomic and Coherent: It should be a single, complete thought.  
    - This can range from a single, dense sentence to a full paragraph that explains it.

# What to Exclude (Do NOT tag these):
Generally speaking, exclude sentences that mostly consist of common words and phrases that don't add much information:
- Paper Structure & Meta-Commentary: Sentences about the paper itself (e.g., "In this section, we describe...", "Figure 3 shows...", "Our contributions are threefold..."). 
- Transitional Sentences: Text that only serves to connect ideas without adding new information (e.g., "Furthermore...", "Now we turn to...", "In addition to the above...").
- Author Speculation or Rhetorical Questions: Subjective statements or questions posed to the reader (e.g., "This result is quite surprising.", "But what if the model could...?"). 
- Figures and Tables: Sentences that describe figures and tables.

# Instructions
1.  Read the entire text carefully.
2.  Identify all segments that fit the definition of a "piece of knowledge" and do not fall into the exclusion categories.
3.  Demarcate each piece of knowledge by wrapping it in `<knowledge>` and `</knowledge>` tags.
4.  While you should ensure the knowledge is self-contained and atomic as much as you can, do not just place tags around an entire paragraph. Encapsulate smaller, discrete units of knowledge. When appropriate, you can also have nested tags.
5.  Return the entire original text with these annotations. Do not modify or summarize the text itself.

# Example
This is an example in which nested tags are used because the first sentence is self-contained and atomic, but the follow-up sentence is not and thus it relies on the previous sentence.
<knowledge><knowledge>In this paper we introduce a new parameterization of the reward model in RLHF that enables extraction of the corresponding optimal policy in closed form, allowing us to solve the standard RLHF problem with only a simple classification loss.</knowledge> The resulting algorithm, which we call \textit{Direct Preference Optimization} (DPO), is stable, performant, and computationally lightweight, eliminating the need for sampling from the LM during fine-tuning or performing significant hyperparameter tuning.</knowledge>
"""
# - For instance, it's okay if you have to forgo some portions of a paragraph to break it up into smaller units.
# - Citations: Sentences that primarily exist to cite other work (e.g., "This was previously shown by Smith et al. (2023).").


# Split paper into paragraphs
paper_paragraphs = paper.split('\n\n')

extracted_claims = []
import concurrent.futures

def query_single(paragraph):
    prompt = {}
    prompt['system'] = extraction_prompt
    prompt['user'] = f"""Paper: {paragraph}"""
    return utils.query_llm(prompt, model='gpt-4.1', temperature=0, max_tokens=32768)

with concurrent.futures.ThreadPoolExecutor() as executor:
    futures = [executor.submit(query_single, paragraph) for paragraph in paper_paragraphs]
    extracted_claims = [future.result() for future in futures]

# Print each output
for i, output in enumerate(extracted_claims, 1):
    print_wrapped(f"Paragraph {i}: {output}")
    print_wrapped("-" * 50)

Paragraph 1: Paper: \title{Direct Preference Optimization: Your Language Model is Secretly a Reward
Model}

--------------------------------------------------

Paragraph 2: \begin{abstract} <knowledge>While large-scale unsupervised language models (LMs) learn
broad world knowledge and some reasoning skills, achieving precise control of their behavior is
difficult due to the completely unsupervised nature of their training.</knowledge>
<knowledge>Existing methods for gaining such steerability collect human labels of the relative
quality of model generations and fine-tune the unsupervised LM to align with these preferences,
often with reinforcement learning from human feedback (RLHF).</knowledge> <knowledge>However, RLHF
is a complex and often unstable procedure, first fitting a reward model that reflects the human
preferences, and then fine-tuning the large unsupervised LM using reinforcement learning to maximize
this estimated reward without drifting too far from the original model.</knowledge>
<knowledge><knowledge>In this paper we introduce a new parameterization of the reward model in RLHF
that enables extraction of the corresponding optimal policy in closed form, allowing us to solve the
standard RLHF problem with only a simple classification loss.</knowledge> The resulting algorithm,
which we call \textit{Direct Preference Optimization} (DPO), is stable, performant, and
computationally lightweight, eliminating the need for sampling from the LM during fine-tuning or
performing significant hyperparameter tuning.</knowledge> <knowledge>Our experiments show that DPO
can fine-tune LMs to align with human preferences as well as or better than existing
methods.</knowledge> <knowledge>Notably, fine-tuning with DPO exceeds PPO-based RLHF in ability to
control sentiment of generations, and matches or improves response quality in summarization and
single-turn dialogue while being substantially simpler to implement and train.</knowledge>
\end{abstract}

--------------------------------------------------

Paragraph 3: <knowledge>Large unsupervised language models (LMs) trained on very large datasets
acquire surprising capabilities~\citep{chowdhery2022palm, brown2020language,
touvron2023llama,bubeck2023sparks}.</knowledge> <knowledge>These models are trained on data
generated by humans with a wide variety of goals, priorities, and skillsets.</knowledge>
<knowledge>Some of these goals and skillsets may not be desirable to imitate; for example, while we
may want our AI coding assistant to \textit{understand} common programming mistakes in order to
correct them, nevertheless, when generating code, we would like to bias our model toward the
(potentially rare) high-quality coding ability present in its training data.</knowledge>
<knowledge>Similarly, we might want our language model to be \textit{aware} of a common
misconception believed by 50\% of people, but we certainly do not want the model to claim this
misconception to be true in 50\% of queries about it!</knowledge> <knowledge>In other words,
selecting the model's \emph{desired responses and behavior} from its very wide \textit{knowledge and
abilities} is crucial to building AI systems that are safe, performant, and controllable
\citep{ouyang2022training}.</knowledge> <knowledge>While existing methods typically steer LMs to
match human preferences using reinforcement learning (RL), we will show that the RL-based objective
used by existing methods can be optimized exactly with a simple binary cross-entropy objective,
greatly simplifying the preference learning pipeline.</knowledge>

--------------------------------------------------

Paragraph 4: Paper: \begin{figure}     \centering
\includegraphics[width=0.999\textwidth]{figures/diagrams/teaser.png}
\caption{\textbf{<knowledge>DPO optimizes for human preferences while avoiding reinforcement
learning.</knowledge> <knowledge>Existing methods for fine-tuning language models with human
feedback first fit a reward model to a dataset of prompts and human preferences over pairs of
responses, and then use RL to find a policy that maximizes the learned reward.</knowledge>
<knowledge>In contrast, DPO directly optimizes for the policy best satisfying the preferences with a
simple classification objective, fitting an \textit{implicit} reward model whose corresponding
optimal policy can be extracted in closed form.</knowledge>}     \vspace{-2mm}
\label{fig:teaser} \end{figure}

--------------------------------------------------

Paragraph 5: <knowledge>Existing methods instill the desired behaviors into a language model using
curated sets of human preferences representing the types of behaviors that humans find safe and
helpful.</knowledge> <knowledge>This preference learning stage occurs after an initial stage of
large-scale unsupervised pre-training on a large text dataset.</knowledge> <knowledge>While the most
straightforward approach to preference learning is supervised fine-tuning on human demonstrations of
high quality responses, the most successful class of methods is reinforcement learning from human
(or AI) feedback (RLHF/RLAIF; \citep{christiano2017deep,bai2022constitutional}).</knowledge>
<knowledge>RLHF methods fit a reward model to a dataset of human preferences and then use RL to
optimize a language model policy to produce responses assigned high reward without drifting
excessively far from the original model.</knowledge> <knowledge>While RLHF produces models with
impressive conversational and coding abilities, the RLHF pipeline is considerably more complex than
supervised learning, involving training multiple LMs and sampling from the LM policy in the loop of
training, incurring significant computational costs.</knowledge>

--------------------------------------------------

Paragraph 6: <knowledge>We show how to directly optimize a language model to adhere to human
preferences, without explicit reward modeling or reinforcement learning.</knowledge> <knowledge>We
propose Direct Preference Optimization (DPO), an algorithm that implicitly optimizes the same
objective as existing RLHF algorithms (reward maximization with a KL-divergence constraint) but is
simple to implement and straightforward to train.</knowledge> <knowledge>Intuitively, the DPO update
increases the relative log probability of preferred to dispreferred responses, but it incorporates a
dynamic, per-example importance weight that prevents the model degeneration that we find occurs with
a naive probability ratio objective.</knowledge> <knowledge>Like existing algorithms, DPO relies on
a theoretical preference model (such as the Bradley-Terry model; \cite{bradley1952rankanalysis})
that measures how well a given reward function aligns with empirical preference data.</knowledge>
<knowledge>While existing methods use the preference model to define a preference loss to train a
reward model and then train a policy that optimizes the learned reward model, DPO uses a change of
variables to define the preference loss as a function of the policy directly.</knowledge>
<knowledge>Given a dataset of human preferences over model responses, DPO can therefore optimize a
policy using a simple binary cross entropy objective, producing the optimal policy to an implicit
reward function fit to the preference data.</knowledge>

--------------------------------------------------

Paragraph 7: <knowledge>Direct Preference Optimization (DPO) is a simple RL-free algorithm for
training language models from preferences.</knowledge> <knowledge>Experiments show that DPO is at
least as effective as existing methods, including PPO-based RLHF, for learning from preferences in
tasks such as sentiment modulation, summarization, and dialogue, using language models with up to 6B
parameters.</knowledge>

--------------------------------------------------

Paragraph 8: Paper: \section{Related Work}

--------------------------------------------------

Paragraph 9: <knowledge>Self-supervised language models of increasing scale learn to complete some
tasks zero-shot \citep{radford2019language} or with few-shot prompts
\citep{gpt3,megatron,chowdhery2022palm}.</knowledge> <knowledge>However, their performance on
downstream tasks and alignment with user intent can be significantly improved by fine-tuning on
datasets of instructions and human-written completions \citep{mishra-
etal-2022-cross,sanh2022multitask,chung2022scaling,thoppilan2022lamda}.</knowledge> <knowledge>This
`instruction-tuning' procedure enables LLMs to generalize to instructions outside of the
instruction-tuning set and generally increase their usability \citep{chung2022scaling}.</knowledge>
<knowledge>Despite the success of instruction tuning, <knowledge>relative human judgments of
response quality are often easier to collect than expert demonstrations, and thus subsequent works
have fine-tuned LLMs with datasets of human preferences, improving proficiency in translation
\citep{kreutzer-etal-2018-reliability}, summarization
\citep{stiennon2022learning,ziegler2020finetuning}, story-telling \citep{ziegler2020finetuning}, and
instruction-following \citep{ouyang2022training,ramamurthy2023is}.</knowledge></knowledge>
<knowledge>These methods first optimize a neural network reward function for compatibility with the
dataset of preferences under a preference model such as the Bradley-Terry model
\citep{bradley1952rankanalysis}, then fine-tune a language model to maximize the given reward using
reinforcement learning algorithms, commonly REINFORCE \citep{williams1992reinforce}, proximal policy
optimization (PPO; \cite{schulman2017proximal}), or variants \citep{ramamurthy2023is}.</knowledge>
<knowledge>A closely-related line of work leverages LLMs fine-tuned for instruction following with
human feedback to generate additional synthetic preference data for targeted attributes such as
safety or harmlessness \citep{bai2022constitutional}, using only weak supervision from humans in the
form of a text rubric for the LLM's annotations.</knowledge> <knowledge>These methods represent a
convergence of two bodies of work: one body of work on training language models with reinforcement
learning for a variety of objectives~\citep{Ranzato2015SequenceLT,paulus2018a,wu2018learning} and
another body of work on general methods for learning from human preferences
\citep{christiano2017deep,kupcsik2018learning}.</knowledge> <knowledge>Despite the appeal of using
relative human preferences, fine-tuning large language models with reinforcement learning remains a
major practical challenge; this work provides a theoretically-justified approach to optimizing
relative preferences without RL.</knowledge>

--------------------------------------------------

Paragraph 10: <knowledge>Outside of the context of language, learning policies from preferences has
been studied in both bandit and reinforcement learning settings, and several approaches have been
proposed.</knowledge> <knowledge>Contextual bandit learning using preferences or rankings of
actions, rather than rewards, is known as a contextual dueling bandit (CDB;
\cite{yue2012karmed,dudik2015contextual}).</knowledge> <knowledge>In the absence of absolute
rewards, theoretical analysis of CDBs substitutes the notion of an optimal policy with a \textit{von
Neumann winner}, a policy whose expected win rate against \textit{any} other policy is at least 50\%
\citep{dudik2015contextual}.</knowledge> <knowledge>In the CDB setting, preference labels are given
online, while in learning from human preferences, we typically learn from a fixed batch of offline
preference-annotated action pairs \citep{yan2022human}.</knowledge> <knowledge>Similarly,
\textit{preference-based RL} (PbRL) learns from binary preferences generated by an \textit{unknown}
`scoring' function rather than rewards \citep{BusaFekete2014,ruiz2023dueling}.</knowledge>
<knowledge>Various algorithms for PbRL exist, including methods that can reuse off-policy preference
data, but generally involve first explicitly estimating the latent scoring function (i.e. the reward
model) and subsequently optimizing it \citep{jain2013learning,BusaFekete2014,christiano2017deep,sadi
gh2017active,kupcsik2018learning}.</knowledge> <knowledge>We instead present a single stage policy
learning approach that directly optimizes a policy to satisfy preferences.</knowledge>

--------------------------------------------------

Paragraph 11: Paper: \section{Preliminaries}\label{section:prelims}

--------------------------------------------------

Paragraph 12: <knowledge>It usually includes three phases: 1) supervised fine-tuning (SFT); 2)
preference sampling and reward learning and 3) RL optimization.</knowledge>

--------------------------------------------------

Paragraph 13: <knowledge>RLHF typically begins by fine-tuning a pre-trained LM with supervised
learning on high-quality data for the downstream task(s) of interest (dialogue, summarization,
etc.), to obtain a model $\pisft$.</knowledge>

--------------------------------------------------

Paragraph 14: Paper: \textbf{Reward Modelling Phase}: <knowledge>In the second phase the SFT model
is prompted with prompts $x$ to produce pairs of answers $(y_1, y_2)\sim \pisft(y \mid
x)$.</knowledge> <knowledge>These are then presented to human labelers who express preferences for
one answer, denoted as $y_w\succ y_l \mid x$ where $y_w$ and $y_l$ denotes the preferred and
dispreferred completion amongst $(y_1, y_2)$ respectively.</knowledge> <knowledge>The preferences
are assumed to be generated by some latent reward model $r^*(y, x)$, which we do not have access
to.</knowledge> <knowledge>There are a number of approaches used to model preferences, the Bradley-
Terry (BT) \cite{bradley1952rankanalysis} model being a popular choice (although more general
Plackett-Luce ranking models \citep{plackett1975analysis, luce2012individual} are also compatible
with the framework if we have access to several ranked answers).</knowledge> <knowledge>The BT model
stipulates that the human preference distribution $p^*$ can be written as:
\begin{equation}\label{eq:bradley-terry}     p^*(y_1\succ y_2 \mid x)=\frac{\exp\left(r^*(x,
y_1)\right)}{\exp\left(r^*(x, y_1)\right) + \exp\left(r^*(x, y_2)\right)}. \end{equation}
</knowledge> <knowledge>Assuming access to a static dataset of comparisons
$\mathcal{D}=\bigl\{x^{(i)}, y_w^{(i)}, y_l^{(i)}\bigr\}_{i=1}^N$ sampled from $p^*$, we can
parametrize a reward model $r_{\phi}(x, y)$ and estimate the parameters via maximum
likelihood.</knowledge> <knowledge>Framing the problem as a binary classification we have the
negative log-likelihood loss: \begin{equation}\label{eq:reward_model}     \mathcal{L}_R(r_{\phi},
\mathcal{D}) = -\mathbb{E}_{(x, y_w, y_l)\sim \mathcal{D}}\bigl[\log \sigma(r_{\phi}(x, y_w)-
r_{\phi}(x, y_l))\bigr] \end{equation} where $\sigma$ is the logistic function.</knowledge>
<knowledge>In the context of LMs, the network $r_{\phi}(x, y)$ is often initialized from the SFT
model $\pisft(y \mid x)$ with the addition of a linear layer on top of the final transformer layer
that produces a single scalar prediction for the reward value
\cite{ziegler2020finetuning}.</knowledge> <knowledge>To ensure a reward function with lower
variance, prior works normalize the rewards, such that  $\mathbb{E}_{x,y\sim
\mathcal{D}}\left[r_\phi(x, y)\right] = 0$ for all $x$.</knowledge>

--------------------------------------------------

Paragraph 15: \textbf{RL Fine-Tuning Phase}: <knowledge>During the RL phase, the learned reward
function is used to provide feedback to the language model.</knowledge> <knowledge>Following prior
works~\citep{jaques2017sequence, jaques2020human}, the optimization is formulated as
\begin{equation}\label{eq:RL} \max_{\pi_{\theta}}  \mathbb{E}_{x\sim \mathcal{D}, y\sim
\pi_{\theta}(y \mid x)}\bigl[r_{\phi}(x, y)\bigr] -
\beta\mathbb{D}_{\textrm{KL}}\bigl[\pi_{\theta}(y\mid x)\mid \mid \piref(y\mid x)\bigr],
\end{equation} where $\beta$ is a parameter controlling the deviation from the base reference policy
$\piref$, namely the initial SFT model $\pisft$.</knowledge>  <knowledge>In practice, the language
model policy $\pi_\theta$ is also initialized to $\pisft$.</knowledge> <knowledge>The added
constraint is important, as it prevents the model from deviating too far from the distribution on
which the reward model is accurate, as well as maintaining the generation diversity and preventing
mode-collapse to single high-reward answers.</knowledge> <knowledge>Due to the discrete nature of
language generation, this objective is not differentiable and is typically optimized with
reinforcement learning.</knowledge> <knowledge>The standard approach \citep{ziegler2020finetuning,
stiennon2022learning, bai2022training, ouyang2022training} has been to construct the reward function
${r(x, y) = r_{\phi}(x, y) -\beta (\log \pi_{\theta}(y\mid x) - \log \piref(y\mid x))}$, and
maximize using PPO \cite{schulman2017proximal}.</knowledge>

--------------------------------------------------

Paragraph 16: Paper: \section{Direct Preference Optimization}\label{sec:DPO}

--------------------------------------------------

Paragraph 17: <knowledge>Motivated by the challenges of applying reinforcement learning algorithms
on large-scale problems such as fine-tuning language models, our goal is to derive a simple approach
for policy optimization using preferences directly.</knowledge> <knowledge>Unlike prior RLHF
methods, which learn a reward and then optimize it via RL, our approach leverages a particular
choice of reward model parameterization that enables extraction of its optimal policy in closed
form, without an RL training loop.</knowledge> <knowledge>Our key insight is to leverage an
analytical mapping from reward functions to optimal policies, which enables us to transform a loss
function over reward functions into a loss function over policies.</knowledge> <knowledge>This
change-of-variables approach avoids fitting an explicit, standalone reward model, while still
optimizing under existing models of human preferences, such as the Bradley-Terry model.</knowledge>
<knowledge>In essence, the policy network represents both the language model and the (implicit)
reward.</knowledge>

--------------------------------------------------

Paragraph 18: Paper: \textbf{Deriving the DPO objective.} <knowledge>We start with the same RL
objective as prior work, Eq.~\ref{eq:RL}, under a general reward function $r$.</knowledge>
<knowledge>Following prior work~\citep{peters2007reinforcement, peng2019advantage,
korbak2022reinforcement, go2023aligning}, it is straightforward to show that the optimal solution to
the KL-constrained reward maximization objective in Eq.~\ref{eq:RL} takes the form:
\begin{equation}\label{eq:op_policy}     \pi_r(y\mid x) = \frac{1}{Z(x)}\piref(y\mid
x)\exp\left(\frac{1}{\beta}r(x, y)\right), \end{equation}% where $Z(x) =\sum_{y}\piref(y\mid
x)\exp\left(\frac{1}{\beta}r(x, y)\right)$ is the partition function.</knowledge> <knowledge>Even if
we use the MLE estimate $r_{\phi}$ of the ground-truth reward function $r^*$, it is still expensive
to estimate the partition function $Z(x)$ \citep{korbak2022reinforcement, go2023aligning}, which
makes this representation hard to utilize in practice.</knowledge> <knowledge>However, we can
rearrange Eq.~\ref{eq:op_policy} to express the reward function in terms of its corresponding
optimal policy $\pi_r$, the reference policy $\piref$, and the unknown partition function
$Z(\cdot)$.</knowledge> <knowledge>Specifically, we first take the logarithm of both sides of
Eq.~\ref{eq:op_policy} and then with some algebra we obtain: \begin{equation}\label{eq:main_eq}
r(x,y) =\beta \log \frac{\pi_r(y\mid x)}{\piref(y\mid x)} + \beta \log Z(x).
\end{equation}</knowledge> <knowledge>We can apply this reparameterization to the ground-truth
reward $r^*$ and corresponding optimal model $\pi^*$.</knowledge> <knowledge>Fortunately, the

In [25]:
extraction_prompt = """Your task is to act as a text segmenter. Carefully read the provided text from a paper and identify all "pieces of knowledge."

# Definition of a "Piece of Knowledge"
A piece of knowledge is statement that:
1. Provides information.
2. Self-Contained
    - It must be fully understandable on its own without needing sentences before or after it. 
    - If it's referring to a term in a previous sentence (e.g., "the reward function"), they should be together as one unit of knowledge.
    - If the sentence is directly building on a previous sentence, either by a pronoun or a reference, they should be together as one unit of knowledge.
2. Atomic and Coherent
    - It should be a single, complete thought.  
    - This can range from a single, dense phrase to a few sentences that are woven together.

# What to Exclude (Do NOT tag these):
Generally speaking, exclude sentences that mostly consist of common words and phrases that don't add much information:
- Paper Structure & Meta-Commentary: Sentences about the paper itself (e.g., "In this section, we describe...", "Figure 3 shows...", "Our contributions are threefold..."). 
- Transitional Sentences: Text that only serves to connect ideas without adding new information (e.g., "Furthermore...", "Now we turn to...", "In addition to the above...").
- Author Speculation or Rhetorical Questions: Subjective statements or questions posed to the reader (e.g., "This result is quite surprising.", "But what if the model could...?"). 
- Figures and Tables: Sentences that describe figures and tables.

# Instructions
1.  Read the entire text carefully.
2.  Identify all segments that fit the definition of a "piece of knowledge" and do not fall into the exclusion categories.
3.  Demarcate each piece of knowledge by wrapping it in `<knowledge>` and `</knowledge>` tags.
4.  While you should ensure the knowledge is self-contained and atomic as much as you can, do not just place tags around an entire paragraph. Encapsulate smaller, discrete units of knowledge.
5.  Only return the entire original text with these annotations. Do not modify or summarize the text itself.
"""
# - For instance, it's okay if you have to forgo some portions of a paragraph to break it up into smaller units.
# - Citations: Sentences that primarily exist to cite other work (e.g., "This was previously shown by Smith et al. (2023).").


# Split paper into paragraphs
paper_paragraphs = paper.split('\n\n')

extracted_claims = []
import concurrent.futures

def query_single(paragraph):
    prompt = {}
    prompt['system'] = extraction_prompt
    prompt['user'] = f"""{paragraph}"""
    return utils.query_llm(prompt, model='gpt-4.1', temperature=0, max_tokens=32768)

with concurrent.futures.ThreadPoolExecutor() as executor:
    futures = [executor.submit(query_single, paragraph) for paragraph in paper_paragraphs]
    extracted_claims = [future.result() for future in futures]

# Print each output
for i, output in enumerate(extracted_claims, 1):
    print_wrapped(f"Paragraph {i}: {output}")
    print_wrapped("-" * 50)

Paragraph 1: \title{Direct Preference Optimization: Your Language Model is Secretly a Reward Model}

--------------------------------------------------

Paragraph 2: \begin{abstract} <knowledge>Large-scale unsupervised language models (LMs) learn broad
world knowledge and some reasoning skills.</knowledge> <knowledge>Achieving precise control of the
behavior of large-scale unsupervised LMs is difficult due to the completely unsupervised nature of
their training.</knowledge> <knowledge>Existing methods for gaining steerability in LMs collect
human labels of the relative quality of model generations and fine-tune the unsupervised LM to align
with these preferences, often using reinforcement learning from human feedback (RLHF).</knowledge>
<knowledge>RLHF is a complex and often unstable procedure, which first fits a reward model that
reflects human preferences, and then fine-tunes the large unsupervised LM using reinforcement
learning to maximize this estimated reward without drifting too far from the original
model.</knowledge> <knowledge>A new parameterization of the reward model in RLHF enables extraction
of the corresponding optimal policy in closed form, allowing the standard RLHF problem to be solved
with only a simple classification loss.</knowledge> <knowledge>The resulting algorithm, called
\textit{Direct Preference Optimization} (DPO), is stable, performant, and computationally
lightweight, eliminating the need for sampling from the LM during fine-tuning or performing
significant hyperparameter tuning.</knowledge> <knowledge>DPO can fine-tune LMs to align with human
preferences as well as or better than existing methods.</knowledge> <knowledge>Fine-tuning with DPO
exceeds PPO-based RLHF in ability to control sentiment of generations, and matches or improves
response quality in summarization and single-turn dialogue while being substantially simpler to
implement and train.</knowledge> \end{abstract}

--------------------------------------------------

Paragraph 3: \section{Introduction} <knowledge>Large unsupervised language models (LMs) trained on
very large datasets acquire surprising capabilities~\citep{chowdhery2022palm, brown2020language,
touvron2023llama,bubeck2023sparks}.</knowledge> <knowledge>These models are trained on data
generated by humans with a wide variety of goals, priorities, and skillsets.</knowledge>
<knowledge>Some of these goals and skillsets may not be desirable to imitate; for example, while we
may want our AI coding assistant to \textit{understand} common programming mistakes in order to
correct them, nevertheless, when generating code, we would like to bias our model toward the
(potentially rare) high-quality coding ability present in its training data.</knowledge>
<knowledge>We might want our language model to be \textit{aware} of a common misconception believed
by 50\% of people, but we certainly do not want the model to claim this misconception to be true in
50\% of queries about it.</knowledge> <knowledge>Selecting the model's \emph{desired responses and
behavior} from its very wide \textit{knowledge and abilities} is crucial to building AI systems that
are safe, performant, and controllable \citep{ouyang2022training}.</knowledge> <knowledge>Existing
methods typically steer LMs to match human preferences using reinforcement learning
(RL).</knowledge> <knowledge>The RL-based objective used by existing methods can be optimized
exactly with a simple binary cross-entropy objective, greatly simplifying the preference learning
pipeline.</knowledge>

--------------------------------------------------

Paragraph 4: \begin{figure}     \centering
\includegraphics[width=0.999\textwidth]{figures/diagrams/teaser.png}     \caption{\textbf{DPO
optimizes for human preferences while avoiding reinforcement learning.} <knowledge>Existing methods
for fine-tuning language models with human feedback first fit a reward model to a dataset of prompts
and human preferences over pairs of responses, and then use RL to find a policy that maximizes the
learned reward.</knowledge> <knowledge>In contrast, DPO directly optimizes for the policy best
satisfying the preferences with a simple classification objective, fitting an \textit{implicit}
reward model whose corresponding optimal policy can be extracted in closed form.</knowledge>}
\vspace{-2mm}     \label{fig:teaser} \end{figure}

--------------------------------------------------

Paragraph 5: <knowledge>Existing methods instill the desired behaviors into a language model using
curated sets of human preferences representing the types of behaviors that humans find safe and
helpful.</knowledge> <knowledge>This preference learning stage occurs after an initial stage of
large-scale unsupervised pre-training on a large text dataset.</knowledge> <knowledge>The most
straightforward approach to preference learning is supervised fine-tuning on human demonstrations of
high quality responses.</knowledge> <knowledge>The most successful class of methods is reinforcement
learning from human (or AI) feedback (RLHF/RLAIF;
\citep{christiano2017deep,bai2022constitutional}).</knowledge> <knowledge>RLHF methods fit a reward
model to a dataset of human preferences and then use RL to optimize a language model policy to
produce responses assigned high reward without drifting excessively far from the original
model.</knowledge> <knowledge>RLHF produces models with impressive conversational and coding
abilities.</knowledge> <knowledge>The RLHF pipeline is considerably more complex than supervised
learning, involving training multiple LMs and sampling from the LM policy in the loop of training,
incurring significant computational costs.</knowledge>

--------------------------------------------------

Paragraph 6: <knowledge>We show how to directly optimize a language model to adhere to human
preferences, without explicit reward modeling or reinforcement learning.</knowledge> <knowledge>We
propose Direct Preference Optimization (DPO), an algorithm that implicitly optimizes the same
objective as existing RLHF algorithms (reward maximization with a KL-divergence constraint) but is
simple to implement and straightforward to train.</knowledge> <knowledge>Intuitively, the DPO update
increases the relative log probability of preferred to dispreferred responses, but it incorporates a
dynamic, per-example importance weight that prevents the model degeneration that we find occurs with
a naive probability ratio objective.</knowledge> <knowledge>Like existing algorithms, DPO relies on
a theoretical preference model (such as the Bradley-Terry model; \cite{bradley1952rankanalysis})
that measures how well a given reward function aligns with empirical preference data.</knowledge>
<knowledge>While existing methods use the preference model to define a preference loss to train a
reward model and then train a policy that optimizes the learned reward model, DPO uses a change of
variables to define the preference loss as a function of the policy directly.</knowledge>
<knowledge>Given a dataset of human preferences over model responses, DPO can therefore optimize a
policy using a simple binary cross entropy objective, producing the optimal policy to an implicit
reward function fit to the preference data.</knowledge>

--------------------------------------------------

Paragraph 7: <knowledge>Direct Preference Optimization (DPO) is a simple RL-free algorithm for
training language models from preferences.</knowledge> <knowledge>DPO is at least as effective as
existing methods, including PPO-based RLHF, for learning from preferences in tasks such as sentiment
modulation, summarization, and dialogue, using language models with up to 6B parameters.</knowledge>

--------------------------------------------------

Paragraph 8: \section{Related Work}

--------------------------------------------------

Paragraph 9: <knowledge>Self-supervised language models of increasing scale learn to complete some
tasks zero-shot or with few-shot prompts.</knowledge> <knowledge>Their performance on downstream
tasks and alignment with user intent can be significantly improved by fine-tuning on datasets of
instructions and human-written completions.</knowledge> <knowledge>This 'instruction-tuning'
procedure enables LLMs to generalize to instructions outside of the instruction-tuning set and
generally increase their usability.</knowledge> <knowledge>Relative human judgments of response
quality are often easier to collect than expert demonstrations, and thus subsequent works have fine-
tuned LLMs with datasets of human preferences, improving proficiency in translation, summarization,
story-telling, and instruction-following.</knowledge> <knowledge>These methods first optimize a
neural network reward function for compatibility with the dataset of preferences under a preference
model such as the Bradley-Terry model, then fine-tune a language model to maximize the given reward
using reinforcement learning algorithms, commonly REINFORCE, proximal policy optimization (PPO), or
variants.</knowledge> <knowledge>A closely-related line of work leverages LLMs fine-tuned for
instruction following with human feedback to generate additional synthetic preference data for
targeted attributes such as safety or harmlessness, using only weak supervision from humans in the
form of a text rubric for the LLM's annotations.</knowledge> <knowledge>These methods represent a
convergence of two bodies of work: one body of work on training language models with reinforcement
learning for a variety of objectives and another body of work on general methods for learning from
human preferences.</knowledge> <knowledge>Despite the appeal of using relative human preferences,
fine-tuning large language models with reinforcement learning remains a major practical challenge;
this work provides a theoretically-justified approach to optimizing relative preferences without
RL.</knowledge>

--------------------------------------------------

Paragraph 10: <knowledge>Outside of the context of language, learning policies from preferences has
been studied in both bandit and reinforcement learning settings, and several approaches have been
proposed.</knowledge> <knowledge>Contextual bandit learning using preferences or rankings of
actions, rather than rewards, is known as a contextual dueling bandit (CDB;
\cite{yue2012karmed,dudik2015contextual}).</knowledge> <knowledge>In the absence of absolute
rewards, theoretical analysis of CDBs substitutes the notion of an optimal policy with a \textit{von
Neumann winner}, a policy whose expected win rate against \textit{any} other policy is at least 50\%
\citep{dudik2015contextual}.</knowledge> <knowledge>In the CDB setting, preference labels are given
online, while in learning from human preferences, we typically learn from a fixed batch of offline
preference-annotated action pairs \citep{yan2022human}.</knowledge> <knowledge>\textit{Preference-
based RL} (PbRL) learns from binary preferences generated by an \textit{unknown} `scoring' function
rather than rewards \citep{BusaFekete2014,ruiz2023dueling}.</knowledge> <knowledge>Various
algorithms for PbRL exist, including methods that can reuse off-policy preference data, but
generally involve first explicitly estimating the latent scoring function (i.e. the reward model)
and subsequently optimizing it \citep{jain2013learning,BusaFekete2014,christiano2017deep,sadigh2017a
ctive,kupcsik2018learning}.</knowledge> <knowledge>We instead present a single stage policy learning
approach that directly optimizes a policy to satisfy preferences.</knowledge>

--------------------------------------------------

Paragraph 11: \section{Preliminaries}\label{section:prelims}

--------------------------------------------------

Paragraph 12: We review the RLHF pipeline in \citeauthor{ziegler2020finetuning} (and later
\citep{stiennon2022learning, bai2022training, ouyang2022training}). <knowledge>It usually includes
three phases: 1) supervised fine-tuning (SFT); 2) preference sampling and reward learning and 3) RL
optimization.</knowledge>

--------------------------------------------------

Paragraph 13: <knowledge>RLHF typically begins by fine-tuning a pre-trained LM with supervised
learning on high-quality data for the downstream task(s) of interest (dialogue, summarization,
etc.), to obtain a model $\pisft$.</knowledge>

--------------------------------------------------

Paragraph 14: <knowledge>In the second phase the SFT model is prompted with prompts $x$ to produce
pairs of answers $(y_1, y_2)\sim \pisft(y \mid x)$.</knowledge> <knowledge>These are then presented
to human labelers who express preferences for one answer, denoted as $y_w\succ y_l \mid x$ where
$y_w$ and $y_l$ denotes the preferred and dispreferred completion amongst $(y_1, y_2)$
respectively.</knowledge> <knowledge>The preferences are assumed to be generated by some latent
reward model $r^*(y, x)$, which we do not have access to.</knowledge> <knowledge>There are a number
of approaches used to model preferences, the Bradley-Terry (BT) \cite{bradley1952rankanalysis} model
being a popular choice (although more general Plackett-Luce ranking models
\citep{plackett1975analysis, luce2012individual} are also compatible with the framework if we have
access to several ranked answers).</knowledge> <knowledge>The BT model stipulates that the human
preference distribution $p^*$ can be written as: \begin{equation}\label{eq:bradley-terry}
p^*(y_1\succ y_2 \mid x)=\frac{\exp\left(r^*(x, y_1)\right)}{\exp\left(r^*(x, y_1)\right) +
\exp\left(r^*(x, y_2)\right)}. \end{equation}</knowledge> <knowledge>Assuming access to a static
dataset of comparisons $\mathcal{D}=\bigl\{x^{(i)}, y_w^{(i)}, y_l^{(i)}\bigr\}_{i=1}^N$ sampled
from $p^*$, we can parametrize a reward model $r_{\phi}(x, y)$ and estimate the parameters via
maximum likelihood.</knowledge> <knowledge>Framing the problem as a binary classification we have
the negative log-likelihood loss: \begin{equation}\label{eq:reward_model}
\mathcal{L}_R(r_{\phi}, \mathcal{D}) = -\mathbb{E}_{(x, y_w, y_l)\sim \mathcal{D}}\bigl[\log
\sigma(r_{\phi}(x, y_w)- r_{\phi}(x, y_l))\bigr] \end{equation} where $\sigma$ is the logistic
function.</knowledge> <knowledge>In the context of LMs, the network $r_{\phi}(x, y)$ is often
initialized from the SFT model $\pisft(y \mid x)$ with the addition of a linear layer on top of the
final transformer layer that produces a single scalar prediction for the reward value
\cite{ziegler2020finetuning}.</knowledge> <knowledge>To ensure a reward function with lower
variance, prior works normalize the rewards, such that  $\mathbb{E}_{x,y\sim
\mathcal{D}}\left[r_\phi(x, y)\right] = 0$ for all $x$.</knowledge>

--------------------------------------------------

Paragraph 15: <knowledge>During the RL phase, the learned reward function is used to provide
feedback to the language model.</knowledge> <knowledge>The optimization during the RL phase is
formulated as maximizing the expected reward under the policy $\pi_\theta$ while penalizing the KL
divergence from a base reference policy $\piref$, as shown in the equation:  \[ \max_{\pi_{\theta}}
\mathbb{E}_{x\sim \mathcal{D}, y\sim \pi_{\theta}(y \mid x)}\bigl[r_{\phi}(x, y)\bigr] -
\beta\mathbb{D}_{\textrm{KL}}\bigl[\pi_{\theta}(y\mid x)\mid \mid \piref(y\mid x)\bigr], \] where
$\beta$ controls the deviation from the reference policy.</knowledge> <knowledge>The base reference
policy $\piref$ is the initial SFT model $\pisft$, and in practice, the language model policy
$\pi_\theta$ is also initialized to $\pisft$.</knowledge> <knowledge>The added KL constraint is
important because it prevents the model from deviating too far from the distribution on which the
reward model is accurate, maintains generation diversity, and prevents mode-collapse to single high-
reward answers.</knowledge> <knowledge>Due to the discrete nature of language generation, the RL
objective is not differentiable and is typically optimized with reinforcement learning.</knowledge>
<knowledge>The standard approach has been to construct the reward function as ${r(x, y) =
r_{\phi}(x, y) -\beta (\log \pi_{\theta}(y\mid x) - \log \piref(y\mid x))}$, and maximize it using
PPO.</knowledge>

--------------------------------------------------

Paragraph 16: \section{Direct Preference Optimization}\label{sec:DPO}

--------------------------------------------------

Paragraph 17: <knowledge>Our goal is to derive a simple approach for policy optimization using
preferences directly, motivated by the challenges of applying reinforcement learning algorithms on
large-scale problems such as fine-tuning language models.</knowledge> <knowledge>Unlike prior RLHF
methods, which learn a reward and then optimize it via RL, our approach leverages a particular
choice of reward model parameterization that enables extraction of its optimal policy in closed
form, without an RL training loop.</knowledge> <knowledge>Our key insight is to leverage an
analytical mapping from reward functions to optimal policies, which enables us to transform a loss
function over reward functions into a loss function over policies.</knowledge> <knowledge>This
change-of-variables approach avoids fitting an explicit, standalone reward model, while still
optimizing under existing models of human preferences, such as the Bradley-Terry model.</knowledge>
<knowledge>The policy network represents both the language model and the (implicit)
reward.</knowledge>

--------------------------------------------------

Paragraph 18: \textbf{Deriving the DPO objective.} We start with the same RL objective as prior
work, Eq.~\ref{eq:RL}, under a general reward function $r$. Following prior
work~\citep{peters2007reinforcement, peng2019advantage, korbak2022reinforcement, go2023aligning},
<knowledge>it is straightforward to show that the optimal solution to the KL-constrained reward
maximization objective in Eq.~\ref{eq:RL} takes the form: \begin{equation}\label{eq:op_policy}
\pi_r(y\mid x) = \frac{1}{Z(x)}\piref(y\mid x)\exp\left(\frac{1}{\beta}r(x, y)\right),
\end{equation}% where $Z(x) =\sum_{y}\piref(y\mid x)\exp\left(\frac{1}{\beta}r(x, y)\right)$ is the
partition function.</knowledge> See Appendix \ref{app:derivation1} for a complete derivation.
<knowledge>Even if we use the MLE estimate $r_{\phi}$ of the ground-truth reward function $r^*$, it
is still expensive to estimate the partition function $Z(x)$ \citep{korbak2022reinforcement,
go2023aligning}, which makes this representation hard to utilize in practice.</knowledge>
<knowledge>However, we can rearrange Eq.~\ref{eq:op_policy} to express the reward function in terms
of its corresponding optimal policy $\pi_r$, the reference policy $\piref$, and the unknown
partition function $Z(\cdot)$.</knowledge> <knowledge>Specifically, we first take the logarithm of
both sides of Eq.~\ref{eq:op_policy} and then with some algebra we obtain:
\begin{equation}\label{eq:main_eq}     r(x,y) =\beta \log \frac{\pi_r(y\mid x)}{\piref(y\mid x)} +
\beta \log Z(x). \end{equation}</knowledge> <knowledge>We can apply this reparameterization to the
ground-truth reward $r^*$ and corresponding optimal model $\pi^*$.</knowledge>
<knowledge>Fortunately, the Bradley-Terry model depends only on the difference of rewards between
two completions, i.e., ${p^*(y_1 \succ y_2 \mid x) = \sigma(r^*(x, y_1) - r^*(x,
y_2))}$.</knowledge> <knowledge>Substituting the reparameterization in Eq.~\ref{eq:main_eq} for
$r^*(x,y)$ into the preference model Eq.~\ref{eq:bradley-terry}, the partition function cancels, and
we can express the human preference probability in terms of only the optimal policy $\pi^*$ and
reference policy $\piref$.</knowledge> <knowledge>Thus, the optimal RLHF policy $\pi^*$ under the
Bradley-Terry model satisfies the preference model: \begin{equation}\label{eq:objective}
p^*(y_1\succ y_2 \mid x)=\frac{1}{1 + \exp\left(\beta \log \frac{\pi^*(y_2\mid x)}{\piref(y_2\mid

### Extracting Knowledge

In [63]:
extraction_prompt = r"""Your task is to act as a text segmenter. Carefully read the provided text from a paper and identify all "pieces of knowledge."

# Definition of a "Piece of Knowledge"
A piece of knowledge is a sentence that provides information. 

# What to Exclude (Do NOT tag these):
- Sentences that can be found in any paper: Sentences that ONLY contain language that's ubiquitous to any paper, adding zero information e.g. "Our results raise several important questions for future work."

# Instructions
1.  Read the entire text carefully.
2.  Identify all sentences that fit the definition of a "piece of knowledge" and do not fall into the exclusion categories.
3.  Please make sure that each table and each figure are tagged as one whole unit. Do not break up the figure or table into smaller units.
4.  For sentences that contain latex, place the tags so that it includes any latex code that's part of the sentence e.g. "\begin{definition}".
5.  Demarcate each piece of knowledge by wrapping it in `<knowledge>` and `</knowledge>` tags.
6.  Please make sure the tags are at the beginning and end of the sentence.
7.  Don't be conservative and include sentences even if it adds little information.
8.  Return the entire original text with these annotations. Do not modify or summarize the text itself.
"""

import re
import pandas as pd

def parse_paper_structure(text):
    """Parse paper into sections, subsections and paragraphs with metadata."""
    sections = []
    
    # Split by sections first
    section_pattern = r'\\section\{([^}]+)\}'
    section_splits = re.split(section_pattern, text)
    
    current_section = "No Section"
    current_section_content = ""
    
    for i in range(len(section_splits)):
        if i == 0:
            # Content before first section
            content = section_splits[i]
            current_section_content = content
        elif i % 2 == 1:
            # This is a section title
            current_section = section_splits[i]
            continue
        else:
            # This is section content
            content = section_splits[i]
            current_section_content = content
        
        # Now split by subsections within this section
        subsection_pattern = r'\\subsection\{([^}]+)\}'
        subsection_splits = re.split(subsection_pattern, content)
        
        current_subsection = "No Subsection"
        current_subsection_content = ""
        
        for j in range(len(subsection_splits)):
            if j == 0:
                # Content before first subsection
                subsection_content = subsection_splits[j]
                current_subsection_content = subsection_content
            elif j % 2 == 1:
                # This is a subsection title
                current_subsection = subsection_splits[j]
                continue
            else:
                # This is subsection content
                subsection_content = subsection_splits[j]
                current_subsection_content = subsection_content
            
            # Split into paragraphs
            paragraphs = [p.strip() for p in subsection_content.split('\n\n') if p.strip()]
            
            for paragraph in paragraphs:
                sections.append({
                    'section': current_section,
                    'subsection': current_subsection,
                    'paragraph': paragraph,
                    'section_text': current_section_content,
                    'subsection_text': current_subsection_content
                })
    
    return pd.DataFrame(sections)

# Parse paper structure
paper_df = parse_paper_structure(paper)

# Process each paragraph with LLM
import concurrent.futures

def query_single(paragraph):
    prompt = {}
    prompt['system'] = extraction_prompt
    prompt['user'] = f"""{paragraph}"""
    return utils.query_llm(prompt, model='gpt-4.1', temperature=0, max_tokens=32768)

with concurrent.futures.ThreadPoolExecutor() as executor:
    futures = [executor.submit(query_single, row['paragraph']) for _, row in paper_df.iterrows()]
    extracted_claims = [future.result() for future in futures]

# Add extracted claims to dataframe
paper_df['extracted_claims'] = extracted_claims

# Print each output with section/subsection context
for i, (_, row) in enumerate(paper_df.iterrows(), 1):
    print_wrapped(f"Section: {row['section']}")
    print_wrapped(f"Subsection: {row['subsection']}")
    print_wrapped(f"Paragraph {i}: {row['extracted_claims']}")
    print_wrapped("-" * 50)

Section: No Section

Subsection: No Subsection

Paragraph 1: <knowledge>\title{Direct Preference Optimization: Your Language Model is Secretly a
Reward Model}</knowledge>

--------------------------------------------------

Section: No Section

Subsection: No Subsection

Paragraph 2: \begin{abstract} <knowledge>While large-scale unsupervised language models (LMs) learn
broad world knowledge and some reasoning skills, achieving precise control of their behavior is
difficult due to the completely unsupervised nature of their training.</knowledge>
<knowledge>Existing methods for gaining such steerability collect human labels of the relative
quality of model generations and fine-tune the unsupervised LM to align with these preferences,
often with reinforcement learning from human feedback (RLHF).</knowledge> <knowledge>However, RLHF
is a complex and often unstable procedure, first fitting a reward model that reflects the human
preferences, and then fine-tuning the large unsupervised LM using reinforcement learning to maximize
this estimated reward without drifting too far from the original model.</knowledge> <knowledge>In
this paper we introduce a new parameterization of the reward model in RLHF that enables extraction
of the corresponding optimal policy in closed form, allowing us to solve the standard RLHF problem
with only a simple classification loss.</knowledge> <knowledge>The resulting algorithm, which we
call \textit{Direct Preference Optimization} (DPO), is stable, performant, and computationally
lightweight, eliminating the need for sampling from the LM during fine-tuning or performing
significant hyperparameter tuning.</knowledge> <knowledge>Our experiments show that DPO can fine-
tune LMs to align with human preferences as well as or better than existing methods.</knowledge>
<knowledge>Notably, fine-tuning with DPO exceeds PPO-based RLHF in ability to control sentiment of
generations, and matches or improves response quality in summarization and single-turn dialogue
while being substantially simpler to implement and train.</knowledge> \end{abstract}

--------------------------------------------------

Section: Introduction

Subsection: No Subsection

Paragraph 3: <knowledge>Large unsupervised language models (LMs) trained on very large datasets
acquire surprising capabilities~\citep{chowdhery2022palm, brown2020language,
touvron2023llama,bubeck2023sparks}.</knowledge> <knowledge>However, these models are trained on data
generated by humans with a wide variety of goals, priorities, and skillsets.</knowledge>
<knowledge>Some of these goals and skillsets may not be desirable to imitate; for example, while we
may want our AI coding assistant to \textit{understand} common programming mistakes in order to
correct them, nevertheless, when generating code, we would like to bias our model toward the
(potentially rare) high-quality coding ability present in its training data.</knowledge>
<knowledge>Similarly, we might want our language model to be \textit{aware} of a common
misconception believed by 50\% of people, but we certainly do not want the model to claim this
misconception to be true in 50\% of queries about it!</knowledge> <knowledge>In other words,
selecting the model's \emph{desired responses and behavior} from its very wide \textit{knowledge and
abilities} is crucial to building AI systems that are safe, performant, and controllable
\citep{ouyang2022training}.</knowledge> <knowledge>While existing methods typically steer LMs to
match human preferences using reinforcement learning (RL), we will show that the RL-based objective
used by existing methods can be optimized exactly with a simple binary cross-entropy objective,
greatly simplifying the preference learning pipeline.</knowledge>

--------------------------------------------------

Section: Introduction

Subsection: No Subsection

Paragraph 4: <knowledge>\begin{figure}     \centering
\includegraphics[width=0.999\textwidth]{figures/diagrams/teaser.png}     \caption{\textbf{DPO
optimizes for human preferences while avoiding reinforcement learning.} Existing methods for fine-
tuning language models with human feedback first fit a reward model to a dataset of prompts and
human preferences over pairs of responses, and then use RL to find a policy that maximizes the
learned reward. In contrast, DPO directly optimizes for the policy best satisfying the preferences
with a simple classification objective, fitting an \textit{implicit} reward model whose
corresponding optimal policy can be extracted in closed form.}     \vspace{-2mm}
\label{fig:teaser} \end{figure}</knowledge>

--------------------------------------------------

Section: Introduction

Subsection: No Subsection

Paragraph 5: <knowledge>At a high level, existing methods instill the desired behaviors into a
language model using curated sets of human preferences representing the types of behaviors that
humans find safe and helpful.</knowledge> <knowledge>This preference learning stage occurs after an
initial stage of large-scale unsupervised pre-training on a large text dataset.</knowledge>
<knowledge>While the most straightforward approach to preference learning is supervised fine-tuning
on human demonstrations of high quality responses, the most successful class of methods is
reinforcement learning from human (or AI) feedback (RLHF/RLAIF;
\citep{christiano2017deep,bai2022constitutional}).</knowledge> <knowledge>RLHF methods fit a reward
model to a dataset of human preferences and then use RL to optimize a language model policy to
produce responses assigned high reward without drifting excessively far from the original
model.</knowledge> <knowledge>While RLHF produces models with impressive conversational and coding
abilities, the RLHF pipeline is considerably more complex than supervised learning, involving
training multiple LMs and sampling from the LM policy in the loop of training, incurring significant
computational costs.</knowledge>

--------------------------------------------------

Section: Introduction

Subsection: No Subsection

Paragraph 6: <knowledge>In this paper, we show how to directly optimize a language model to adhere
to human preferences, without explicit reward modeling or reinforcement learning.</knowledge>
<knowledge>We propose Direct Preference Optimization (DPO), an algorithm that implicitly optimizes
the same objective as existing RLHF algorithms (reward maximization with a KL-divergence constraint)
but is simple to implement and straightforward to train.</knowledge> <knowledge>Intuitively, the DPO
update increases the relative log probability of preferred to dispreferred responses, but it
incorporates a dynamic, per-example importance weight that prevents the model degeneration that we
find occurs with a naive probability ratio objective.</knowledge> <knowledge>Like existing
algorithms, DPO relies on a theoretical preference model (such as the Bradley-Terry model;
\cite{bradley1952rankanalysis}) that measures how well a given reward function aligns with empirical
preference data.</knowledge> <knowledge>However, while existing methods use the preference model to
define a preference loss to train a reward model and then train a policy that optimizes the learned
reward model, DPO uses a change of variables to define the preference loss as a function of the
policy directly.</knowledge> <knowledge>Given a dataset of human preferences over model responses,
DPO can therefore optimize a policy using a simple binary cross entropy objective, producing the
optimal policy to an implicit reward function fit to the preference data.</knowledge>

--------------------------------------------------

Section: Introduction

Subsection: No Subsection

Paragraph 7: <knowledge>Our main contribution is Direct Preference Optimization (DPO), a simple RL-
free algorithm for training language models from preferences.</knowledge> <knowledge>Our experiments
show that DPO is at least as effective as existing methods, including PPO-based RLHF, for learning
from preferences in tasks such as sentiment modulation, summarization, and dialogue, using language
models with up to 6B parameters.</knowledge>

--------------------------------------------------

Section: Related Work

Subsection: No Subsection

Paragraph 8: <knowledge>Self-supervised language models of increasing scale learn to complete some
tasks zero-shot \citep{radford2019language} or with few-shot prompts
\citep{gpt3,megatron,chowdhery2022palm}.</knowledge> <knowledge>However, their performance on
downstream tasks and alignment with user intent can be significantly improved by fine-tuning on
datasets of instructions and human-written completions \citep{mishra-
etal-2022-cross,sanh2022multitask,chung2022scaling,thoppilan2022lamda}.</knowledge> <knowledge>This
`instruction-tuning' procedure enables LLMs to generalize to instructions outside of the
instruction-tuning set and generally increase their usability \citep{chung2022scaling}.</knowledge>
<knowledge>Despite the success of instruction tuning, \textit{relative} human judgments of response
quality are often easier to collect than expert demonstrations, and thus subsequent works have fine-
tuned LLMs with datasets of human preferences, improving proficiency in translation \citep{kreutzer-
etal-2018-reliability}, summarization \citep{stiennon2022learning,ziegler2020finetuning}, story-
telling \citep{ziegler2020finetuning}, and instruction-following
\citep{ouyang2022training,ramamurthy2023is}.</knowledge> <knowledge>These methods first optimize a
neural network reward function for compatibility with the dataset of preferences under a preference
model such as the Bradley-Terry model \citep{bradley1952rankanalysis}, then fine-tune a language
model to maximize the given reward using reinforcement learning algorithms, commonly REINFORCE
\citep{williams1992reinforce}, proximal policy optimization (PPO; \cite{schulman2017proximal}), or
variants \citep{ramamurthy2023is}.</knowledge> <knowledge>A closely-related line of work leverages
LLMs fine-tuned for instruction following with human feedback to generate additional synthetic
preference data for targeted attributes such as safety or harmlessness
\citep{bai2022constitutional}, using only weak supervision from humans in the form of a text rubric
for the LLM's annotations.</knowledge> <knowledge>These methods represent a convergence of two
bodies of work: one body of work on training language models with reinforcement learning for a
variety of objectives~\citep{Ranzato2015SequenceLT,paulus2018a,wu2018learning} and another body of
work on general methods for learning from human preferences
\citep{christiano2017deep,kupcsik2018learning}.</knowledge>  <knowledge>Despite the appeal of using
relative human preferences, fine-tuning large language models with reinforcement learning remains a
major practical challenge; this work provides a theoretically-justified approach to optimizing
relative preferences without RL.</knowledge>

--------------------------------------------------

Section: Related Work

Subsection: No Subsection

Paragraph 9: <knowledge>Outside of the context of language, learning policies from preferences has
been studied in both bandit and reinforcement learning settings, and several approaches have been
proposed.</knowledge> <knowledge>Contextual bandit learning using preferences or rankings of
actions, rather than rewards, is known as a contextual dueling bandit (CDB;
\cite{yue2012karmed,dudik2015contextual}).</knowledge> <knowledge>In the absence of absolute
rewards, theoretical analysis of CDBs substitutes the notion of an optimal policy with a \textit{von
Neumann winner}, a policy whose expected win rate against \textit{any} other policy is at least 50\%
\citep{dudik2015contextual}.</knowledge> <knowledge>However, in the CDB setting, preference labels
are given online, while in learning from human preferences, we typically learn from a fixed batch of
offline preference-annotated action pairs \citep{yan2022human}.</knowledge> <knowledge>Similarly,
\textit{preference-based RL} (PbRL) learns from binary preferences generated by an \textit{unknown}
`scoring' function rather than rewards \citep{BusaFekete2014,ruiz2023dueling}.</knowledge>
<knowledge>Various algorithms for PbRL exist, including methods that can reuse off-policy preference
data, but generally involve first explicitly estimating the latent scoring function (i.e. the reward
model) and subsequently optimizing it \citep{jain2013learning,BusaFekete2014,christiano2017deep,sadi
gh2017active,kupcsik2018learning}.</knowledge> <knowledge>We instead present a single stage policy
learning approach that directly optimizes a policy to satisfy preferences.</knowledge>

--------------------------------------------------

Section: Preliminaries

Subsection: No Subsection

Paragraph 10: \label{section:prelims}

--------------------------------------------------

Section: Preliminaries

Subsection: No Subsection

Paragraph 11: <knowledge>We review the RLHF pipeline in \citeauthor{ziegler2020finetuning} (and
later \citep{stiennon2022learning, bai2022training, ouyang2022training}).</knowledge> <knowledge>It
usually includes three phases: 1) supervised fine-tuning (SFT); 2) preference sampling and reward
learning and 3) RL optimization.</knowledge>

--------------------------------------------------

Section: Preliminaries

Subsection: No Subsection

Paragraph 12: <knowledge>\textbf{SFT}: RLHF typically begins by fine-tuning a pre-trained LM with
supervised learning on high-quality data for the downstream task(s) of interest (dialogue,
summarization, etc.), to obtain a model $\pisft$.</knowledge>

--------------------------------------------------

Section: Preliminaries

Subsection: No Subsection

Paragraph 13: <knowledge>\textbf{Reward Modelling Phase}: In the second phase the SFT model is
prompted with prompts $x$ to produce pairs of answers $(y_1, y_2)\sim \pisft(y \mid x)$.</knowledge>
<knowledge>These are then presented to human labelers who express preferences for one answer,
denoted as $y_w\succ y_l \mid x$ where $y_w$ and $y_l$ denotes the preferred and dispreferred
completion amongst $(y_1, y_2)$ respectively.</knowledge> <knowledge>The preferences are assumed to
be generated by some latent reward model $r^*(y, x)$, which we do not have access to.</knowledge>
<knowledge>There are a number of approaches used to model preferences, the Bradley-Terry (BT)
\cite{bradley1952rankanalysis} model being a popular choice (although more general Plackett-Luce
ranking models \citep{plackett1975analysis, luce2012individual} are also compatible with the
framework if we have access to several ranked answers).</knowledge> <knowledge>The BT model
stipulates that the human preference distribution $p^*$ can be written as:
\begin{equation}\label{eq:bradley-terry}     p^*(y_1\succ y_2 \mid x)=\frac{\exp\left(r^*(x,
y_1)\right)}{\exp\left(r^*(x, y_1)\right) + \exp\left(r^*(x, y_2)\right)}.
\end{equation}</knowledge> <knowledge>Assuming access to a static dataset of comparisons
$\mathcal{D}=\bigl\{x^{(i)}, y_w^{(i)}, y_l^{(i)}\bigr\}_{i=1}^N$ sampled from $p^*$, we can
parametrize a reward model $r_{\phi}(x, y)$ and estimate the parameters via maximum
likelihood.</knowledge> <knowledge>Framing the problem as a binary classification we have the
negative log-likelihood loss: \begin{equation}\label{eq:reward_model}     \mathcal{L}_R(r_{\phi},
\mathcal{D}) = -\mathbb{E}_{(x, y_w, y_l)\sim \mathcal{D}}\bigl[\log \sigma(r_{\phi}(x, y_w)-
r_{\phi}(x, y_l))\bigr] \end{equation} where $\sigma$ is the logistic function.</knowledge>
<knowledge>In the context of LMs, the network $r_{\phi}(x, y)$ is often initialized from the SFT
model $\pisft(y \mid x)$ with the addition of a linear layer on top of the final transformer layer
that produces a single scalar prediction for the reward value
\cite{ziegler2020finetuning}.</knowledge> <knowledge>To ensure a reward function with lower
variance, prior works normalize the rewards, such that  $\mathbb{E}_{x,y\sim
\mathcal{D}}\left[r_\phi(x, y)\right] = 0$ for all $x$.</knowledge>

--------------------------------------------------

Section: Preliminaries

Subsection: No Subsection

Paragraph 14: <knowledge>\textbf{RL Fine-Tuning Phase}: During the RL phase, the learned reward
function is used to provide feedback to the language model.</knowledge> <knowledge>Following prior
works~\citep{jaques2017sequence, jaques2020human}, the optimization is formulated as
\begin{equation}\label{eq:RL} \max_{\pi_{\theta}}  \mathbb{E}_{x\sim \mathcal{D}, y\sim
\pi_{\theta}(y \mid x)}\bigl[r_{\phi}(x, y)\bigr] -
\beta\mathbb{D}_{\textrm{KL}}\bigl[\pi_{\theta}(y\mid x)\mid \mid \piref(y\mid x)\bigr],
\end{equation} where $\beta$ is a parameter controlling the deviation from the base reference policy
$\piref$, namely the initial SFT model $\pisft$.</knowledge>  <knowledge>In practice, the language
model policy $\pi_\theta$ is also initialized to $\pisft$.</knowledge> <knowledge>The added
constraint is important, as it prevents the model from deviating too far from the distribution on
which the reward model is accurate, as well as maintaining the generation diversity and preventing
mode-collapse to single high-reward answers.</knowledge> <knowledge>Due to the discrete nature of
language generation, this objective is not differentiable and is typically optimized with
reinforcement learning.</knowledge> <knowledge>The standard approach \citep{ziegler2020finetuning,
stiennon2022learning, bai2022training, ouyang2022training} has been to construct the reward function
${r(x, y) = r_{\phi}(x, y) -\beta (\log \pi_{\theta}(y\mid x) - \log \piref(y\mid x))}$, and
maximize using PPO \cite{schulman2017proximal}.</knowledge>

--------------------------------------------------

Section: Direct Preference Optimization

Subsection: No Subsection

Paragraph 15: \label{sec:DPO}

--------------------------------------------------

Section: Direct Preference Optimization

Subsection: No Subsection

Paragraph 16: <knowledge>Motivated by the challenges of applying reinforcement learning algorithms
on large-scale problems such as fine-tuning language models, our goal is to derive a simple approach
for policy optimization using preferences directly.</knowledge> <knowledge>Unlike prior RLHF
methods, which learn a reward and then optimize it via RL, our approach leverages a particular
choice of reward model parameterization that enables extraction of its optimal policy in closed
form, without an RL training loop.</knowledge>  <knowledge>As we will describe next in detail, our
key insight is to leverage an analytical mapping from reward functions to optimal policies, which
enables us to transform a loss function over reward functions into a loss function over
policies.</knowledge> <knowledge>This change-of-variables approach avoids fitting an explicit,
standalone reward model, while still optimizing under existing models of human preferences, such as
the Bradley-Terry model.</knowledge> <knowledge>In essence, the policy network represents both the
language model and the (implicit) reward.</knowledge>

--------------------------------------------------

Section: Direct Preference Optimization

Subsection: No Subsection

Paragraph 17: <knowledge>\textbf{Deriving the DPO objective.} We start with the same RL objective as
prior work, Eq.~\ref{eq:RL}, under a general reward function $r$.</knowledge> <knowledge>Following
prior work~\citep{peters2007reinforcement, peng2019advantage, korbak2022reinforcement,
go2023aligning}, it is straightforward to show that the optimal solution to the KL-constrained
reward maximization objective in Eq.~\ref{eq:RL} takes the form:
\begin{equation}\label{eq:op_policy}     \pi_r(y\mid x) = \frac{1}{Z(x)}\piref(y\mid
x)\exp\left(\frac{1}{\beta}r(x, y)\right), \end{equation}%</knowledge> <knowledge>where $Z(x)
=\sum_{y}\piref(y\mid x)\exp\left(\frac{1}{\beta}r(x, y)\right)$ is the partition

#### Check Knowledge is actually in the paper

In [78]:
import re
import pandas as pd

def extract_text_from_knowledge_tags(text: str) -> list[str]:
    """
    Finds all <knowledge> tags in a given text and extracts their content.

    Args:
        text: A string containing the text to parse, which may include
              <knowledge>...</knowledge> tags.

    Returns:
        A list of strings, where each string is the content found within
        a <knowledge> tag. The content is stripped of leading/trailing
        whitespace.
    """
    # This regex pattern finds all content between <knowledge> and </knowledge>.
    # - The (.*?) part is a non-greedy capture group for the content inside the tags.
    # - The re.DOTALL flag allows the '.' character to match newlines, so tags
    #   that span multiple lines are correctly handled.
    pattern = re.compile(r'<knowledge>(.*?)</knowledge>', re.DOTALL)
    
    # re.findall returns a list of all captured groups.
    matches = pattern.findall(text)
    
    # Clean up any leading/trailing whitespace from the extracted text.
    cleaned_matches = [match.strip() for match in matches]
    
    return cleaned_matches

def remove_knowledge_tags(text: str) -> str:
    """Remove knowledge tags from text while preserving the content."""
    pattern = re.compile(r'</?knowledge>', re.DOTALL)
    return pattern.sub('', text)

paper_df['extracted_claims'] = extracted_claims

# Extract a list of knowledge statements for each row
paper_df['knowledge_list'] = paper_df['extracted_claims'].apply(extract_text_from_knowledge_tags)

# Explode the DataFrame on the knowledge_list column
paper_df_exploded = paper_df.explode('knowledge_list').rename(columns={'knowledge_list': 'raw_knowledge_statement'})

# Count total claims extracted by the LLM before filtering
total_extracted_claims = paper_df_exploded['raw_knowledge_statement'].notna().sum()

# Filter out claims that are not actually in the original paper text (case-insensitive)
paper_lower = paper.lower()
def is_claim_in_paper(claim):
    # Rows with no knowledge statement (claim is NaN) are kept
    if pd.isna(claim):
        return True
    # Check if the lowercased claim is in the lowercased paper
    return claim.strip().lower() in paper_lower

# Apply the filter and create a new validated dataframe
paper_df_validated = paper_df_exploded[paper_df_exploded['raw_knowledge_statement'].apply(is_claim_in_paper)].copy()

# Count claims that passed validation
validated_claims_count = paper_df_validated['raw_knowledge_statement'].notna().sum()
print(f"Found {validated_claims_count}/{total_extracted_claims} extracted claims in the original paper text.")

# Clean up the original paragraph text by removing knowledge tags from the validated dataframe
paper_df_validated['paragraph'] = paper_df_validated['extracted_claims'].apply(remove_knowledge_tags)

# Drop the now-redundant columns
paper_df_validated = paper_df_validated.drop(columns=['extracted_claims'])

# Display the result
print(f"Total rows after exploding and validation: {len(paper_df_validated)}")
paper_df_validated

Found 217/217 extracted claims in the original paper text.
Total rows after exploding and validation: 222

,section,subsection,paragraph,section_text,subsection_text,raw_knowledge_statement
0,No Section,No Subsection,\title{Direct Preference Optimization: Your La...,\title{Direct Preference Optimization: Your La...,\title{Direct Preference Optimization: Your La...,\title{Direct Preference Optimization: Your La...
1,No Section,No Subsection,\begin{abstract}\nWhile large-scale unsupervis...,\title{Direct Preference Optimization: Your La...,\title{Direct Preference Optimization: Your La...,While large-scale unsupervised language models...
1,No Section,No Subsection,\begin{abstract}\nWhile large-scale unsupervis...,\title{Direct Preference Optimization: Your La...,\title{Direct Preference Optimization: Your La...,Existing methods for gaining such steerability...
1,No Section,No Subsection,\begin{abstract}\nWhile large-scale unsupervis...,\title{Direct Preference Optimization: Your La...,\title{Direct Preference Optimization: Your La...,"However, RLHF is a complex and often unstable ..."
1,No Section,No Subsection,\begin{abstract}\nWhile large-scale unsupervis...,\title{Direct Preference Optimization: Your La...,\title{Direct Preference Optimization: Your La...,In this paper we introduce a new parameterizat...
...,...,...,...,...,...,...
40,Discussion,No Subsection,\textbf{Limitations \& Future Work.} Our resul...,"\nLearning from preferences is a powerful, sca...","\nLearning from preferences is a powerful, sca...","On another front, how does reward over-optimiz..."
40,Discussion,No Subsection,\textbf{Limitations \& Future Work.} Our resul...,"\nLearning from preferences is a powerful, sca...","\nLearning from preferences is a powerful, sca...","Additionally, while we evaluate models up to 6..."
40,Discussion,No Subsection,\textbf{Limitations \& Future Work.} Our resul...,"\nLearning from preferences is a powerful, sca...","\nLearning from preferences is a powerful, sca...","Regarding evaluations, we find that the win ra..."
40,Discussion,No Subsection,\textbf{Limitations \& Future Work.} Our resul...,"\nLearning from preferences is a powerful, sca...","\nLearning from preferences is a powerful, sca...","Finally, many possible applications of DPO exi..."
41,Discussion,No Subsection,\end{document},"\nLearning from preferences is a powerful, sca...","\nLearning from preferences is a powerful, sca...",NaN

In [79]:
# Print all the NAs
na_rows = paper_df_validated[paper_df_validated['raw_knowledge_statement'].isna()]
print(f"Found {len(na_rows)} rows with NA knowledge statements:")
for idx, row in na_rows.iterrows():
    print(f"\nRow {idx}:")
    print(f"Paragraph: {row['paragraph']}")

Found 5 rows with NA knowledge statements:

Row 9:
Paragraph: \label{section:prelims}

Row 14:
Paragraph: \label{sec:DPO}

Row 20:
Paragraph: In this section, we give further interpretation of the DPO method, provide theoretical backing, and relate advantages of DPO to issues with actor critic algorithms used for RLHF (such as PPO~\cite{schulman2017proximal}).

Row 21:
Paragraph: \label{sec:theory}

Row 41:
Paragraph: \end{document}

### Now extract all unnecessary latex code from these knowledge statements and call the column "knowledge_statement"

In [80]:

# --- NEW: Clean unnecessary LaTeX from knowledge statements ---
cleaning_prompt = r"""Your task is to remove unmeaningful LaTeX commands while keeping the sentence same otherwise.

# Rules:
1.  **Keep Math**: Preserve mathematical notation written in LaTeX (e.g., `$\mathcal{L}$`, `\pi_\theta`, `\mathbb{E}`). Do not expand or remove them.
2.  **Remove Formatting**: Remove formatting commands like `\textbf{...}`, `\textit{...}`, `\texttt{...}`, etc., but keep the text inside them.
3.  **Handle Citations & References**: Simplify citation commands (e.g., `\cite{...}`, `\citep{...}`) and reference commands (e.g., `\ref{...}`) by removing them but keeping the sentence flow. For example, 'See Appendix~\ref{app:1}' becomes 'See Appendix'.
4.  **Keep Core Content**: The final output must be the original sentence otherwise.
5.  Return only the cleaned sentence, with no extra explanations.

# Example 1:
Input: `Our experiments show that \textbf{DPO} can fine-tune LMs to align with human preferences as well as or better than existing methods.`
Output: `Our experiments show that DPO can fine-tune LMs to align with human preferences as well as or better than existing methods.`

# Example 2:
Input: `The gradient with respect to the parameters $\theta$ can be written as:`
Output: `The gradient with respect to the parameters $\theta$ can be written as:`

# Example 3:
Input: `See Appendix~\ref{app:derivation1} for a complete derivation.`
Output: `See Appendix for a complete derivation.`

# Task:
Now, process the following sentence.
"""

def query_single_clean(statement):
    if statement is None:
        return None
    """Query the LLM to clean a single knowledge statement."""
    prompt = {
        'system': cleaning_prompt,
        'user': f"Input: `{statement}`"
    }
    # Assuming 'gpt-4.1' is a valid model alias in your utils
    return utils.query_llm(prompt, model='gpt-4.1', temperature=0, max_tokens=2048)

paper_df_validated.dropna(inplace=True)
# Get unique non-null statements to avoid redundant API calls
statements_to_clean = paper_df_validated['raw_knowledge_statement'].unique().tolist()
cleaned_statements = []

print(f"Cleaning {len(statements_to_clean)} unique knowledge statements...")
with concurrent.futures.ThreadPoolExecutor(max_workers=16) as executor:
    futures = [executor.submit(query_single_clean, stmt) for stmt in statements_to_clean]
    cleaned_statements = [future.result() for future in futures]

# Create a mapping from raw statement to cleaned statement
cleaning_map = dict(zip(statements_to_clean, cleaned_statements))

# Map the cleaned statements back to the dataframe
paper_df_validated['knowledge_statement'] = paper_df_validated['raw_knowledge_statement'].map(cleaning_map)

paper_df_validated.reset_index(drop=True, inplace=True)
paper_df_validated

Cleaning 217 unique knowledge statements...

,section,subsection,paragraph,section_text,subsection_text,raw_knowledge_statement,knowledge_statement
0,No Section,No Subsection,\title{Direct Preference Optimization: Your La...,\title{Direct Preference Optimization: Your La...,\title{Direct Preference Optimization: Your La...,\title{Direct Preference Optimization: Your La...,Direct Preference Optimization: Your Language ...
1,No Section,No Subsection,\begin{abstract}\nWhile large-scale unsupervis...,\title{Direct Preference Optimization: Your La...,\title{Direct Preference Optimization: Your La...,While large-scale unsupervised language models...,While large-scale unsupervised language models...
2,No Section,No Subsection,\begin{abstract}\nWhile large-scale unsupervis...,\title{Direct Preference Optimization: Your La...,\title{Direct Preference Optimization: Your La...,Existing methods for gaining such steerability...,Existing methods for gaining such steerability...
3,No Section,No Subsection,\begin{abstract}\nWhile large-scale unsupervis...,\title{Direct Preference Optimization: Your La...,\title{Direct Preference Optimization: Your La...,"However, RLHF is a complex and often unstable ...","However, RLHF is a complex and often unstable ..."
4,No Section,No Subsection,\begin{abstract}\nWhile large-scale unsupervis...,\title{Direct Preference Optimization: Your La...,\title{Direct Preference Optimization: Your La...,In this paper we introduce a new parameterizat...,In this paper we introduce a new parameterizat...
...,...,...,...,...,...,...,...
212,Discussion,No Subsection,\textbf{Limitations \& Future Work.} Our resul...,"\nLearning from preferences is a powerful, sca...","\nLearning from preferences is a powerful, sca...","For example, can training with self-labeling f...","For example, can training with self-labeling f..."
213,Discussion,No Subsection,\textbf{Limitations \& Future Work.} Our resul...,"\nLearning from preferences is a powerful, sca...","\nLearning from preferences is a powerful, sca...","On another front, how does reward over-optimiz...","On another front, how does reward over-optimiz..."
214,Discussion,No Subsection,\textbf{Limitations \& Future Work.} Our resul...,"\nLearning from preferences is a powerful, sca...","\nLearning from preferences is a powerful, sca...","Additionally, while we evaluate models up to 6...","Additionally, while we evaluate models up to 6..."
215,Discussion,No Subsection,\textbf{Limitations \& Future Work.} Our resul...,"\nLearning from preferences is a powerful, sca...","\nLearning from preferences is a powerful, sca...","Regarding evaluations, we find that the win ra...","Regarding evaluations, we find that the win ra..."
216,Discussion,No Subsection,\textbf{Limitations \& Future Work.} Our resul...,"\nLearning from preferences is a powerful, sca...","\nLearning from preferences is a powerful, sca...","Finally, many possible applications of DPO exi...","Finally, many possible applications of DPO exi..."

### Identify Context Required for each Probe

In [81]:
# --- NEW: Add context to knowledge statements ---

context_prompt = r"""Your task is to extract a concise, self-contained piece of information from a larger text. You will be given a `subsection_text` and a `knowledge_statement` that is a direct quote from the text.

Your goal is to expand the `knowledge_statement` by including the minimal necessary preceding context from the `subsection_text` to make it understandable on its own. The output should be a single, contiguous block of text copied "word-for-word" from the `subsection_text`.

# Instructions:
1.  The `knowledge_statement` must be at the end of your output.
2.  The output must be a direct, continuous excerpt from the `subsection_text`. Do not add, remove, or change any words.
3.  Include only the *minimal* amount of preceding text required for the `knowledge_statement` to be clear and self-contained. Avoid including entire paragraphs if a single preceding sentence or phrase is sufficient.
4.  If the `knowledge_statement` is already self-contained, just return the `knowledge_statement` itself.
5.  Return only the final text, with no extra explanations.

# Example:
`subsection_text`: "The Transformer architecture has been very successful. It relies on a self-attention mechanism. This mechanism allows the model to weigh the importance of different words in the input sequence. For example, in the sentence 'The cat sat on the mat', self-attention can help the model understand that 'sat' is related to 'cat' and 'mat'."
`knowledge_statement`: "This mechanism allows the model to weigh the importance of different words in the input sequence."

Output: "The Transformer architecture has been very successful. It relies on a self-attention mechanism. This mechanism allows the model to weigh the importance of different words in the input sequence."

# Task:
Now, process the following.
"""

def query_for_context(subsection_text, raw_knowledge_statement):
    if not isinstance(subsection_text, str) or not isinstance(raw_knowledge_statement, str):
        return None
    prompt = {
        'system': context_prompt,
        'user': f"`subsection_text`:\n{subsection_text}\n\n`knowledge_statement`:\n{raw_knowledge_statement}"
    }
    return utils.query_llm(prompt, model='gpt-4.1', temperature=0, max_tokens=2048)

def check_statement_in_paper(statement):
    if not statement:
        return False
    statement_cleaned = statement.strip().strip('"`')
    return statement_cleaned.lower() in paper.lower()

inputs = [(row['subsection_text'], row['raw_knowledge_statement']) for _, row in paper_df_validated.iterrows()]

print(f"Adding context to {len(inputs)} knowledge statements...")
with concurrent.futures.ThreadPoolExecutor(max_workers=16) as executor:
    futures = [executor.submit(query_for_context, sub_text, raw_stmt) for sub_text, raw_stmt in inputs]
    statements_with_context = [future.result() for future in futures]

paper_df_validated['raw_knowledge_statement_with_context'] = statements_with_context

# Check which statements are found in paper
found_in_paper = [check_statement_in_paper(stmt) for stmt in statements_with_context]

# Retry failed statements twice
for retry in range(2):
    failed_indices = [i for i, found in enumerate(found_in_paper) if not found]
    if not failed_indices:
        break
    
    print(f"Retry {retry + 1}: Processing {len(failed_indices)} failed statements...")
    retry_inputs = [inputs[i] for i in failed_indices]
    
    with concurrent.futures.ThreadPoolExecutor(max_workers=16) as executor:
        futures = [executor.submit(query_for_context, sub_text, raw_stmt) for sub_text, raw_stmt in retry_inputs]
        retry_results = [future.result() for future in futures]
    
    for i, result in zip(failed_indices, retry_results):
        statements_with_context[i] = result
        found_in_paper[i] = check_statement_in_paper(result)

# Update dataframe with final results
paper_df_validated['raw_knowledge_statement_with_context'] = statements_with_context

# Add context_needed column
paper_df_validated['context_needed'] = [
    stmt_with_context.strip() != raw_stmt.strip() 
    for stmt_with_context, raw_stmt in zip(statements_with_context, paper_df_validated['raw_knowledge_statement'])
]

# Filter out statements not found in paper
initial_rows = len(paper_df_validated)
paper_df_validated = paper_df_validated[found_in_paper]
final_rows = len(paper_df_validated)

print(f"Filtered out {initial_rows - final_rows} rows that were not found in the original paper text.")
print(f"Remaining rows: {final_rows}")

paper_df_validated

Adding context to 217 knowledge statements...
Retry 1: Processing 4 failed statements...
Retry 2: Processing 3 failed statements...
Filtered out 2 rows that were not found in the original paper text.
Remaining rows: 215

,section,subsection,paragraph,section_text,subsection_text,raw_knowledge_statement,knowledge_statement,raw_knowledge_statement_with_context,context_needed
0,No Section,No Subsection,\title{Direct Preference Optimization: Your La...,\title{Direct Preference Optimization: Your La...,\title{Direct Preference Optimization: Your La...,\title{Direct Preference Optimization: Your La...,Direct Preference Optimization: Your Language ...,\title{Direct Preference Optimization: Your La...,False
1,No Section,No Subsection,\begin{abstract}\nWhile large-scale unsupervis...,\title{Direct Preference Optimization: Your La...,\title{Direct Preference Optimization: Your La...,While large-scale unsupervised language models...,While large-scale unsupervised language models...,While large-scale unsupervised language models...,False
2,No Section,No Subsection,\begin{abstract}\nWhile large-scale unsupervis...,\title{Direct Preference Optimization: Your La...,\title{Direct Preference Optimization: Your La...,Existing methods for gaining such steerability...,Existing methods for gaining such steerability...,While large-scale unsupervised language models...,True
3,No Section,No Subsection,\begin{abstract}\nWhile large-scale unsupervis...,\title{Direct Preference Optimization: Your La...,\title{Direct Preference Optimization: Your La...,"However, RLHF is a complex and often unstable ...","However, RLHF is a complex and often unstable ...",Existing methods for gaining such steerability...,True
4,No Section,No Subsection,\begin{abstract}\nWhile large-scale unsupervis...,\title{Direct Preference Optimization: Your La...,\title{Direct Preference Optimization: Your La...,In this paper we introduce a new parameterizat...,In this paper we introduce a new parameterizat...,"However, RLHF is a complex and often unstable ...",True
...,...,...,...,...,...,...,...,...,...
212,Discussion,No Subsection,\textbf{Limitations \& Future Work.} Our resul...,"\nLearning from preferences is a powerful, sca...","\nLearning from preferences is a powerful, sca...","For example, can training with self-labeling f...","For example, can training with self-labeling f...",Our initial results suggest that DPO policies ...,True
213,Discussion,No Subsection,\textbf{Limitations \& Future Work.} Our resul...,"\nLearning from preferences is a powerful, sca...","\nLearning from preferences is a powerful, sca...","On another front, how does reward over-optimiz...","On another front, how does reward over-optimiz...",Our initial results suggest that DPO policies ...,True
214,Discussion,No Subsection,\textbf{Limitations \& Future Work.} Our resul...,"\nLearning from preferences is a powerful, sca...","\nLearning from preferences is a powerful, sca...","Additionally, while we evaluate models up to 6...","Additionally, while we evaluate models up to 6...","Additionally, while we evaluate models up to 6...",False
215,Discussion,No Subsection,\textbf{Limitations \& Future Work.} Our resul...,"\nLearning from preferences is a powerful, sca...","\nLearning from preferences is a powerful, sca...","Regarding evaluations, we find that the win ra...","Regarding evaluations, we find that the win ra...","Additionally, while we evaluate models up to 6...",True
216,Discussion,No Subsection,\textbf{Limitations \& Future Work.} Our resul...,"\nLearning from preferences is a powerful, sca...","\nLearning from preferences is a powerful, sca...","Finally, many possible applications of DPO exi...","Finally, many possible applications of DPO exi...","Regarding evaluations, we find that the win ra...",True

In [82]:
# print out the rows where context_needed is True. print the raw_knowledge_statement and the raw_knowledge_statement_with_context
context_needed_rows = paper_df_validated[paper_df_validated['context_needed'] == True]

for idx, row in context_needed_rows.iterrows():
    print(f"Row {idx}:")
    print(f"Raw statement: {row['raw_knowledge_statement']}")
    print(f"Statement with context: {row['raw_knowledge_statement_with_context']}")
    print("-" * 80)

Row 2:
Raw statement: Existing methods for gaining such steerability collect human labels of the relative quality of model generations and fine-tune the unsupervised LM to align with these preferences, often with reinforcement learning from human feedback (RLHF).
Statement with context: While large-scale unsupervised language models (LMs) learn broad world knowledge and some reasoning skills, achieving precise control of their behavior is difficult due to the completely unsupervised nature of their training.
Existing methods for gaining such steerability collect human labels of the relative quality of model generations and fine-tune the unsupervised LM to align with these preferences, often with reinforcement learning from human feedback (RLHF).
--------------------------------------------------------------------------------
Row 3:
Raw statement: However, RLHF is a complex and often unstable procedure, first fitting a reward model that reflects the human preferences, and then fine-tuning the large unsupervised LM using reinforcement learning to maximize this estimated reward without drifting too far from the original model.
Statement with context: Existing methods for gaining such steerability collect human labels of the relative quality of model generations and fine-tune the unsupervised LM to align with these preferences, often with reinforcement learning from human feedback (RLHF).
However, RLHF is a complex and often unstable procedure, first fitting a reward model that reflects the human preferences, and then fine-tuning the large unsupervised LM using reinforcement learning to maximize this estimated reward without drifting too far from the original model.
--------------------------------------------------------------------------------
Row 4:
Raw statement: In this paper we introduce a new parameterization of the reward model in RLHF that enables extraction of the corresponding optimal policy in closed form, allowing us to solve the standard RLHF problem with only a simple classification loss.
Statement with context: However, RLHF is a complex and often unstable procedure, first fitting a reward model that reflects the human preferences, and then fine-tuning the large unsupervised LM using reinforcement learning to maximize this estimated reward without drifting too far from the original model.
In this paper we introduce a new parameterization of the reward model in RLHF that enables extraction of the corresponding optimal policy in closed form, allowing us to solve the standard RLHF problem with only a simple classification loss.
--------------------------------------------------------------------------------
Row 5:
Raw statement: The resulting algorithm, which we call \textit{Direct Preference Optimization} (DPO), is stable, performant, and computationally lightweight, eliminating the need for sampling from the LM during fine-tuning or performing significant hyperparameter tuning.
Statement with context: In this paper we introduce a new parameterization of the reward model in RLHF that enables extraction of the corresponding optimal policy in closed form, allowing us to solve the standard RLHF problem with only a simple classification loss.
The resulting algorithm, which we call \textit{Direct Preference Optimization} (DPO), is stable, performant, and computationally lightweight, eliminating the need for sampling from the LM during fine-tuning or performing significant hyperparameter tuning.
--------------------------------------------------------------------------------
Row 7:
Raw statement: Notably, fine-tuning with DPO exceeds PPO-based RLHF in ability to control sentiment of generations, and matches or improves response quality in summarization and single-turn dialogue while being substantially simpler to implement and train.
Statement with context: Our experiments show that DPO can fine-tune LMs to align with human preferences as well as or better than existing methods. Notably, fine-tuning with DPO exceeds PPO-based RLHF in ability to control sentiment of generations, and matches or improves response quality in summarization and single-turn dialogue while being substantially simpler to implement and train.
--------------------------------------------------------------------------------
Row 9:
Raw statement: However, these models are trained on data generated by humans with a wide variety of goals, priorities, and skillsets.
Statement with context: Large unsupervised language models (LMs) trained on very large datasets acquire surprising capabilities~\citep{chowdhery2022palm, brown2020language, touvron2023llama,bubeck2023sparks}. However, these models are trained on data generated by humans with a wide variety of goals, priorities, and skillsets.
--------------------------------------------------------------------------------
Row 10:
Raw statement: Some of these goals and skillsets may not be desirable to imitate; for example, while we may want our AI coding assistant to \textit{understand} common programming mistakes in order to correct them, nevertheless, when generating code, we would like to bias our model toward the (potentially rare) high-quality coding ability present in its training data.
Statement with context: However, these models are trained on data generated by humans with a wide variety of goals, priorities, and skillsets. Some of these goals and skillsets may not be desirable to imitate; for example, while we may want our AI coding assistant to \textit{understand} common programming mistakes in order to correct them, nevertheless, when generating code, we would like to bias our model toward the (potentially rare) high-quality coding ability present in its training data.
--------------------------------------------------------------------------------
Row 11:
Raw statement: Similarly, we might want our language model to be \textit{aware} of a common misconception believed by 50\% of people, but we certainly do not want the model to claim this misconception to be true in 50\% of queries about it!
Statement with context: Some of these goals and skillsets may not be desirable to imitate; for example, while we may want our AI coding assistant to \textit{understand} common programming mistakes in order to correct them, nevertheless, when generating code, we would like to bias our model toward the (potentially rare) high-quality coding ability present in its training data. Similarly, we might want our language model to be \textit{aware} of a common misconception believed by 50\% of people, but we certainly do not want the model to claim this misconception to be true in 50\% of queries about it!
--------------------------------------------------------------------------------
Row 12:
Raw statement: In other words, selecting the model's \emph{desired responses and behavior} from its very wide \textit{knowledge and abilities} is crucial to building AI systems that are safe, performant, and controllable \citep{ouyang2022training}.
Statement with context: Some of these goals and skillsets may not be desirable to imitate; for example, while we may want our AI coding assistant to \textit{understand} common programming mistakes in order to correct them, nevertheless, when generating code, we would like to bias our model toward the (potentially rare) high-quality coding ability present in its training data. Similarly, we might want our language model to be \textit{aware} of a common misconception believed by 50\% of people, but we certainly do not want the model to claim this misconception to be true in 50\% of queries about it! In other words, selecting the model's \emph{desired responses and behavior} from its very wide \textit{knowledge and abilities} is crucial to building AI systems that are safe, performant, and controllable \citep{ouyang2022training}.
--------------------------------------------------------------------------------
Row 13:
Raw statement: While existing methods typically steer LMs to match human preferences using reinforcement learning (RL), we will show that the RL-based objective used by existing methods can be optimized exactly with a simple binary cross-entropy objective, greatly simplifying the preference learning pipeline.
Statement with context: However, these models are trained on data generated by humans with a wide variety of goals, priorities, and skillsets. Some of these goals and skillsets may not be desirable to imitate; for example, while we may want our AI coding assistant to \textit{understand} common programming mistakes in order to correct them, nevertheless, when generating code, we would like to bias our model toward the (potentially rare) high-quality coding ability present in its training data. Similarly, we might want our language model to be \textit{aware} of a common misconception believed by 50\% of people, but we certainly do not want the model to claim this misconception to be true in 50\% of queries about it! In other words, selecting the model's \emph{desired responses and behavior} from its very wide \textit{knowledge and abilities} is crucial to building AI systems that are safe, performant, and controllable \citep{ouyang2022training}. While existing methods typically steer LMs to match human preferences using reinforcement learning (RL), we will show that the RL-based objective used by existing methods can be optimized exactly with a simple binary cross-entropy objective, greatly simplifying the preference learning pipeline.
--------------------------------------------------------------------------------
Row 16:
Raw statement: This preference learning stage occurs after an initial stage of large-scale unsupervised pre-training on a large text dataset.
Statement with context: At a high level, existing methods instill the desired behaviors into a language model using curated sets of human preferences representing the types of behaviors that humans find safe and helpful. This preference learning stage occurs after an initial stage of large-scale unsupervised pre-training on a large text dataset.
--------------------------------------------------------------------------------
Row 17:
Raw statement: While the most straightforward approach to preference learning is supervised fine-tuning on human demonstrations of high quality responses, the most successful class of methods is reinforcement learning from human (or AI) feedback (RLHF/RLAIF; \citep{christiano2017deep,bai2022constitutional}).
Statement with context: At a high level, existing methods instill the desired behaviors into a language model using curated sets of human preferences representing the types of behaviors that humans find safe and helpful. This preference learning stage occurs after an initial stage of large-scale unsupervised pre-training on a large text dataset. While the most straightforward approach to preference learning is supervised fine-tuning on human demonstrations of high quality responses, the most successful class of methods is reinforcement learning from human (or AI) feedback (RLHF/RLAIF; \citep{christiano2017deep,bai2022constitutional}).
--------------------------------------------------------------------------------
Row 18:
Raw statement: RLHF methods fit a reward model to a dataset of human preferences and then use RL to optimize a language model policy to produce responses assigned high reward without drifting excessively far from the original model.
Statement with context: While the most straightforward approach to preference learning is supervised fine-tuning on human demonstrations of high quality responses, the most successful class of methods is reinforcement learning from human (or AI) feedback (RLHF/RLAIF; \citep{christiano2017deep,bai2022constitutional}). RLHF methods fit a reward model to a dataset of human preferences and then use RL to optimize a language model policy to produce responses assigned high reward without drifting excessively far from the original model.
--------------------------------------------------------------------------------
Row 19:
Raw statement: While RLHF produces models with impressive conversational and coding abilities, the RLHF pipeline is considerably more complex than supervised learning, involving training multiple LMs and sampling from the LM policy in the loop of training, incurring significant computational costs.
Statement with context: While the most straightforward approach to preference learning is supervised fine-tuning on human demonstrations of high quality responses, the most successful class of methods is reinforcement learning from human (or AI) feedback (RLHF/RLAIF; \citep{christiano2017deep,bai2022constitutional}). RLHF methods fit a reward model to a dataset of human preferences and then use RL to optimize a language model policy to produce responses assigned high reward without drifting excessively far from the original model. While RLHF produces models with impressive conversational and coding abilities, the RLHF pipeline is considerably more complex than supervised learning, involving training multiple LMs and sampling from the LM policy in the loop of training, incurring significant computational costs.
--------------------------------------------------------------------------------
Row 21:
Raw statement: We propose Direct Preference Optimization (DPO), an algorithm that implicitly optimizes the same objective as existing RLHF algorithms (reward maximization with a KL-divergence constraint) but is simple to implement and straightforward to train.
Statement with context: In this paper, we show how to directly optimize a language model to adhere to human preferences, without explicit reward modeling or reinforcement learning. We propose Direct Preference Optimization (DPO), an algorithm that implicitly optimizes the same objective as existing RLHF algorithms (reward maximization with a KL-divergence constraint) but is simple to implement and straightforward to train.
--------------------------------------------------------------------------------
Row 22:
Raw statement: Intuitively, the DPO update increases the relative log probability of preferred to dispreferred responses, but it incorporates a dynamic, per-example importance weight that prevents the model degeneration that we find occurs with a naive probability ratio objective.
Statement with context: We propose Direct Preference Optimization (DPO), an algorithm that implicitly optimizes the same objective as existing RLHF algorithms (reward maximization with a KL-divergence constraint) but is simple to implement and straightforward to train. Intuitively, the DPO update increases the relative log probability of preferred to dispreferred responses, but it incorporates a dynamic, per-example importance weight that prevents the model degeneration that we find occurs with a naive probability ratio objective.
--------------------------------------------------------------------------------
Row 23:
Raw statement: Like existing algorithms, DPO relies on a theoretical preference model (such as the Bradley-Terry model; \cite{bradley1952rankanalysis}) that measures how well a given reward function aligns with empirical preference data.
Statement with context: Intuitively, the DPO update increases the relative log probability of preferred to dispreferred responses, but it incorporates a dynamic, per-example importance weight that prevents the model degeneration that we find occurs with a naive probability ratio objective. Like existing algorithms, DPO relies on a theoretical preference model (such as the Bradley-Terry model; \cite{bradley1952rankanalysis}) that measures how well a given reward function aligns with empirical preference data.
--------------------------------------------------------------------------------
Row 24:
Raw statement: However, while existing methods use the preference model to define a preference loss to train a reward model and then train a policy that optimizes the learned reward model, DPO uses a change of variables to define the preference loss as a function of the policy directly.
Statement with context: Like existing algorithms, DPO relies on a theoretical preference model (such as the Bradley-Terry model; \cite{bradley1952rankanalysis}) that measures how well a given reward function aligns with empirical preference data. However, while existing methods use the preference model to define a preference loss to train a reward model and then train a policy that optimizes the learned reward model, DPO uses a change of variables to define the preference loss as a function of the policy directly.
--------------------------------------------------------------------------------
Row 25:
Raw statement: Given a dataset of human preferences over model responses, DPO can therefore optimize a policy using a simple binary cross entropy objective, producing the optimal policy to an implicit reward function fit to the preference data.
Statement with context: Like existing algorithms, DPO relies on a theoretical preference model (such as the Bradley-Terry model; \cite{bradley1952rankanalysis}) that measures how well a given reward function aligns with empirical preference data. However, while existing methods use the preference model to define a preference loss to train a reward model and then train a policy that optimizes the learned reward model, DPO uses a change of variables to define the preference loss as a function of the policy directly. Given a dataset of human preferences over model responses, DPO can therefore optimize a policy using a simple binary cross entropy objective, producing the optimal policy to an implicit reward function fit to the preference data.
--------------------------------------------------------------------------------
Row 27:
Raw statement: Our experiments show that DPO is at least as effective as existing methods, including PPO-based RLHF, for learning from preferences in tasks such as sentiment modulation, summarization, and dialogue, using language models with up to 6B parameters.
Statement with context: Our main contribution is Direct Preference Optimization (DPO), a simple RL-free algorithm for training language models from preferences. Our experiments show that DPO is at least as effective as existing methods, including PPO-based RLHF, for learning from preferences in tasks such as sentiment modulation, summarization, and dialogue, using language models with up to 6B parameters.
--------------------------------------------------------------------------------
Row 29:
Raw statement: However, their performance on downstream tasks and alignment with user intent can be significantly improved by fine-tuning on datasets of instructions and human-written completions \citep{mishra-etal-2022-cross,sanh2022multitask,chung2022scaling,thoppilan2022lamda}.
Statement with context: Self-supervised language models of increasing scale learn to complete some tasks zero-shot \citep{radford2019language} or with few-shot prompts \citep{gpt3,megatron,chowdhery2022palm}. However, their performance on downstream tasks and alignment with user intent can be significantly improved by fine-tuning on datasets of instructions and human-written completions \citep{mishra-etal-2022-cross,sanh2022multitask,chung2022scaling,thoppilan2022lamda}.
--------------------------------------------------------------------------------
Row 30:
Raw statement: This `instruction-tuning' procedure enables LLMs to generalize to instructions outside of the instruction-tuning set and generally increase their usability \citep{chung2022scaling}.

In [83]:
# save the paper_df_validated to a csv file
paper_df_validated.to_csv('DPO_knowledge_probes.csv', index=False)

### Identify Target Span Given the Piece of Knowledge

In [ ]:
pass

### Creating Ontologies for the Knowledge

In [ ]:
for claim in extracted_claims:
    prompt = {}

    prompt['system'] = """Your task is to act as a strict claim evaluator. You will be given a single claim. Your goal is to determine if this claim meets ALL of the following criteria.

    # Evaluation Criteria

    1.  **Objective and Factual:** Extract statements presented as facts or claims, not opinions, subjective evaluations, or superlative statements.
        *   GOOD: "Direct Preference Optimization (DPO) is an algorithm for aligning language models with human preferences."
        *   BAD: "We believe DPO is the most promising approach for alignment." (Subjective belief)
        *   BAD: "DPO is the best method." (Superlative statement)

    3.  **Generalizable Knowledge, not Paper-Specific Results:** Focus on definitions, mechanisms, and core concepts. Do not extract claims about the paper's specific findings, experimental setup, or citations.
        *   GOOD: "Reinforcement Learning from Human Feedback (RLHF) typically involves training a separate reward model on preference data."
        *   BAD: "Our experiments show a 5% improvement on the benchmark." (Specific result)
        *   BAD: "As shown by Smith et al. (2023), the method is effective." (Relies on a citation)"""

    prompt['user'] = f"""Claim: {claim}. Does this claim strictly meet all four criteria? Respond with only the word "True" or "False"."""
    output = utils.query_llm(prompt, model='gpt-4.1', max_tokens=2)
    print(output)