In [2]:
import pandas as pd

In [51]:

import textwrap
import sys 
sys.path.append('../../')
import utils.llm_training as llm_training 

import utils.utils as utils
import pandas as pd

with open('../../data/arxiv/cleaned_DPO.txt', 'r') as f:
    paper = f.read()


def print_wrapped(text, width=100):
    """
    Prints the given text wrapped to a specified width for better readability in notebooks.
    This function preserves paragraph breaks.
    """
    paragraphs = text.split('\n\n')
    for para in paragraphs:
        print(textwrap.fill(para, width=width))
        print()
        
print_wrapped(paper)

\title{Direct Preference Optimization: Your Language Model is Secretly a Reward Model}

\begin{abstract} While large-scale unsupervised language models (LMs) learn broad world knowledge
and some reasoning skills, achieving precise control of their behavior is difficult due to the
completely unsupervised nature of their training. Existing methods for gaining such steerability
collect human labels of the relative quality of model generations and fine-tune the unsupervised LM
to align with these preferences, often with reinforcement learning from human feedback (RLHF).
However, RLHF is a complex and often unstable procedure, first fitting a reward model that reflects
the human preferences, and then fine-tuning the large unsupervised LM using reinforcement learning
to maximize this estimated reward without drifting too far from the original model. In this paper we
introduce a new parameterization of the reward model in RLHF that enables extraction of the
corresponding optimal policy in closed form, allowing us to solve the standard RLHF problem with
only a simple classification loss. The resulting algorithm, which we call \textit{Direct Preference
Optimization} (DPO), is stable, performant, and computationally lightweight, eliminating the need
for sampling from the LM during fine-tuning or performing significant hyperparameter tuning. Our
experiments show that DPO can fine-tune LMs to align with human preferences as well as or better
than existing methods. Notably, fine-tuning with DPO exceeds PPO-based RLHF in ability to control
sentiment of generations, and matches or improves response quality in summarization and single-turn
dialogue while being substantially simpler to implement and train. \end{abstract}

\section{Introduction} Large unsupervised language models (LMs) trained on very large datasets
acquire surprising capabilities~\citep{chowdhery2022palm, brown2020language,
touvron2023llama,bubeck2023sparks}. However, these models are trained on data generated by humans
with a wide variety of goals, priorities, and skillsets. Some of these goals and skillsets may not
be desirable to imitate; for example, while we may want our AI coding assistant to
\textit{understand} common programming mistakes in order to correct them, nevertheless, when
generating code, we would like to bias our model toward the (potentially rare) high-quality coding
ability present in its training data. Similarly, we might want our language model to be
\textit{aware} of a common misconception believed by 50\% of people, but we certainly do not want
the model to claim this misconception to be true in 50\% of queries about it! In other words,
selecting the model's \emph{desired responses and behavior} from its very wide \textit{knowledge and
abilities} is crucial to building AI systems that are safe, performant, and controllable
\citep{ouyang2022training}. While existing methods typically steer LMs to match human preferences
using reinforcement learning (RL), we will show that the RL-based objective used by existing methods
can be optimized exactly with a simple binary cross-entropy objective, greatly simplifying the
preference learning pipeline.

\begin{figure}     \centering
\includegraphics[width=0.999\textwidth]{figures/diagrams/teaser.png}     \caption{\textbf{DPO
optimizes for human preferences while avoiding reinforcement learning.} Existing methods for fine-
tuning language models with human feedback first fit a reward model to a dataset of prompts and
human preferences over pairs of responses, and then use RL to find a policy that maximizes the
learned reward. In contrast, DPO directly optimizes for the policy best satisfying the preferences
with a simple classification objective, fitting an \textit{implicit} reward model whose
corresponding optimal policy can be extracted in closed form.}     \vspace{-2mm}
\label{fig:teaser} \end{figure}

At a high level, existing methods instill the desired behaviors into a language model using curated
sets of human preferences representing the types of behaviors that humans find safe and helpful.
This preference learning stage occurs after an initial stage of large-scale unsupervised pre-
training on a large text dataset. While the most straightforward approach to preference learning is
supervised fine-tuning on human demonstrations of high quality responses, the most successful class
of methods is reinforcement learning from human (or AI) feedback (RLHF/RLAIF;
\citep{christiano2017deep,bai2022constitutional}). RLHF methods fit a reward model to a dataset of
human preferences and then use RL to optimize a language model policy to produce responses assigned
high reward without drifting excessively far from the original model. While RLHF produces models
with impressive conversational and coding abilities, the RLHF pipeline is considerably more complex
than supervised learning, involving training multiple LMs and sampling from the LM policy in the
loop of training, incurring significant computational costs.

In this paper, we show how to directly optimize a language model to adhere to human preferences,
without explicit reward modeling or reinforcement learning. We propose Direct Preference
Optimization (DPO), an algorithm that implicitly optimizes the same objective as existing RLHF
algorithms (reward maximization with a KL-divergence constraint) but is simple to implement and
straightforward to train. Intuitively, the DPO update increases the relative log probability of
preferred to dispreferred responses, but it incorporates a dynamic, per-example importance weight
that prevents the model degeneration that we find occurs with a naive probability ratio objective.
Like existing algorithms, DPO relies on a theoretical preference model (such as the Bradley-Terry
model; \cite{bradley1952rankanalysis}) that measures how well a given reward function aligns with
empirical preference data. However, while existing methods use the preference model to define a
preference loss to train a reward model and then train a policy that optimizes the learned reward
model, DPO uses a change of variables to define the preference loss as a function of the policy
directly. Given a dataset of human preferences over model responses, DPO can therefore optimize a
policy using a simple binary cross entropy objective, producing the optimal policy to an implicit
reward function fit to the preference data.

Our main contribution is Direct Preference Optimization (DPO), a simple RL-free algorithm for
training language models from preferences. Our experiments show that DPO is at least as effective as
existing methods, including PPO-based RLHF, for learning from preferences in tasks such as sentiment
modulation, summarization, and dialogue, using language models with up to 6B parameters.

\section{Related Work}

Self-supervised language models of increasing scale learn to complete some tasks zero-shot
\citep{radford2019language} or with few-shot prompts \citep{gpt3,megatron,chowdhery2022palm}.
However, their performance on downstream tasks and alignment with user intent can be significantly
improved by fine-tuning on datasets of instructions and human-written completions \citep{mishra-
etal-2022-cross,sanh2022multitask,chung2022scaling,thoppilan2022lamda}. This `instruction-tuning'
procedure enables LLMs to generalize to instructions outside of the instruction-tuning set and
generally increase their usability \citep{chung2022scaling}. Despite the success of instruction
tuning, \textit{relative} human judgments of response quality are often easier to collect than
expert demonstrations, and thus subsequent works have fine-tuned LLMs with datasets of human
preferences, improving proficiency in translation \citep{kreutzer-etal-2018-reliability},
summarization \citep{stiennon2022learning,ziegler2020finetuning}, story-telling
\citep{ziegler2020finetuning}, and instruction-following
\citep{ouyang2022training,ramamurthy2023is}. These methods first optimize a neural network reward
function for compatibility with the dataset of preferences under a preference model such as the
Bradley-Terry model \citep{bradley1952rankanalysis}, then fine-tune a language model to maximize the
given reward using reinforcement learning algorithms, commonly REINFORCE
\citep{williams1992reinforce}, proximal policy optimization (PPO; \cite{schulman2017proximal}), or
variants \citep{ramamurthy2023is}. A closely-related line of work leverages LLMs fine-tuned for
instruction following with human feedback to generate additional synthetic preference data for
targeted attributes such as safety or harmlessness \citep{bai2022constitutional}, using only weak
supervision from humans in the form of a text rubric for the LLM's annotations. These methods
represent a convergence of two bodies of work: one body of work on training language models with
reinforcement learning for a variety of
objectives~\citep{Ranzato2015SequenceLT,paulus2018a,wu2018learning} and another body of work on
general methods for learning from human preferences \citep{christiano2017deep,kupcsik2018learning}.
Despite the appeal of using relative human preferences, fine-tuning large language models with
reinforcement learning remains a major practical challenge; this work provides a theoretically-
justified approach to optimizing relative preferences without RL.

Outside of the context of language, learning policies from preferences has been studied in both
bandit and reinforcement learning settings, and several approaches have been proposed. Contextual
bandit learning using preferences or rankings of actions, rather than rewards, is known as a
contextual dueling bandit (CDB; \cite{yue2012karmed,dudik2015contextual}). In the absence of
absolute rewards, theoretical analysis of CDBs substitutes the notion of an optimal policy with a
\textit{von Neumann winner}, a policy whose expected win rate against \textit{any} other policy is
at least 50\% \citep{dudik2015contextual}. However, in the CDB setting, preference labels are given
online, while in learning from human preferences, we typically learn from a fixed batch of offline
preference-annotated action pairs \citep{yan2022human}. Similarly, \textit{preference-based RL}
(PbRL) learns from binary preferences generated by an \textit{unknown} `scoring' function rather
than rewards \citep{BusaFekete2014,ruiz2023dueling}. Various algorithms for PbRL exist, including
methods that can reuse off-policy preference data, but generally involve first explicitly estimating
the latent scoring function (i.e. the reward model) and subsequently optimizing it
\citep{jain2013learning,BusaFekete2014,christiano2017deep,sadigh2017active,kupcsik2018learning}. We
instead present a single stage policy learning approach that directly optimizes a policy to satisfy
preferences.

\section{Preliminaries}\label{section:prelims}

We review the RLHF pipeline in \citeauthor{ziegler2020finetuning} (and later
\citep{stiennon2022learning, bai2022training, ouyang2022training}). It usually includes three
phases: 1) supervised fine-tuning (SFT); 2) preference sampling and reward learning and 3) RL
optimization.

\textbf{SFT}: RLHF typically begins by fine-tuning a pre-trained LM with supervised learning on
high-quality data for the downstream task(s) of interest (dialogue, summarization, etc.), to obtain
a model $\pisft$.

\textbf{Reward Modelling Phase}: In the second phase the SFT model is prompted with prompts $x$ to
produce pairs of answers $(y_1, y_2)\sim \pisft(y \mid x)$. These are then presented to human
labelers who express preferences for one answer, denoted as $y_w\succ y_l \mid x$ where $y_w$ and
$y_l$ denotes the preferred and dispreferred completion amongst $(y_1, y_2)$ respectively. The
preferences are assumed to be generated by some latent reward model $r^*(y, x)$, which we do not
have access to. There are a number of approaches used to model preferences, the Bradley-Terry (BT)
\cite{bradley1952rankanalysis} model being a popular choice (although more general Plackett-Luce
ranking models \citep{plackett1975analysis, luce2012individual} are also compatible with the
framework if we have access to several ranked answers). The BT model stipulates that the human
preference distribution $p^*$ can be written as: \begin{equation}\label{eq:bradley-terry}
p^*(y_1\succ y_2 \mid x)=\frac{\exp\left(r^*(x, y_1)\right)}{\exp\left(r^*(x, y_1)\right) +
\exp\left(r^*(x, y_2)\right)}. \end{equation} Assuming access to a static dataset of comparisons
$\mathcal{D}=\bigl\{x^{(i)}, y_w^{(i)}, y_l^{(i)}\bigr\}_{i=1}^N$ sampled from $p^*$, we can
parametrize a reward model $r_{\phi}(x, y)$ and estimate the parameters via maximum likelihood.
Framing the problem as a binary classification we have the negative log-likelihood loss:
\begin{equation}\label{eq:reward_model}     \mathcal{L}_R(r_{\phi}, \mathcal{D}) = -\mathbb{E}_{(x,
y_w, y_l)\sim \mathcal{D}}\bigl[\log \sigma(r_{\phi}(x, y_w)- r_{\phi}(x, y_l))\bigr] \end{equation}
where $\sigma$ is the logistic function. In the context of LMs, the network $r_{\phi}(x, y)$ is
often initialized from the SFT model $\pisft(y \mid x)$ with the addition of a linear layer on top
of the final transformer layer that produces a single scalar prediction for the reward value
\cite{ziegler2020finetuning}. To ensure a reward function with lower variance, prior works normalize
the rewards, such that  $\mathbb{E}_{x,y\sim \mathcal{D}}\left[r_\phi(x, y)\right] = 0$ for all $x$.

\textbf{RL Fine-Tuning Phase}: During the RL phase, the learned reward function is used to provide
feedback to the language model. Following prior works~\citep{jaques2017sequence, jaques2020human},
the optimization is formulated as \begin{equation}\label{eq:RL} \max_{\pi_{\theta}}
\mathbb{E}_{x\sim \mathcal{D}, y\sim \pi_{\theta}(y \mid x)}\bigl[r_{\phi}(x, y)\bigr] -
\beta\mathbb{D}_{\textrm{KL}}\bigl[\pi_{\theta}(y\mid x)\mid \mid \piref(y\mid x)\bigr],
\end{equation} where $\beta$ is a parameter controlling the deviation from the base reference policy
$\piref$, namely the initial SFT model $\pisft$.  In practice, the language model policy
$\pi_\theta$ is also initialized to $\pisft$. The added constraint is important, as it prevents the
model from deviating too far from the distribution on which the reward model is accurate, as well as
maintaining the generation diversity and preventing mode-collapse to single high-reward answers. Due
to the discrete nature of language generation, this objective is not differentiable and is typically
optimized with reinforcement learning. The standard approach \citep{ziegler2020finetuning,
stiennon2022learning, bai2022training, ouyang2022training} has been to construct the reward function
${r(x, y) = r_{\phi}(x, y) -\beta (\log \pi_{\theta}(y\mid x) - \log \piref(y\mid x))}$, and
maximize using PPO \cite{schulman2017proximal}.

\section{Direct Preference Optimization}\label{sec:DPO}

Motivated by the challenges of applying reinforcement learning algorithms on large-scale problems
such as fine-tuning language models, our goal is to derive a simple approach for policy optimization
using preferences directly. Unlike prior RLHF methods, which learn a reward and then optimize it via
RL, our approach leverages a particular choice of reward model parameterization that enables
extraction of its optimal policy in closed form, without an RL training loop.  As we will describe
next in detail, our key insight is to leverage an analytical mapping from reward functions to
optimal policies, which enables us to transform a loss function over reward functions into a loss
function over policies. This change-of-variables approach avoids fitting an explicit, standalone
reward model, while still optimizing under existing models of human preferences, such as the
Bradley-Terry model. In essence, the policy network represents both the language model and the
(implicit) reward.

\textbf{Deriving the DPO objective.} We start with the same RL objective as prior work,
Eq.~\ref{eq:RL}, under a general reward function $r$. Following prior
work~\citep{peters2007reinforcement, peng2019advantage, korbak2022reinforcement, go2023aligning}, it
is straightforward to show that the optimal solution to the KL-constrained reward maximization
objective in Eq.~\ref{eq:RL} takes the form: \begin{equation}\label{eq:op_policy}     \pi_r(y\mid x)
= \frac{1}{Z(x)}\piref(y\mid x)\exp\left(\frac{1}{\beta}r(x, y)\right), \end{equation}% where $Z(x)
=\sum_{y}\piref(y\mid x)\exp\left(\frac{1}{\beta}r(x, y)\right)$ is the partition function. See
Appendix \ref{app:derivation1} for a complete derivation. Even if we use the MLE estimate $r_{\phi}$
of the ground-truth reward function $r^*$, it is still expensive to estimate the partition function
$Z(x)$ \citep{korbak2022reinforcement, go2023aligning}, which makes this representation hard to
utilize in practice. However, we can rearrange Eq.~\ref{eq:op_policy} to express the reward function
in terms of its corresponding optimal policy $\pi_r$, the reference policy $\piref$, and the unknown
partition function $Z(\cdot)$. Specifically, we first take the logarithm of both sides of
Eq.~\ref{eq:op_policy} and then with some algebra we obtain: \begin{equation}\label{eq:main_eq}
r(x,y) =\beta \log \frac{\pi_r(y\mid x)}{\piref(y\mid x)} + \beta \log Z(x). \end{equation} We can
apply this reparameterization to the ground-truth reward $r^*$ and corresponding optimal model
$\pi^*$. Fortunately, the Bradley-Terry model depends only on the difference of rewards between two
completions, i.e., ${p^*(y_1 \succ y_2 \mid x) = \sigma(r^*(x, y_1) - r^*(x, y_2))}$. Substituting
the reparameterization in Eq.~\ref{eq:main_eq} for $r^*(x,y)$ into the preference model
Eq.~\ref{eq:bradley-terry}, the partition function cancels, and we can express the human preference
probability in terms of only the optimal policy $\pi^*$ and reference policy $\piref$. Thus, the
optimal RLHF policy $\pi^*$ under the Bradley-Terry model satisfies the preference model:
\begin{equation}\label{eq:objective}     p^*(y_1\succ y_2 \mid x)=\frac{1}{1 + \exp\left(\beta \log
\frac{\pi^*(y_2\mid x)}{\piref(y_2\mid x)} - \beta \log \frac{\pi^*(y_1\mid x)}{\piref(y_1\mid
x)}\right)} \end{equation} The derivation is in Appendix~\ref{app:derivation2}. While
Eq.~\ref{eq:objective} uses the Bradley-Terry model, we can similarly derive expressions under the
more general Plackett-Luce models~\citep{plackett1975analysis, luce2012individual}, shown in
Appendix~\ref{app:plackett_luce_models}.

Now that we have the probability of human preference data in terms of the optimal policy rather than
the reward model, we can formulate a maximum likelihood objective for a parametrized policy
$\pi_\theta$. Analogous to the reward modeling approach (i.e. Eq.~\ref{eq:reward_model}), our policy
objective becomes: \begin{equation}\label{eq:optimum_model}     \mathcal{L}_\text{DPO}(\pi_{\theta};
\piref) = -\mathbb{E}_{(x, y_w, y_l)\sim \mathcal{D}}\left[\log \sigma \left(\beta \log
\frac{\pi_{\theta}(y_w\mid x)}{\piref(y_w\mid x)} - \beta \log \frac{\pi_{\theta}(y_l\mid
x)}{\piref(y_l\mid x)}\right)\right]. \end{equation} This way, we fit an implicit reward using an
alternative parameterization, whose optimal policy is simply $\pi_\theta$. Moreover, since our
procedure is equivalent to fitting a reparametrized Bradley-Terry model, it enjoys certain
theoretical properties, such as consistencies under suitable assumption of the preference data
distribution \cite{bong2022generalized}. In Section~\ref{sec:theory}, we further discuss theoretical
properties of DPO in relation to other works.

\textbf{What does the DPO update do?} For a mechanistic understanding of DPO, it is useful to
analyze the gradient of the loss function $\mathcal{L}_\text{DPO}$. The gradient with respect to the
parameters $\theta$ can be written as: \begin{multline*}\label{eq:gradient}     \nabla_\theta

### 1. Generate High-Level Questions

In [40]:
# Parse paper into sections
# sections_df = parse_paper_structure(paper)
from importlib import reload
reload(utils)
# Create questions for each section
all_questions = []

# # Get the full text for this section
# section_text = section_group['section_text'].iloc[0]

#Then, at the end, turn these questions into cloze form sentences in which the answer is placed at the end of the sentence. Provide the cloze sentence with the answer missing, and the answer in JSON.

section_text = paper
prompt = {}
prompt['system'] = """### Instructions
Based on your understanding of the provided text, generate inference questions to test a reader's comprehension and understanding of the text. The most important aspect is that the question should build upon the text to draw a conclusion or synthesize the knowledge.
- The question can be as long as needed, but the answer should be a phrase that is 1-5 words. 
- The questions should NOT be about factual recall that asks to recall a specific fact verbatim. 
- The answer to the question should not be found in the text alone. It should be a conclusion or synthesis of the knowledge.
- The questions should require a generalizable, deep understanding of the knowledge. 
- Be precise with the question formulation so that there is only one clear answer.

In addition, for each question, provide: 
- The prior knowledge that is required to answer the question. Academic papers build upon a large body of domain knowledge, and so there is an underlying assumption that the reader has a deep understanding of the domain knowledge for any paper.
- The sentences from the text that are required to answer the question. Cite from the text verbatim, and don't surround it with quotes.
- For a lay person, an explanation of what the question is asking.
- For a lay person, an explanation of how the answer is derived from the provided knowledge in the text.

### Output Format
Provide the question and answers in JSON, as a list of dictionaries with the following keys:
- "question": (string) 
- "answer": (string)
- "prior_knowledge": (string)
- "text_sentences": list of strings
- "question_explanation": (string)
- "inference_explanation": (string)
"""

prompt['user'] = f"""### Text
{section_text}"""

# Query LLM for questions
response = utils.query_llm(prompt, model='gpt-5', system_prompt_included=True, return_json=True, max_tokens=1000)

# Parse the JSON response
import json
parsed_questions = []

# Handle string response that needs JSON parsing
if isinstance(response, str):
    try:
        response = json.loads(response)
    except json.JSONDecodeError:
        print("Failed to parse JSON response")
        response = []

In [43]:
print(response)

{'qa_items': [{'question': 'Interpreting the optimal policy expression π_r(y|x) ∝ p_ref(y|x) · exp(r/β) as a Bayesian-style update, in what probabilistic role does the reference policy p_ref function within DPO’s learning view?', 'answer': 'a prior distribution', 'prior_knowledge': "Understanding that in Bayesian inference the posterior is proportional to the prior times a likelihood term; recognizing exp(reward/temperature) as an exponential family 'likelihood' factor that tilts a prior distribution.", 'text_sentences': ['it is straightforward to show that the optimal solution to the KL-constrained reward maximization objective in Eq.~\\ref{eq:RL} takes the form:', 'where $Z(x) =\\sum_{y}\\piref(y\\mid x)\\exp\\left(\\frac{1}{\\beta}r(x, y)\\right)$ is the partition function.', 'The added constraint is important, as it prevents the model from deviating too far from the distribution on which the reward model is accurate, as well as maintaining the generation diversity and preventing mode-collapse to single high-reward answers.'], 'question_explanation': 'It asks you to see the reference model’s role in the formula like a prior in Bayes’ rule.', 'inference_explanation': 'Because the optimal policy is proportional to the reference policy multiplied by an exponential of reward, this mirrors posterior ∝ prior × likelihood, so the reference behaves as a prior.'}, {'question': 'If the preference model depended on absolute reward levels rather than only on reward differences between responses, what critical algebraic simplification that enables DPO’s closed-form policy learning would fail?', 'answer': 'partition function cancellation', 'prior_knowledge': 'Knowing that subtracting or differencing removes additive constants; understanding that partition functions appear as additive constants in log-space and cancel when taking differences.', 'text_sentences': ['Fortunately, the Bradley-Terry model depends only on the difference of rewards between two completions, i.e., ${p^*(y_1 \\succ y_2 \\mid x) = \\sigma(r^*(x, y_1) - r^*(x, y_2))}$.', 'Substituting the reparameterization in Eq.~\\ref{eq:main_eq} for $r^*(x,y)$ into the preference model Eq.~\\ref{eq:bradley-terry}, the partition function cancels, and we can express the human preference probability in terms of only the optimal policy $\\pi^*$ and reference policy $\\piref$.'], 'question_explanation': 'It asks which mathematical trick DPO relies on that would break if labels depended on absolute rewards, not just differences.', 'inference_explanation': 'DPO leverages that preferences depend on reward differences so the partition function cancels; with absolute-level dependence, that cancellation would not happen.'}, {'question': 'In actor–critic terms, which quantity does DPO’s reparameterization eliminate the need to estimate during training, thereby improving stability relative to PPO?', 'answer': 'the soft value function', 'prior_knowledge': 'Actor–critic methods reduce gradient variance using value-function baselines; the soft value function corresponds to a log-partition-type normalization in entropy-regularized RL.', 'text_sentences': ['We can also use our framework to diagnose instabilities with standard actor-critic algorithms used for the RLHF, such as PPO.', 'In this setting, we can interpret the normalization term in $f(r_{\\phi}, \\piref, \\beta)$ as the soft value function of the reference policy $\\piref$.', 'While this term does not affect the optimal solution, without it, the policy gradient of the objective could have high variance, making learning unstable.', 'In contrast the DPO reparameterization yields a reward function that does not require any baselines.'], 'question_explanation': 'It asks what extra learned component PPO needs for stability that DPO avoids.', 'inference_explanation': 'Since the normalization term acts as a soft value baseline and DPO’s reparameterization avoids baselines, DPO removes the need to estimate the soft value function.'}, {'question': 'Given that adding any function f(x) to the reward leaves Bradley–Terry/Plackett–Luce preferences unchanged, what object does DPO recover uniquely despite this reward under-identification?', 'answer': 'the optimal policy', 'prior_knowledge': 'Equivalence classes: many reward functions can induce the same pairwise preferences, but if they yield the same optimal policy, that policy is the identifiable target.', 'text_sentences': ['Under the Plackett-Luce, and in particular the Bradley-Terry, preference framework, two reward functions from the same class induce the same preference distribution.', 'Two reward functions from the same equivalence class induce the same optimal policy under the constrained RL problem.', 'Note the optimization objective Eq. \\ref{eq:main_eq} is equivalent to a Bradley-Terry model with a reward parameterization $r^*(x, y) = \\beta \\log\\frac{\\pi^*_\\theta(y \\mid x)}{\\piref(y \\mid x)}$ and we optimize our parametric model $\\pi_{\\theta}$, equivalently to the reward model optimization in Eq. \\ref{eq:reward_model} under the change of variables.', 'In this section we will build the theory behind this reparameterization, show that it does not constrain the class of learned reward models, and allows for the exact recovery of the optimal policy.'], 'question_explanation': 'It asks what end result is still uniquely determined even though the reward itself isn’t.', 'inference_explanation': 'Because all rewards in an equivalence class induce the same optimal policy, DPO can uniquely recover that policy even when rewards are under-specified.'}, {'question': 'When the implicit reward already orders the preferred response above the dispreferred by a large margin, what happens to the size of DPO’s update for that pair?', 'answer': 'small update', 'prior_knowledge': 'The logistic function σ(z) approaches 0 when z is very negative; in weighted gradients, small weights yield small parameter updates.', 'text_sentences': ['The gradient with respect to the parameters $\\theta$ can be written as:', 'higher weight when reward estimate is wrong', 'Intuitively, the gradient of the loss function $\\mathcal{L}_\\text{DPO}$ increases the likelihood of the preferred completions $y_w$ and decreases the likelihood of dispreferred completions $y_l$.', 'Importantly, the examples are weighed by how much higher the implicit reward model $\\hat{r}_\\theta$ rates the dispreferred completions, scaled by $\\beta$, i.e, how incorrectly the implicit reward model orders the completions, accounting for the strength of the KL constraint.'], 'question_explanation': 'It asks what happens to the training signal when the model is already confident and correct.', 'inference_explanation': 'Because the weight is σ(r_l − r_w), and r_w ≫ r_l makes this very small, the update magnitude becomes small.'}, {'question': 'What expensive training-loop component of PPO-based RLHF does DPO avoid by turning preference learning into supervised classification over fixed pairs, thereby reducing compute?', 'answer': 'on-policy sampling', 'prior_knowledge': 'PPO training is on-policy and repeatedly samples from the current policy; supervised learning over a fixed dataset does not require such sampling.', 'text_sentences': ['The resulting algorithm, which we call \\textit{Direct Preference Optimization} (DPO), is stable, performant, and computationally lightweight, eliminating the need for sampling from the LM during fine-tuning or performing significant hyperparameter tuning.', 'While RLHF produces models with impressive conversational and coding abilities, the RLHF pipeline is considerably more complex than supervised learning, involving training multiple LMs and sampling from the LM policy in the loop of training, incurring significant computational costs.', 'Given a dataset of human preferences over model responses, DPO can therefore optimize a policy using a simple binary cross entropy objective, producing the optimal policy to an implicit reward function fit to the preference data.'], 'question_explanation': 'It asks which costly PPO step DPO removes by formulating a supervised objective.', 'inference_explanation': 'Because DPO uses a fixed preference dataset and a cross-entropy loss, it avoids the on-policy sampling loop required by PPO.'}, {'question': 'Because DPO and PPO optimize the same constrained objective but DPO strictly dominates PPO (and even PPO with ground-truth rewards) on the reward–KL frontier, what optimization pathology in PPO is the most plausible performance limiter?', 'answer': 'high-variance gradients', 'prior_knowledge': 'When two methods optimize the same objective, a worse frontier usually indicates optimization inefficiency or instability, such as high-gradient variance in policy gradients.', 'text_sentences': ['We find that DPO produces by far the most efficient frontier, achieving the highest reward while still achieving low KL.', "This result is particularly notable for multiple reasons. First, DPO and PPO optimize the same objective, but DPO is notably more efficient; DPO's reward/KL tradeoff strictly dominates PPO.", 'Second, DPO achieves a better frontier than PPO, \\emph{even when PPO can access ground truth rewards} (PPO-GT).', 'While this term does not affect the optimal solution, without it, the policy gradient of the objective could have high variance, making learning unstable.'], 'question_explanation': 'It asks you to infer what kind of training instability likely hurts PPO given DPO’s superior frontier on the same goal.', 'inference_explanation': 'Since objectives match, PPO’s inferiority points to optimization variance/instability; the text highlights high-variance policy gradients as a culprit.'}, {'question': 'In language generation, what failure mode is the KL constraint in the RLHF objective explicitly intended to prevent so that diversity is preserved?', 'answer': 'mode collapse', 'prior_knowledge': 'Mode collapse is when a model outputs a narrow set of responses, harming diversity.', 'text_sentences': ['The added constraint is important, as it prevents the model from deviating too far from the distribution on which the reward model is accurate, as well as maintaining the generation diversity and preventing mode-collapse to single high-reward answers.'], 'question_explanation': 'It asks what diversity-related problem the KL term is guarding against.', 'inference_explanation': 'The text states the KL prevents mode-collapse to single high-reward answers, i.e., mode collapse.'}, {'question': 'By defining the implicit reward as β·log(π/ p_ref) and maximizing Bradley–Terry likelihood on offline pairs, what quantity are we effectively using to tilt the reference policy into the learned policy?', 'answer': 'a likelihood ratio', 'prior_knowledge': 'A likelihood (or density) ratio π/p_ref reweights a base distribution to produce a new one; in log form it adds to rewards.', 'text_sentences': ['Specifically, we first take the logarithm of both sides of Eq.~\\ref{eq:op_policy} and then with some algebra we obtain:', 'This way, we fit an implicit reward using an alternative parameterization, whose optimal policy is simply $\\pi_\\theta$.', 'our policy objective becomes:', 'we can express the human preference probability in terms of only the optimal policy $\\pi^*$ and reference policy $\\piref$.'], 'question_explanation': 'It asks what mathematical factor transforms the reference distribution into the final policy under DPO.', 'inference_explanation': 'Because the implicit reward is β·log(π/p_ref), the policy is obtained by tilting p_ref with the likelihood ratio π/p_ref.'}, {'question': 'Under DPO’s reparameterization, what condition must the learned policy π satisfy so that it corresponds to a valid member of a reward equivalence class consistent with the preferences?', 'answer': 'valid probability distribution', 'prior_knowledge': 'A probability distribution must have nonnegative probabilities that sum to one; in exponential-family forms, this is enforced by a partition function constraint.', 'text_sentences': ['We can alternatively view Theorem~\\ref{thm:main} as specifying exactly which reward function within each equivalence class the DPO reparameterization selects, that is, the reward function satisfying:', 'i.e., $\\pi(y\\mid x)$ is a valid distribution (probabilities are positive and sum to 1).'], 'question_explanation': 'It asks what normalization property π must have to correspond to some consistent reward within the class.', 'inference_explanation': 'The text states the selected member satisfies a normalization that makes π a valid distribution (probabilities sum to one).'}, {'question': 'Inspecting the DPO loss, what discriminative quantity between the preferred and dispreferred responses does the model learn to push positive?', 'answer': 'a log-odds ratio', 'prior_knowledge': 'In logistic regression, the log-odds (logit) being positive corresponds to class 1 being more probable; here, the log-ratio difference plays that role.', 'text_sentences': ['Now that we have the probability of human preference data in terms of the optimal policy rather than the reward model, we can formulate a maximum likelihood objective for a parametrized policy $\\pi_\\theta$.', 'Analogous to the reward modeling approach (i.e. Eq.~\\ref{eq:reward_model}), our policy objective becomes:'], 'question_explanation': 'It asks what score the model tries to increase to favor the preferred answer.', 'inference_explanation': 'The loss is log σ(β log(π(y_w)/p_ref(y_w)) − β log(π(y_l)/p_ref(y_l))), so it drives the log-odds (difference of log-ratios) to be positive.'}, {'question': 'Relative to uniformly pushing up y_w and down y_l, what mechanism in DPO tempers updates on already well-ordered pairs while concentrating learning on misordered ones?', 'answer': 'confidence weighting', 'prior_knowledge': 'Logistic weights act like confidence-based weights: when the model is confident and correct, the weight is small; when it’s wrong, the weight is large.', 'text_sentences': ['higher weight when reward estimate is wrong', 'Importantly, the examples are weighed by how much higher the implicit reward model $\\hat{r}_\\theta$ rates the dispreferred completions, scaled by $\\beta$, i.e, how incorrectly the implicit reward model orders the completions, accounting for the strength of the KL constraint.', 'Our experiments suggest the importance of this weighting, as a na\\"ive version of this method without the weighting coefficient can cause the language model to degenerate (Appendix Table~\\ref{tab:unlikelihood_generations}).'], 'question_explanation': 'It asks what built-in weighting makes DPO focus on mistakes and ease off on already-correct cases.', 'inference_explanation': 'Because the gradient uses a logistic weight that’s larger when the model’s ordering is wrong and smaller when it’s right, DPO applies confidence-based weighting.'}]}

In [59]:
# Extract questions from response
dropped = 0
if isinstance(response, dict) and 'qa_items' in response:
    for item in response['qa_items']:
        # Check if all text sentences are actually in the paper
        all_sentences_found = True
        if 'text_sentences' in item and isinstance(item['text_sentences'], list):
            for sentence in item['text_sentences']:
                if sentence not in section_text:
                    all_sentences_found = False
                    break
        
        # Only process if all sentences are found in the paper
        if all_sentences_found:
            print_wrapped(f"Question: {item['question']}")
            print_wrapped(f"Answer: {item['answer']}")
            print_wrapped(f"Prior Knowledge: {item['prior_knowledge']}")
            print_wrapped(f"Text Sentences: {item['text_sentences']}")
            print_wrapped(f"Question Explanation: {item['question_explanation']}")
            print_wrapped(f"Inference Explanation: {item['inference_explanation']}")
            print_wrapped("---")
            
            parsed_questions.append({
                'question': item['question'],
                'answer': item['answer'],
                'prior_knowledge': item['prior_knowledge'],
                'text_sentences': item['text_sentences'],
                'question_explanation': item['question_explanation'],
                'inference_explanation': item['inference_explanation']
            })
        else:
            print_wrapped(f"DROPPED: Question with invalid text sentences: {item['question']}")
            dropped += 1

print(f"Dropped {dropped} out of {len(response['qa_items'])} questions")

Question: Interpreting the optimal policy expression π_r(y|x) ∝ p_ref(y|x) · exp(r/β) as a Bayesian-
style update, in what probabilistic role does the reference policy p_ref function within DPO’s
learning view?

Answer: a prior distribution

Prior Knowledge: Understanding that in Bayesian inference the posterior is proportional to the prior
times a likelihood term; recognizing exp(reward/temperature) as an exponential family 'likelihood'
factor that tilts a prior distribution.

Text Sentences: ['it is straightforward to show that the optimal solution to the KL-constrained
reward maximization objective in Eq.~\\ref{eq:RL} takes the form:', 'where $Z(x)
=\\sum_{y}\\piref(y\\mid x)\\exp\\left(\\frac{1}{\\beta}r(x, y)\\right)$ is the partition
function.', 'The added constraint is important, as it prevents the model from deviating too far from
the distribution on which the reward model is accurate, as well as maintaining the generation
diversity and preventing mode-collapse to single high-reward answers.']

Question Explanation: It asks you to see the reference model’s role in the formula like a prior in
Bayes’ rule.

Inference Explanation: Because the optimal policy is proportional to the reference policy multiplied
by an exponential of reward, this mirrors posterior ∝ prior × likelihood, so the reference behaves
as a prior.

---

Question: If the preference model depended on absolute reward levels rather than only on reward
differences between responses, what critical algebraic simplification that enables DPO’s closed-form
policy learning would fail?

Answer: partition function cancellation

Prior Knowledge: Knowing that subtracting or differencing removes additive constants; understanding
that partition functions appear as additive constants in log-space and cancel when taking
differences.

Text Sentences: ['Fortunately, the Bradley-Terry model depends only on the difference of rewards
between two completions, i.e., ${p^*(y_1 \\succ y_2 \\mid x) = \\sigma(r^*(x, y_1) - r^*(x,
y_2))}$.', 'Substituting the reparameterization in Eq.~\\ref{eq:main_eq} for $r^*(x,y)$ into the
preference model Eq.~\\ref{eq:bradley-terry}, the partition function cancels, and we can express the
human preference probability in terms of only the optimal policy $\\pi^*$ and reference policy
$\\piref$.']

Question Explanation: It asks which mathematical trick DPO relies on that would break if labels
depended on absolute rewards, not just differences.

Inference Explanation: DPO leverages that preferences depend on reward differences so the partition
function cancels; with absolute-level dependence, that cancellation would not happen.

---

Question: In actor–critic terms, which quantity does DPO’s reparameterization eliminate the need to
estimate during training, thereby improving stability relative to PPO?

Answer: the soft value function

Prior Knowledge: Actor–critic methods reduce gradient variance using value-function baselines; the
soft value function corresponds to a log-partition-type normalization in entropy-regularized RL.

Text Sentences: ['We can also use our framework to diagnose instabilities with standard actor-critic
algorithms used for the RLHF, such as PPO.', 'In this setting, we can interpret the normalization
term in $f(r_{\\phi}, \\piref, \\beta)$ as the soft value function of the reference policy
$\\piref$.', 'While this term does not affect the optimal solution, without it, the policy gradient
of the objective could have high variance, making learning unstable.', 'In contrast the DPO
reparameterization yields a reward function that does not require any baselines.']

Question Explanation: It asks what extra learned component PPO needs for stability that DPO avoids.

Inference Explanation: Since the normalization term acts as a soft value baseline and DPO’s
reparameterization avoids baselines, DPO removes the need to estimate the soft value function.

---

Question: Given that adding any function f(x) to the reward leaves Bradley–Terry/Plackett–Luce
preferences unchanged, what object does DPO recover uniquely despite this reward under-
identification?

Answer: the optimal policy

Prior Knowledge: Equivalence classes: many reward functions can induce the same pairwise
preferences, but if they yield the same optimal policy, that policy is the identifiable target.

Text Sentences: ['Under the Plackett-Luce, and in particular the Bradley-Terry, preference
framework, two reward functions from the same class induce the same preference distribution.', 'Two
reward functions from the same equivalence class induce the same optimal policy under the
constrained RL problem.', 'Note the optimization objective Eq. \\ref{eq:main_eq} is equivalent to a
Bradley-Terry model with a reward parameterization $r^*(x, y) = \\beta \\log\\frac{\\pi^*_\\theta(y
\\mid x)}{\\piref(y \\mid x)}$ and we optimize our parametric model $\\pi_{\\theta}$, equivalently
to the reward model optimization in Eq. \\ref{eq:reward_model} under the change of variables.', 'In
this section we will build the theory behind this reparameterization, show that it does not
constrain the class of learned reward models, and allows for the exact recovery of the optimal
policy.']

Question Explanation: It asks what end result is still uniquely determined even though the reward
itself isn’t.

Inference Explanation: Because all rewards in an equivalence class induce the same optimal policy,
DPO can uniquely recover that policy even when rewards are under-specified.

---

Question: When the implicit reward already orders the preferred response above the dispreferred by a
large margin, what happens to the size of DPO’s update for that pair?

Answer: small update

Prior Knowledge: The logistic function σ(z) approaches 0 when z is very negative; in weighted
gradients, small weights yield small parameter updates.

Text Sentences: ['The gradient with respect to the parameters $\\theta$ can be written as:', 'higher
weight when reward estimate is wrong', 'Intuitively, the gradient of the loss function
$\\mathcal{L}_\\text{DPO}$ increases the likelihood of the preferred completions $y_w$ and decreases
the likelihood of dispreferred completions $y_l$.', 'Importantly, the examples are weighed by how
much higher the implicit reward model $\\hat{r}_\\theta$ rates the dispreferred completions, scaled
by $\\beta$, i.e, how incorrectly the implicit reward model orders the completions, accounting for
the strength of the KL constraint.']

Question Explanation: It asks what happens to the training signal when the model is already
confident and correct.

Inference Explanation: Because the weight is σ(r_l − r_w), and r_w ≫ r_l makes this very small, the
update magnitude becomes small.

---

Question: What expensive training-loop component of PPO-based RLHF does DPO avoid by turning
preference learning into supervised classification over fixed pairs, thereby reducing compute?

Answer: on-policy sampling

Prior Knowledge: PPO training is on-policy and repeatedly samples from the current policy;
supervised learning over a fixed dataset does not require such sampling.

Text Sentences: ['The resulting algorithm, which we call \\textit{Direct Preference Optimization}
(DPO), is stable, performant, and computationally lightweight, eliminating the need for sampling
from the LM during fine-tuning or performing significant hyperparameter tuning.', 'While RLHF
produces models with impressive conversational and coding abilities, the RLHF pipeline is
considerably more complex than supervised learning, involving training multiple LMs and sampling
from the LM policy in the loop of training, incurring significant computational costs.', 'Given a
dataset of human preferences over model responses, DPO can therefore optimize a policy using a
simple binary cross entropy objective, producing the optimal policy to an implicit reward function
fit to the preference data.']

Question Explanation: It asks which costly PPO step DPO removes by formulating a supervised
objective.

Inference Explanation: Because DPO uses a fixed preference dataset and a cross-entropy loss, it
avoids the on-policy sampling loop required by PPO.

---

Question: Because DPO and PPO optimize the same constrained objective but DPO strictly dominates PPO
(and even PPO with ground-truth rewards) on the reward–KL frontier, what optimization pathology in
PPO is the most plausible performance limiter?

Answer: high-variance gradients

Prior Knowledge: When two methods optimize the same objective, a worse frontier usually indicates
optimization inefficiency or instability, such as high-gradient variance in policy gradients.

Text Sentences: ['We find that DPO produces by far the most efficient frontier, achieving the
highest reward while still achieving low KL.', "This result is particularly notable for multiple
reasons. First, DPO and PPO optimize the same objective, but DPO is notably more efficient; DPO's
reward/KL tradeoff strictly dominates PPO.", 'Second, DPO achieves a better frontier than PPO,
\\emph{even when PPO can access ground truth rewards} (PPO-GT).', 'While this term does not affect
the optimal solution, without it, the policy gradient of the objective could have high variance,
making learning unstable.']

Question Explanation: It asks you to infer what kind of training instability likely hurts PPO given
DPO’s superior frontier on the same goal.

Inference Explanation: Since objectives match, PPO’s inferiority points to optimization
variance/instability; the text highlights high-variance policy gradients as a culprit.

---

Question: In language generation, what failure mode is the KL constraint in the RLHF objective
explicitly intended to prevent so that diversity is preserved?

Answer: mode collapse

Prior Knowledge: Mode collapse is when a model outputs a narrow set of responses, harming diversity.

Text Sentences: ['The added constraint is important, as it prevents the model from deviating too far
from the distribution on which the reward model is accurate, as well as maintaining the generation
diversity and preventing mode-collapse to single high-reward answers.']

Question Explanation: It asks what diversity-related problem the KL term is guarding against.

Inference Explanation: The text states the KL prevents mode-collapse to single high-reward answers,
i.e., mode collapse.

---

Question: By defining the implicit reward as β·log(π/ p_ref) and maximizing Bradley–Terry likelihood
on offline pairs, what quantity are we effectively using to tilt the reference policy into the
learned policy?

Answer: a likelihood ratio

Prior Knowledge: A likelihood (or density) ratio π/p_ref reweights a base distribution to produce a
new one; in log form it adds to rewards.

Text Sentences: ['Specifically, we first take the logarithm of both sides of Eq.~\\ref{eq:op_policy}
and then with some algebra we obtain:', 'This way, we fit an implicit reward using an alternative
parameterization, whose optimal policy is simply $\\pi_\\theta$.', 'our policy objective becomes:',
'we can express the human preference probability in terms of only the optimal policy $\\pi^*$ and
reference policy $\\piref$.']

Question Explanation: It asks what mathematical factor transforms the reference distribution into
the final policy under DPO.

Inference Explanation: Because the implicit reward is β·log(π/p_ref), the policy is obtained by
tilting p_ref with the likelihood ratio π/p_ref.

---

Question: Under DPO’s reparameterization, what condition must the learned policy π satisfy so that
it corresponds to a valid member of a reward equivalence class consistent with the preferences?

Answer: valid probability distribution

Prior Knowledge: A probability distribution must have nonnegative probabilities that sum to one; in
exponential-family forms, this is enforced by a partition function constraint.

Text Sentences: ['We can alternatively view Theorem~\\ref{thm:main} as specifying exactly which
reward function within each equivalence class the DPO reparameterization selects, that is, the
reward function satisfying:', 'i.e., $\\pi(y\\mid x)$ is a valid distribution (probabilities are
positive and sum to 1).']

Question Explanation: It asks what normalization property π must have to correspond to some
consistent reward within the class.

Inference Explanation: The text states the selected member satisfies a normalization that makes π a
valid distribution (probabilities sum to one).

---

Question: Inspecting the DPO loss, what discriminative quantity between the preferred and
dispreferred responses does the model learn to push positive?

Answer: a log-odds ratio

Prior Knowledge: In logistic regression, the log-odds (logit) being positive corresponds to class 1
being more probable; here, the log-ratio difference plays that role.

Text Sentences: ['Now that we have the probability of human preference data in terms of the optimal
policy rather than the reward model, we can formulate a maximum likelihood objective for a
parametrized policy $\\pi_\\theta$.', 'Analogous to the reward modeling approach (i.e.
Eq.~\\ref{eq:reward_model}), our policy objective becomes:']

Question Explanation: It asks what score the model tries to increase to favor the preferred answer.

Inference Explanation: The loss is log σ(β log(π(y_w)/p_ref(y_w)) − β log(π(y_l)/p_ref(y_l))), so it
drives the log-odds (difference of log-ratios) to be positive.

---

Question: Relative to uniformly pushing up y_w and down y_l, what mechanism in DPO tempers updates
on already well-ordered pairs while concentrating learning on misordered ones?

Answer: confidence weighting

Prior Knowledge: Logistic weights act like confidence-based weights: when the model is confident and
correct, the weight is small; when it’s wrong, the weight is large.

Text Sentences: ['higher weight when reward estimate is wrong', 'Importantly, the examples are
weighed by how much higher the implicit reward model $\\hat{r}_\\theta$ rates the dispreferred
completions, scaled by $\\beta$, i.e, how incorrectly the implicit reward model orders the
completions, accounting for the strength of the KL constraint.', 'Our experiments suggest the
importance of this weighting, as a na\\"ive version of this method without the weighting coefficient
can cause the language model to degenerate (Appendix Table~\\ref{tab:unlikelihood_generations}).']

Question Explanation: It asks what built-in weighting makes DPO focus on mistakes and ease off on
already-correct cases.

Inference Explanation: Because the gradient uses a logistic weight that’s larger when the model’s
ordering is wrong and smaller when it’s right, DPO applies confidence-based weighting.

---

Dropped 0 out of 12 questions

#### 1.1 Convert Questions into Cloze Form Sentences

In [56]:
# Convert questions to text format with embedded answers using LLM
cloze_prompt = {}
cloze_prompt['system'] = r"""### Instructions
You will be given a list of pairs of questions and answers. Turn each question and answer into a statement in which the answer is placed at the very end. 
- The answer must be at the *very end* of the the last sentence. There should be no other words after the answer.
- The paraphrasing should be natural and flow well, with the answer naturally appearing at the very end. Avoid awkward repetition or forced placement of the answer. If restructuring the question to end with the answer feels unnatural or forced, discard that question entirely.
- Ensure the statement is grammatically correct and well-written. Adjust the answer only if necessary to maintain grammatical correctness.
- Preserve all information and context from the original question when converting to cloze form.
- Maintain the same sentence count as the original question.

### Demonstration

Question: Within the DPO theoretical section, the projection operator f normalizes the reward function by subtracting a term involving the policy’s partition function. Which mathematical function of the partition function is used for this normalization?  
Answer: logarithm

Statement: Within the DPO theoretical section, the projection operator f normalizes the reward function by subtracting a term involving the policy’s partition function. The mathematical function of the partition function used for this normalization is the logarithm.

### Output Format 
List the statements as a list of (answer, statement)."""
cloze_prompt['user'] = f"""### Questions and Answers\n{json.dumps(response['qa_items'])}\n"""
converted_response = utils.query_llm(cloze_prompt, model='gpt-5-mini', system_prompt_included=True, max_tokens=10000)

quality_control_prompt = {}
quality_control_prompt['system'] = r"""You are a meticulous Quality Control Assistant. Your task is to review and refine statements that have been extracted from an academic paper. You will be given a list of '(answer, statement)' pairs and the original context from which they were derived. Your task is to apply a rigorous checklist to each pair, refining it based on a provided quality control checklist.

### Quality Control Checklist

For each '(answer, statement)' pair, verify the following:

1. LaTeX Formatting
- All mathematical expressions and notations **MUST** be written in LaTeX, enclosed in '$' or '$$' delimiters.
- Do *NOT* use unicode mathematical characters (e.g., use '\\pi', not 'π').
- Do *NOT* use unnecessary styling commands like '\\displaystyle'.
- Ensure LaTeX syntax matches the style of the original context (e.g., '( ... )' or '$ ... $').
- Action: Rewrite the math expressions and statements so they can be written in LaTeX, keeping the rest of the statement the same, correcting any and all formatting errors related to mathematical notation.

In all your adjustments, change the statement as minimally as necessary. If a statement is already good, make no changes.
### Output Format
After your review, provide a list of the refined '(answer, statement)' pairs that have passed all checks in JSON."""
quality_control_prompt['user'] = f"""### Questions and Answers\n{converted_response}"""
refined_converted_response = utils.query_llm(quality_control_prompt, model='gpt-5-mini', system_prompt_included=True, return_json=True, max_tokens=10000)
refined_converted_response = json.loads(refined_converted_response)
print(refined_converted_response)

{'pairs': [['a prior distribution', "Interpreting the optimal policy expression $\\pi_r(y\\mid x) \\propto p_{\\text{ref}}(y\\mid x)\\exp(r/\\beta)$ as a Bayesian-style update in DPO's learning view, the reference policy $p_{\\text{ref}}$ plays the role of a prior distribution."], ['partition function cancellation', "If the preference model depended on absolute reward levels rather than only on reward differences between responses, the critical algebraic simplification that enables DPO's closed-form policy learning would fail: partition function cancellation."], ['the soft value function', "In actor-critic terms and relative to PPO, DPO's reparameterization removes the need to estimate the soft value function."], ['the optimal policy', 'Given that adding any function $f(x)$ to the reward leaves Bradley-Terry/Plackett-Luce preferences unchanged, DPO still uniquely recovers the optimal policy.'], ['small update', "When the implicit reward already orders the preferred response above the dispreferred by a large margin, the size of DPO's update for that pair is a small update."], ['on-policy sampling', 'By turning preference learning into supervised classification over fixed pairs, DPO avoids the expensive PPO training-loop component of on-policy sampling.'], ['high-variance gradients', "Because DPO and PPO optimize the same constrained objective yet DPO strictly dominates PPO on the reward-KL frontier (even versus PPO with ground-truth rewards), the most plausible optimization pathology limiting PPO's performance is high-variance gradients."], ['mode collapse', 'In language generation, the KL constraint in the RLHF objective is explicitly intended to prevent mode collapse.'], ['a likelihood ratio', 'By defining the implicit reward as $\\beta\\log\\left(\\frac{\\pi}{p_{\\text{ref}}}\\right)$ and maximizing the Bradley-Terry likelihood on offline pairs, we effectively tilt the reference policy into the learned policy using a likelihood ratio.'], ['valid probability distribution', "Under DPO's reparameterization, the learned policy $\\pi$ must satisfy the condition of being a valid probability distribution."], ['a log-odds ratio', 'Inspecting the DPO loss reveals that the discriminative quantity the model learns to push positive between the preferred and dispreferred responses is a log-odds ratio.'], ['confidence weighting', 'Relative to uniformly pushing up $y_w$ and down $y_l$, DPO tempers updates on already well-ordered pairs while concentrating learning on misordered ones through confidence weighting.']]}

#### 1.2 Split the sentences into "probe" and "target"

This is for evaluating the prediction of the target, given the rpobe

In [61]:
# Create probes from the refined response and merge with original QA data
valid_probes = []
dropped_count = 0

for i, (answer, statement) in enumerate(refined_converted_response['pairs']):
    # Strip punctuation from the end of the statement and check if it ends with the answer
    statement_stripped = statement.rstrip('.,!?;: ')
    if statement_stripped.lower().endswith(answer.lower()):
        # Create probe by removing the answer from the end
        probe = statement_stripped[:-len(answer)].rstrip()
        
        # Merge with original QA data
        original_qa = parsed_questions[i] if i < len(parsed_questions) else {}
        valid_probes.append({
            'target': answer,
            'probe': probe,
            'fact': statement,
            'question': original_qa.get('question', ''),
            'answer': original_qa.get('answer', ''),
            'prior_knowledge': original_qa.get('prior_knowledge', ''),
            'text_sentences': original_qa.get('text_sentences', ''),
            'question_explanation': original_qa.get('question_explanation', ''),
            'inference_explanation': original_qa.get('inference_explanation', '')
        })
    else:
        dropped_count += 1

print(f"Dropped {dropped_count} statements that don't end with their answer")

Dropped 0 statements that don't end with their answer

In [ ]:
# Create DataFrame and save as CSV
df = pd.DataFrame(valid_probes)
df.to_csv('dpo_high_level_probes_v2.csv', index=False)
print(f"Created {len(valid_probes)} probes and saved to dpo_high_level_probes_formatted.csv")
df

Created 12 probes and saved to dpo_high_level_probes_formatted.csv

,target,probe,fact,question,answer,prior_knowledge,text_sentences,question_explanation,inference_explanation
0,a prior distribution,Interpreting the optimal policy expression $\p...,Interpreting the optimal policy expression $\p...,Interpreting the optimal policy expression π_r...,a prior distribution,Understanding that in Bayesian inference the p...,[it is straightforward to show that the optima...,It asks you to see the reference model’s role ...,Because the optimal policy is proportional to ...
1,partition function cancellation,If the preference model depended on absolute r...,If the preference model depended on absolute r...,If the preference model depended on absolute r...,partition function cancellation,Knowing that subtracting or differencing remov...,"[Fortunately, the Bradley-Terry model depends ...",It asks which mathematical trick DPO relies on...,DPO leverages that preferences depend on rewar...
2,the soft value function,"In actor-critic terms and relative to PPO, DPO...","In actor-critic terms and relative to PPO, DPO...","In actor–critic terms, which quantity does DPO...",the soft value function,Actor–critic methods reduce gradient variance ...,[We can also use our framework to diagnose ins...,It asks what extra learned component PPO needs...,Since the normalization term acts as a soft va...
3,the optimal policy,Given that adding any function $f(x)$ to the r...,Given that adding any function $f(x)$ to the r...,Given that adding any function f(x) to the rew...,the optimal policy,Equivalence classes: many reward functions can...,"[Under the Plackett-Luce, and in particular th...",It asks what end result is still uniquely dete...,Because all rewards in an equivalence class in...
4,small update,When the implicit reward already orders the pr...,When the implicit reward already orders the pr...,When the implicit reward already orders the pr...,small update,The logistic function σ(z) approaches 0 when z...,[The gradient with respect to the parameters $...,It asks what happens to the training signal wh...,"Because the weight is σ(r_l − r_w), and r_w ≫ ..."
5,on-policy sampling,By turning preference learning into supervised...,By turning preference learning into supervised...,What expensive training-loop component of PPO-...,on-policy sampling,PPO training is on-policy and repeatedly sampl...,"[The resulting algorithm, which we call \texti...",It asks which costly PPO step DPO removes by f...,Because DPO uses a fixed preference dataset an...
6,high-variance gradients,Because DPO and PPO optimize the same constrai...,Because DPO and PPO optimize the same constrai...,Because DPO and PPO optimize the same constrai...,high-variance gradients,"When two methods optimize the same objective, ...",[We find that DPO produces by far the most eff...,It asks you to infer what kind of training ins...,"Since objectives match, PPO’s inferiority poin..."
7,mode collapse,"In language generation, the KL constraint in t...","In language generation, the KL constraint in t...","In language generation, what failure mode is t...",mode collapse,Mode collapse is when a model outputs a narrow...,"[The added constraint is important, as it prev...",It asks what diversity-related problem the KL ...,The text states the KL prevents mode-collapse ...
8,a likelihood ratio,By defining the implicit reward as $\beta\log\...,By defining the implicit reward as $\beta\log\...,By defining the implicit reward as β·log(π/ p_...,a likelihood ratio,A likelihood (or density) ratio π/p_ref reweig...,"[Specifically, we first take the logarithm of ...",It asks what mathematical factor transforms th...,"Because the implicit reward is β·log(π/p_ref),..."
9,valid probability distribution,"Under DPO's reparameterization, the learned po...","Under DPO's reparameterization, the learned po...","Under DPO’s reparameterization, what condition...",valid probability distribution,A probability distribution must have nonnegati...,[We can alternatively view Theorem~\ref{thm:ma...,It asks what normalization property π must hav...,The text states the selected member satisfies ...
10,a log-odds ratio,Inspecting the DPO loss reveals that the discr...,Inspecting the DPO loss reveals that the discr...,"Inspecting the DPO loss, what discriminative q...",a log-odds ratio,"In logistic regression, the log-odds (logit) b...",[Now that we have the probability of human pre...,It asks what score the model tries to increase...,The loss is log σ(β log(π(y_w)/p_ref(y_w)) − β...
11,confidence weighting,Relative to uniformly pushing up $y_w$ and dow...,Relative to uniformly pushing up $y_w$ and dow...,Relative to uniformly pushing up y_w and down ...,confidence weighting,Logistic weights act like confidence-based wei...,"[higher weight when reward estimate is wrong, ...",It asks what built-in weighting makes DPO focu...,Because the gradient uses a logistic weight th...

#### 1.3 Clean the probes and targets

In [65]:
df = pd.read_csv('../../data/arxiv/DPO_high_level_probes_v2.csv')

In [66]:
# Clean up the data: strip whitespace, remove punctuation, add space to target
df_cleaned = df.copy()

for i in range(len(df_cleaned)):
    # Strip whitespace from probe, target, and fact
    df_cleaned.at[i, 'probe'] = df_cleaned.at[i, 'probe'].strip()
    df_cleaned.at[i, 'target'] = df_cleaned.at[i, 'target'].strip()
    df_cleaned.at[i, 'fact'] = df_cleaned.at[i, 'fact'].strip()
    
    # Remove punctuation from end of target and fact if present
    target = df_cleaned.at[i, 'target'].rstrip('.,!?;:')
    fact = df_cleaned.at[i, 'fact'].rstrip('.,!?;:')
    
    # Add space in front of target
    target = ' ' + target
    
    # Update the dataframe
    df_cleaned.at[i, 'target'] = target
    df_cleaned.at[i, 'fact'] = fact

# Update df to use the cleaned version
df = df_cleaned
print(f"Cleaned {len(df)} rows: stripped whitespace, removed punctuation, added space to targets")

Cleaned 12 rows: stripped whitespace, removed punctuation, added space to targets

In [68]:
df.to_csv('dpo_high_level_probes_v2.csv', index=False)
print(f"Created {len(valid_probes)} probes and saved to dpo_high_level_probes_formatted.csv")
df

Created 12 probes and saved to dpo_high_level_probes_formatted.csv

,target,probe,fact,question,answer,prior_knowledge,text_sentences,question_explanation,inference_explanation
0,a prior distribution,Interpreting the optimal policy expression $\p...,Interpreting the optimal policy expression $\p...,Interpreting the optimal policy expression π_r...,a prior distribution,Understanding that in Bayesian inference the p...,['it is straightforward to show that the optim...,It asks you to see the reference model’s role ...,Because the optimal policy is proportional to ...
1,partition function cancellation,If the preference model depended on absolute r...,If the preference model depended on absolute r...,If the preference model depended on absolute r...,partition function cancellation,Knowing that subtracting or differencing remov...,"['Fortunately, the Bradley-Terry model depends...",It asks which mathematical trick DPO relies on...,DPO leverages that preferences depend on rewar...
2,the soft value function,"In actor-critic terms and relative to PPO, DPO...","In actor-critic terms and relative to PPO, DPO...","In actor–critic terms, which quantity does DPO...",the soft value function,Actor–critic methods reduce gradient variance ...,['We can also use our framework to diagnose in...,It asks what extra learned component PPO needs...,Since the normalization term acts as a soft va...
3,the optimal policy,Given that adding any function $f(x)$ to the r...,Given that adding any function $f(x)$ to the r...,Given that adding any function f(x) to the rew...,the optimal policy,Equivalence classes: many reward functions can...,"['Under the Plackett-Luce, and in particular t...",It asks what end result is still uniquely dete...,Because all rewards in an equivalence class in...
4,small update,When the implicit reward already orders the pr...,When the implicit reward already orders the pr...,When the implicit reward already orders the pr...,small update,The logistic function σ(z) approaches 0 when z...,['The gradient with respect to the parameters ...,It asks what happens to the training signal wh...,"Because the weight is σ(r_l − r_w), and r_w ≫ ..."
5,on-policy sampling,By turning preference learning into supervised...,By turning preference learning into supervised...,What expensive training-loop component of PPO-...,on-policy sampling,PPO training is on-policy and repeatedly sampl...,"['The resulting algorithm, which we call \\tex...",It asks which costly PPO step DPO removes by f...,Because DPO uses a fixed preference dataset an...
6,high-variance gradients,Because DPO and PPO optimize the same constrai...,Because DPO and PPO optimize the same constrai...,Because DPO and PPO optimize the same constrai...,high-variance gradients,"When two methods optimize the same objective, ...",['We find that DPO produces by far the most ef...,It asks you to infer what kind of training ins...,"Since objectives match, PPO’s inferiority poin..."
7,mode collapse,"In language generation, the KL constraint in t...","In language generation, the KL constraint in t...","In language generation, what failure mode is t...",mode collapse,Mode collapse is when a model outputs a narrow...,"['The added constraint is important, as it pre...",It asks what diversity-related problem the KL ...,The text states the KL prevents mode-collapse ...
8,a likelihood ratio,By defining the implicit reward as $\beta\log\...,By defining the implicit reward as $\beta\log\...,By defining the implicit reward as β·log(π/ p_...,a likelihood ratio,A likelihood (or density) ratio π/p_ref reweig...,"['Specifically, we first take the logarithm of...",It asks what mathematical factor transforms th...,"Because the implicit reward is β·log(π/p_ref),..."
9,valid probability distribution,"Under DPO's reparameterization, the learned po...","Under DPO's reparameterization, the learned po...","Under DPO’s reparameterization, what condition...",valid probability distribution,A probability distribution must have nonnegati...,['We can alternatively view Theorem~\\ref{thm:...,It asks what normalization property π must hav...,The text states the selected member satisfies ...
10,a log-odds ratio,Inspecting the DPO loss reveals that the discr...,Inspecting the DPO loss reveals that the discr...,"Inspecting the DPO loss, what discriminative q...",a log-odds ratio,"In logistic regression, the log-odds (logit) b...",['Now that we have the probability of human pr...,It asks what score the model tries to increase...,The loss is log σ(β log(π(y_w)/p_ref(y_w)) − β...
11,confidence weighting,Relative to uniformly pushing up $y_w$ and dow...,Relative to uniformly pushing up $y_w$ and dow...,Relative to uniformly pushing up y_w and down ...,confidence weighting,Logistic weights act like confidence-based wei...,['higher weight when reward estimate is wrong'...,It asks what built-in weighting makes DPO focu...,Because the gradient uses a logistic weight th...

#### 1.4 Split the questions as well actually into "probe" and "target"

We'll be doing the same we did for the cloze form sentences. We also keep the question form to evaluate the model *after* instruction-tuning

In [13]:
import pandas as pd
df = pd.read_csv('../../data/arxiv/DPO_high_level_probes_v2.csv')

In [14]:
# Create probe column by stripping question and adding "\nResponse:"
df['probe'] = df['question'].str.strip() + "\nResponse:"

# Create answer column by stripping answer and adding space before
df['answer'] = ' ' + df['answer'].str.strip()

# Create question_and_answer column by combining probe and answer
df['question_and_answer'] = df['probe'] + df['answer']

df['answer'][0]

' a prior distribution'

In [15]:
df = df.drop(columns=['target', 'fact'])
df.columns

Index(['probe', 'question', 'answer', 'prior_knowledge', 'text_sentences',
       'question_explanation', 'inference_explanation', 'question_and_answer'],
      dtype='object')

In [16]:
df.to_csv('dpo_high_level_probes_in_question_form_v2.csv', index=False)

### 2. Examine Probes

In [ ]:
df = pd.read_csv('../../data/arxiv/DPO_high_level_probes_v2.csv')

In [67]:
from transformers import AutoTokenizer

# Load tokenizer
tokenizer = AutoTokenizer.from_pretrained("allenai/OLMo-2-0425-1B")

contexts = df['probe'].tolist()
targets = df['target'].tolist()
facts = df['fact'].tolist()

print(f"--- Tokenizer and String Consistency Check ---")

string_mismatches = 0
token_mismatches = 0

for i, (context, target, fact) in enumerate(zip(contexts, targets, facts)):
    # --- String Level Check ---
    reconstructed_string = context + target
    string_match = reconstructed_string == fact
    
    if not string_match:
        string_mismatches += 1
        print(f"--- ❌ STRING MISMATCH: Sample #{i} ---")
        print(f"Context: '{context}'")
        print(f"Target:  '{target}'")
        print(f"Fact:    '{fact}'")
        print(f"Reconstructed: '{reconstructed_string}'")
        print(f"Match: {string_match}")
        print("-" * 30)
        continue
    
    # --- Tokenization Level Check ---
    # Method 1: Tokenize the fact directly
    tokenized_fact = tokenizer(fact, add_special_tokens=False, padding=False)['input_ids']
    
    # Method 2: Tokenize parts separately and concatenate
    tokenized_context = tokenizer(context, add_special_tokens=False, padding=False)['input_ids']
    tokenized_target = tokenizer(target, add_special_tokens=False, padding=False)['input_ids']
    tokenized_parts_combined = tokenized_context + tokenized_target

    # --- Comparison ---
    if tokenized_fact != tokenized_parts_combined:
        token_mismatches += 1
        print(f"--- ❌ TOKEN MISMATCH: Sample #{i} ---")
        print(f"Context: '{context}'")
        print(f"Target:  '{target}'")
        print(f"Fact:    '{fact}'")
        print(f"\nTokenizing fact directly:           {tokenized_fact} (Length: {len(tokenized_fact)})")
        print(f"Tokenizing parts and concatenating: {tokenized_parts_combined} (Length: {len(tokenized_parts_combined)})")
        
        # Find differing positions
        min_len = min(len(tokenized_fact), len(tokenized_parts_combined))
        diff_positions = []
        for pos in range(min_len):
            if tokenized_fact[pos] != tokenized_parts_combined[pos]:
                diff_positions.append(pos)
        
        if diff_positions:
            print(f"\nFirst differing positions: {diff_positions[:5]}")
            for pos in diff_positions[:3]:
                fact_token = tokenizer.decode([tokenized_fact[pos]])
                parts_token = tokenizer.decode([tokenized_parts_combined[pos]])
                print(f"  Position {pos}: fact='{fact_token}' vs parts='{parts_token}'")
        
        print("-" * 30)

print(f"\nSummary:")
print(f"String mismatches: {string_mismatches}")
print(f"Token mismatches: {token_mismatches}")
print(f"Total samples: {len(contexts)}")

--- Tokenizer and String Consistency Check ---

Summary:
String mismatches: 0
Token mismatches: 0
Total samples: 12